// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";

export class CompletionTrace {
    "requestId": string;
    "filePath": string;
    "language": string;
    "prefix": string;
    "accessChain": string;
    "resolvedOwner": string;
    "resolvedLibrary": string;
    "resolvedNamespace": string;
    "durationMs": number;
    "sourceDurationsMs": { [_ in string]?: number };
    "sourceStatuses": { [_ in string]?: string };
    "cacheStatus": { [_ in string]?: string };
    "staleDropped": number;
    "lspStatus": string;
    "lspListIncomplete": boolean;
    "cacheHit": boolean;
    "beforeFilter": number;
    "afterPrefixFilter": number;
    "afterContextFilter": number;
    "afterDedup": number;
    "resultCount": number;
    "sourceCounts": { [_ in string]?: number };
    "topSuggestions": TraceSuggestion[];

    /** Creates a new CompletionTrace instance. */
    constructor($$source: Partial<CompletionTrace> = {}) {
        if (!("requestId" in $$source)) {
            this["requestId"] = "";
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("prefix" in $$source)) {
            this["prefix"] = "";
        }
        if (!("accessChain" in $$source)) {
            this["accessChain"] = "";
        }
        if (!("resolvedOwner" in $$source)) {
            this["resolvedOwner"] = "";
        }
        if (!("resolvedLibrary" in $$source)) {
            this["resolvedLibrary"] = "";
        }
        if (!("resolvedNamespace" in $$source)) {
            this["resolvedNamespace"] = "";
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }
        if (!("sourceDurationsMs" in $$source)) {
            this["sourceDurationsMs"] = {};
        }
        if (!("sourceStatuses" in $$source)) {
            this["sourceStatuses"] = {};
        }
        if (!("cacheStatus" in $$source)) {
            this["cacheStatus"] = {};
        }
        if (!("staleDropped" in $$source)) {
            this["staleDropped"] = 0;
        }
        if (!("lspStatus" in $$source)) {
            this["lspStatus"] = "";
        }
        if (!("lspListIncomplete" in $$source)) {
            this["lspListIncomplete"] = false;
        }
        if (!("cacheHit" in $$source)) {
            this["cacheHit"] = false;
        }
        if (!("beforeFilter" in $$source)) {
            this["beforeFilter"] = 0;
        }
        if (!("afterPrefixFilter" in $$source)) {
            this["afterPrefixFilter"] = 0;
        }
        if (!("afterContextFilter" in $$source)) {
            this["afterContextFilter"] = 0;
        }
        if (!("afterDedup" in $$source)) {
            this["afterDedup"] = 0;
        }
        if (!("resultCount" in $$source)) {
            this["resultCount"] = 0;
        }
        if (!("sourceCounts" in $$source)) {
            this["sourceCounts"] = {};
        }
        if (!("topSuggestions" in $$source)) {
            this["topSuggestions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompletionTrace instance from a string or object.
     */
    static createFrom($$source: any = {}): CompletionTrace {
        const $$createField9_0 = $$createType0;
        const $$createField10_0 = $$createType1;
        const $$createField11_0 = $$createType1;
        const $$createField21_0 = $$createType2;
        const $$createField22_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sourceDurationsMs" in $$parsedSource) {
            $$parsedSource["sourceDurationsMs"] = $$createField9_0($$parsedSource["sourceDurationsMs"]);
        }
        if ("sourceStatuses" in $$parsedSource) {
            $$parsedSource["sourceStatuses"] = $$createField10_0($$parsedSource["sourceStatuses"]);
        }
        if ("cacheStatus" in $$parsedSource) {
            $$parsedSource["cacheStatus"] = $$createField11_0($$parsedSource["cacheStatus"]);
        }
        if ("sourceCounts" in $$parsedSource) {
            $$parsedSource["sourceCounts"] = $$createField21_0($$parsedSource["sourceCounts"]);
        }
        if ("topSuggestions" in $$parsedSource) {
            $$parsedSource["topSuggestions"] = $$createField22_0($$parsedSource["topSuggestions"]);
        }
        return new CompletionTrace($$parsedSource as Partial<CompletionTrace>);
    }
}

export class TraceSuggestion {
    "text": string;
    "source": core$0.SymbolSource;
    "kind": core$0.SymbolKind;
    "namespace"?: string;
    "score": number;

    /** Creates a new TraceSuggestion instance. */
    constructor($$source: Partial<TraceSuggestion> = {}) {
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = core$0.SymbolSource.$zero;
        }
        if (!("kind" in $$source)) {
            this["kind"] = core$0.SymbolKind.$zero;
        }
        if (!("score" in $$source)) {
            this["score"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TraceSuggestion instance from a string or object.
     */
    static createFrom($$source: any = {}): TraceSuggestion {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TraceSuggestion($$parsedSource as Partial<TraceSuggestion>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = TraceSuggestion.createFrom;
const $$createType4 = $Create.Array($$createType3);
