// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

export class Settings {
    "version": number;
    "enabled": boolean;
    "approvalRequired": boolean;
    "defaultApprovalTtlSeconds": number;
    "disabledTools": string[];

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("approvalRequired" in $$source)) {
            this["approvalRequired"] = false;
        }
        if (!("defaultApprovalTtlSeconds" in $$source)) {
            this["defaultApprovalTtlSeconds"] = 0;
        }
        if (!("disabledTools" in $$source)) {
            this["disabledTools"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("disabledTools" in $$parsedSource) {
            $$parsedSource["disabledTools"] = $$createField4_0($$parsedSource["disabledTools"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

export class ToolSettingsEntry {
    "name": string;
    "description": string;
    "group": string;
    "enabled": boolean;
    "effectiveEnabled": boolean;

    /** Creates a new ToolSettingsEntry instance. */
    constructor($$source: Partial<ToolSettingsEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("group" in $$source)) {
            this["group"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("effectiveEnabled" in $$source)) {
            this["effectiveEnabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolSettingsEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolSettingsEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolSettingsEntry($$parsedSource as Partial<ToolSettingsEntry>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
