// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

export class DependencyEdge {
    "source": string;
    "target": string;
    "kind": string;
    "line": number;

    /** Creates a new DependencyEdge instance. */
    constructor($$source: Partial<DependencyEdge> = {}) {
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("line" in $$source)) {
            this["line"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DependencyEdge instance from a string or object.
     */
    static createFrom($$source: any = {}): DependencyEdge {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DependencyEdge($$parsedSource as Partial<DependencyEdge>);
    }
}

export class DependencyGraph {
    "nodes": DependencyNode[];
    "edges": DependencyEdge[];

    /** Creates a new DependencyGraph instance. */
    constructor($$source: Partial<DependencyGraph> = {}) {
        if (!("nodes" in $$source)) {
            this["nodes"] = [];
        }
        if (!("edges" in $$source)) {
            this["edges"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DependencyGraph instance from a string or object.
     */
    static createFrom($$source: any = {}): DependencyGraph {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField0_0($$parsedSource["nodes"]);
        }
        if ("edges" in $$parsedSource) {
            $$parsedSource["edges"] = $$createField1_0($$parsedSource["edges"]);
        }
        return new DependencyGraph($$parsedSource as Partial<DependencyGraph>);
    }
}

export class DependencyNode {
    "path": string;
    "symbols": NodeSymbol[];

    /** Creates a new DependencyNode instance. */
    constructor($$source: Partial<DependencyNode> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("symbols" in $$source)) {
            this["symbols"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DependencyNode instance from a string or object.
     */
    static createFrom($$source: any = {}): DependencyNode {
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("symbols" in $$parsedSource) {
            $$parsedSource["symbols"] = $$createField1_0($$parsedSource["symbols"]);
        }
        return new DependencyNode($$parsedSource as Partial<DependencyNode>);
    }
}

export class FileRelation {
    "path": string;
    "type": RelationType;
    "lineNumber": number;
    "description": string;

    /** Creates a new FileRelation instance. */
    constructor($$source: Partial<FileRelation> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = RelationType.$zero;
        }
        if (!("lineNumber" in $$source)) {
            this["lineNumber"] = 0;
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileRelation instance from a string or object.
     */
    static createFrom($$source: any = {}): FileRelation {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileRelation($$parsedSource as Partial<FileRelation>);
    }
}

export class NodeSymbol {
    "name": string;
    "kind": string;
    "line": number;

    /** Creates a new NodeSymbol instance. */
    constructor($$source: Partial<NodeSymbol> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("line" in $$source)) {
            this["line"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodeSymbol instance from a string or object.
     */
    static createFrom($$source: any = {}): NodeSymbol {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NodeSymbol($$parsedSource as Partial<NodeSymbol>);
    }
}

export enum RelationType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RelationTypeRoute = "route",
    RelationTypeController = "controller",
    RelationTypeModel = "model",
    RelationTypeView = "view",
    RelationTypeMigration = "migration",
};

// Private type creation functions
const $$createType0 = DependencyNode.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = DependencyEdge.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = NodeSymbol.createFrom;
const $$createType5 = $Create.Array($$createType4);
