// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

export class Profile {
    "id": string;
    "label": string;
    "description": string;
    "kind": ProfileKind;
    "mode": ProfileMode;
    "command": string;
    "workingDirectory"?: string;
    "language"?: string;
    "framework"?: string;
    "origin"?: ProfileOrigin;
    "confidence"?: number;
    "requiredTools"?: string[];
    "missingTools"?: string[];
    "env"?: { [_ in string]?: string };

    /** Creates a new Profile instance. */
    constructor($$source: Partial<Profile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = ProfileKind.$zero;
        }
        if (!("mode" in $$source)) {
            this["mode"] = ProfileMode.$zero;
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Profile instance from a string or object.
     */
    static createFrom($$source: any = {}): Profile {
        const $$createField11_0 = $$createType0;
        const $$createField12_0 = $$createType0;
        const $$createField13_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("requiredTools" in $$parsedSource) {
            $$parsedSource["requiredTools"] = $$createField11_0($$parsedSource["requiredTools"]);
        }
        if ("missingTools" in $$parsedSource) {
            $$parsedSource["missingTools"] = $$createField12_0($$parsedSource["missingTools"]);
        }
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField13_0($$parsedSource["env"]);
        }
        return new Profile($$parsedSource as Partial<Profile>);
    }
}

export enum ProfileKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ProfileKindTerminal = "terminal",
    ProfileKindPreview = "preview",
};

export enum ProfileMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ProfileModeRun = "run",
    ProfileModeDebug = "debug",
};

export enum ProfileOrigin {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ProfileOriginAuto = "auto",
    ProfileOriginPlugin = "plugin",
    ProfileOriginImported = "imported",
    ProfileOriginUser = "user",
};

export class ProfileSet {
    "runProfiles": Profile[];
    "debugProfiles": Profile[];

    /** Creates a new ProfileSet instance. */
    constructor($$source: Partial<ProfileSet> = {}) {
        if (!("runProfiles" in $$source)) {
            this["runProfiles"] = [];
        }
        if (!("debugProfiles" in $$source)) {
            this["debugProfiles"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileSet instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileSet {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("runProfiles" in $$parsedSource) {
            $$parsedSource["runProfiles"] = $$createField0_0($$parsedSource["runProfiles"]);
        }
        if ("debugProfiles" in $$parsedSource) {
            $$parsedSource["debugProfiles"] = $$createField1_0($$parsedSource["debugProfiles"]);
        }
        return new ProfileSet($$parsedSource as Partial<ProfileSet>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = Profile.createFrom;
const $$createType3 = $Create.Array($$createType2);
