// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

export class AIModelDescriptor {
    "id": string;
    "displayName": string;
    "contextWindow"?: number;
    "streaming": boolean;
    "toolCalling"?: boolean;
    "structuredOutput"?: boolean;
    "patchGeneration"?: boolean;
    "lowLatency"?: boolean;
    "costTier"?: string;

    /** Creates a new AIModelDescriptor instance. */
    constructor($$source: Partial<AIModelDescriptor> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("streaming" in $$source)) {
            this["streaming"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIModelDescriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): AIModelDescriptor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIModelDescriptor($$parsedSource as Partial<AIModelDescriptor>);
    }
}

export enum AIProviderAuthMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ProviderAuthModeNone = "none",
    ProviderAuthModeAPIKey = "api_key",
    ProviderAuthModeOAuth = "oauth",
};

export enum AIProviderCapability {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CapabilityCodeCompletion = "code_completion",
    CapabilityLinePrediction = "line_prediction",
    CapabilityTerminalPrediction = "terminal_prediction",
    CapabilityChat = "chat",
    CapabilityToolCalling = "tool_calling",
    CapabilityStructuredOutput = "structured_output",
    CapabilityPatchGeneration = "patch_generation",
};

export class AIProviderDescriptor {
    "id": string;
    "name": string;
    "kind": string;
    "runtimeFamily"?: string;
    "endpoint"?: string;
    "endpointClass"?: string;
    "externalAccount"?: boolean;
    "binary"?: string;
    "local": boolean;
    "manual": boolean;
    "frontier": boolean;
    "authMode"?: AIProviderAuthMode;
    "authStatus"?: string;
    "billingMode"?: string;
    "legalBasis"?: string;
    "riskTier"?: string;
    "sourceLinks"?: string[];
    "supportedActions"?: string[];
    "oauthSupported": boolean;
    "requiresAuth": boolean;
    "authConfigured": boolean;
    "capabilities": AIProviderCapability[];
    "models": AIModelDescriptor[];
    "defaultModel"?: string;
    "status": AIProviderStatusValue;
    "reason"?: string;
    "lastCheckedAt"?: string;

    /** Creates a new AIProviderDescriptor instance. */
    constructor($$source: Partial<AIProviderDescriptor> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("local" in $$source)) {
            this["local"] = false;
        }
        if (!("manual" in $$source)) {
            this["manual"] = false;
        }
        if (!("frontier" in $$source)) {
            this["frontier"] = false;
        }
        if (!("oauthSupported" in $$source)) {
            this["oauthSupported"] = false;
        }
        if (!("requiresAuth" in $$source)) {
            this["requiresAuth"] = false;
        }
        if (!("authConfigured" in $$source)) {
            this["authConfigured"] = false;
        }
        if (!("capabilities" in $$source)) {
            this["capabilities"] = [];
        }
        if (!("models" in $$source)) {
            this["models"] = [];
        }
        if (!("status" in $$source)) {
            this["status"] = AIProviderStatusValue.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIProviderDescriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): AIProviderDescriptor {
        const $$createField16_0 = $$createType0;
        const $$createField17_0 = $$createType0;
        const $$createField21_0 = $$createType1;
        const $$createField22_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sourceLinks" in $$parsedSource) {
            $$parsedSource["sourceLinks"] = $$createField16_0($$parsedSource["sourceLinks"]);
        }
        if ("supportedActions" in $$parsedSource) {
            $$parsedSource["supportedActions"] = $$createField17_0($$parsedSource["supportedActions"]);
        }
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField21_0($$parsedSource["capabilities"]);
        }
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField22_0($$parsedSource["models"]);
        }
        return new AIProviderDescriptor($$parsedSource as Partial<AIProviderDescriptor>);
    }
}

export class AIProviderSettings {
    "id": string;
    "name"?: string;
    "kind": string;
    "endpoint"?: string;
    "model"?: string;
    "enabled": boolean;
    "manual": boolean;
    "capabilities"?: AIProviderCapability[];
    "secretRef"?: string;
    "secretValue"?: string;
    "clearSecret"?: boolean;
    "authMode"?: AIProviderAuthMode;
    "oauthClientId"?: string;
    "oauthSupported"?: boolean;

    /** Creates a new AIProviderSettings instance. */
    constructor($$source: Partial<AIProviderSettings> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("manual" in $$source)) {
            this["manual"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIProviderSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AIProviderSettings {
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField7_0($$parsedSource["capabilities"]);
        }
        return new AIProviderSettings($$parsedSource as Partial<AIProviderSettings>);
    }
}

export enum AIProviderStatusValue {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ProviderStatusDisabled = "disabled",
    ProviderStatusDiscovered = "discovered",
    ProviderStatusNeedsAuth = "needs_auth",
    ProviderStatusReady = "ready",
    ProviderStatusDegraded = "degraded",
    ProviderStatusError = "error",
};

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = AIModelDescriptor.createFrom;
const $$createType3 = $Create.Array($$createType2);
