// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ai$0 from "./internal/ai/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as providers$0 from "./internal/ai/providers/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as autocomplete$0 from "./internal/autocomplete/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as composer$0 from "./internal/composer/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as depsync$0 from "./internal/depsync/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dispatcher$0 from "./internal/dispatcher/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as execution$0 from "./internal/execution/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as indexer$0 from "./internal/indexer/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as brain$0 from "./internal/indexer/brain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as lsp$0 from "./internal/indexer/lsp/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mcp$0 from "./internal/mcp/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as plugins$0 from "./internal/plugins/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as project$0 from "./internal/project/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as system$0 from "./internal/system/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as welcome$0 from "./internal/ui/welcome/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AIApplyPatchArtifact(req: ai$0.AIPatchApplyRequest): $CancellablePromise<ai$0.AIPatchApplyResult> {
    return $Call.ByID(720800651, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function AIApproveMnemonicEntryProposal(req: ai$0.AIMnemonicApproveProposalRequest): $CancellablePromise<ai$0.AIMnemonicEntry> {
    return $Call.ByID(3627176462, req).then(($result: any) => {
        return $$createType1($result);
    });
}

export function AICancelChatRun(runID: string): $CancellablePromise<ai$0.AIChatRun> {
    return $Call.ByID(2942042952, runID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function AIClearChatRuns(): $CancellablePromise<void> {
    return $Call.ByID(357299996);
}

export function AIClearMnemonic(): $CancellablePromise<void> {
    return $Call.ByID(2807620704);
}

export function AIClearProviderSecret(providerID: string): $CancellablePromise<ai$0.AIProviderDescriptor> {
    return $Call.ByID(3793872273, providerID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function AIClearState(): $CancellablePromise<void> {
    return $Call.ByID(235808365);
}

export function AIDeleteChatSession(chatSessionID: string): $CancellablePromise<void> {
    return $Call.ByID(277582758, chatSessionID);
}

export function AIDeleteMnemonicEntry(id: string): $CancellablePromise<void> {
    return $Call.ByID(383368848, id);
}

export function AIExecuteToolCall(req: ai$0.AIToolCallRequest): $CancellablePromise<ai$0.AIToolCallResult> {
    return $Call.ByID(79851108, req).then(($result: any) => {
        return $$createType4($result);
    });
}

export function AIGetApprovalPolicy(): $CancellablePromise<ai$0.AIApprovalPolicy> {
    return $Call.ByID(3239357996).then(($result: any) => {
        return $$createType5($result);
    });
}

export function AIGetChatRun(runID: string): $CancellablePromise<ai$0.AIChatRun> {
    return $Call.ByID(2485175480, runID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function AIGetChatRunArtifact(artifactID: string): $CancellablePromise<ai$0.AIChatRunArtifact> {
    return $Call.ByID(1421136122, artifactID).then(($result: any) => {
        return $$createType6($result);
    });
}

export function AIGetChatRunEnvelope(runID: string): $CancellablePromise<ai$0.AIChatRunEnvelope> {
    return $Call.ByID(1518123300, runID).then(($result: any) => {
        return $$createType7($result);
    });
}

export function AIGetConsentPolicy(): $CancellablePromise<ai$0.AIConsentPolicy> {
    return $Call.ByID(185739619).then(($result: any) => {
        return $$createType8($result);
    });
}

export function AIGetContextPreview(req: ai$0.AIContextRequest): $CancellablePromise<ai$0.AIContextSnapshot> {
    return $Call.ByID(1617810636, req).then(($result: any) => {
        return $$createType9($result);
    });
}

export function AIGetEditorContinuation(req: ai$0.AIContextRequest, providerID: string, model: string): $CancellablePromise<ai$0.AIContinuationResponse> {
    return $Call.ByID(2602162403, req, providerID, model).then(($result: any) => {
        return $$createType10($result);
    });
}

export function AIGetEmbeddingStatus(): $CancellablePromise<ai$0.AIEmbeddingStatus> {
    return $Call.ByID(669940112).then(($result: any) => {
        return $$createType11($result);
    });
}

export function AIGetStatus(): $CancellablePromise<ai$0.AIStatus> {
    return $Call.ByID(2936535171).then(($result: any) => {
        return $$createType12($result);
    });
}

export function AIGetTerminalContinuation(req: ai$0.AIContextRequest, providerID: string, model: string): $CancellablePromise<ai$0.AIContinuationResponse> {
    return $Call.ByID(1640943938, req, providerID, model).then(($result: any) => {
        return $$createType10($result);
    });
}

export function AIInspectMnemonic(runID: string): $CancellablePromise<ai$0.AIMnemonicInspection> {
    return $Call.ByID(365510269, runID).then(($result: any) => {
        return $$createType13($result);
    });
}

export function AIListAgentProfiles(): $CancellablePromise<ai$0.AIAgentProfileDescriptor[]> {
    return $Call.ByID(1109101670).then(($result: any) => {
        return $$createType15($result);
    });
}

export function AIListChatActions(): $CancellablePromise<ai$0.AIChatActionDescriptor[]> {
    return $Call.ByID(2391356768).then(($result: any) => {
        return $$createType17($result);
    });
}

export function AIListChatRunArtifacts(runID: string): $CancellablePromise<ai$0.AIChatRunArtifact[]> {
    return $Call.ByID(3556308013, runID).then(($result: any) => {
        return $$createType18($result);
    });
}

export function AIListChatRuns(limit: number): $CancellablePromise<ai$0.AIChatRunEnvelope[]> {
    return $Call.ByID(2726976455, limit).then(($result: any) => {
        return $$createType19($result);
    });
}

export function AIListContextProviders(): $CancellablePromise<ai$0.AIContextProviderDescriptor[]> {
    return $Call.ByID(586247632).then(($result: any) => {
        return $$createType21($result);
    });
}

export function AIListEgressRecords(limit: number): $CancellablePromise<ai$0.AIEgressRecord[]> {
    return $Call.ByID(4258240650, limit).then(($result: any) => {
        return $$createType23($result);
    });
}

export function AIListMnemonicEntries(limit: number): $CancellablePromise<ai$0.AIMnemonicEntry[]> {
    return $Call.ByID(1449536265, limit).then(($result: any) => {
        return $$createType24($result);
    });
}

export function AIListModelCapabilities(): $CancellablePromise<ai$0.AIModelCapabilityDescriptor[]> {
    return $Call.ByID(4294009402).then(($result: any) => {
        return $$createType26($result);
    });
}

export function AIListPendingApprovals(limit: number): $CancellablePromise<ai$0.AIPendingApproval[]> {
    return $Call.ByID(814193330, limit).then(($result: any) => {
        return $$createType28($result);
    });
}

export function AIListPromptWorkflows(): $CancellablePromise<ai$0.AIPromptWorkflowDescriptor[]> {
    return $Call.ByID(3456087665).then(($result: any) => {
        return $$createType30($result);
    });
}

export function AIListProviderRuntimes(): $CancellablePromise<ai$0.AIProviderRuntimeDescriptor[]> {
    return $Call.ByID(1846561503).then(($result: any) => {
        return $$createType32($result);
    });
}

export function AIListProviders(): $CancellablePromise<ai$0.AIProviderDescriptor[]> {
    return $Call.ByID(1364497287).then(($result: any) => {
        return $$createType33($result);
    });
}

export function AIListToolAudit(limit: number): $CancellablePromise<ai$0.AIToolAuditRecord[]> {
    return $Call.ByID(2726014700, limit).then(($result: any) => {
        return $$createType35($result);
    });
}

export function AIListTools(): $CancellablePromise<ai$0.AIToolDescriptor[]> {
    return $Call.ByID(3522130974).then(($result: any) => {
        return $$createType37($result);
    });
}

export function AIPreviewBackgroundAgent(req: ai$0.AIBackgroundAgentPreviewRequest): $CancellablePromise<ai$0.AIBackgroundAgentPreviewResult> {
    return $Call.ByID(2326536090, req).then(($result: any) => {
        return $$createType38($result);
    });
}

export function AIPreviewPatch(req: ai$0.AIPatchPreviewRequest): $CancellablePromise<ai$0.AIPatchPreviewResult> {
    return $Call.ByID(3923597381, req).then(($result: any) => {
        return $$createType39($result);
    });
}

export function AIProbeModelCapability(req: ai$0.AIModelCapabilityProbeRequest): $CancellablePromise<ai$0.AIModelCapabilityProbeResult> {
    return $Call.ByID(3244589006, req).then(($result: any) => {
        return $$createType40($result);
    });
}

export function AIProposeMnemonicEntry(req: ai$0.AIMnemonicWriteProposalRequest): $CancellablePromise<ai$0.AIMnemonicWriteProposalResult> {
    return $Call.ByID(2623944841, req).then(($result: any) => {
        return $$createType41($result);
    });
}

export function AIRefreshLocalProviders(): $CancellablePromise<ai$0.AIDiscoveryResult> {
    return $Call.ByID(2658808305).then(($result: any) => {
        return $$createType42($result);
    });
}

export function AIRevokeApprovalPolicy(): $CancellablePromise<ai$0.AIApprovalPolicy> {
    return $Call.ByID(2979631040).then(($result: any) => {
        return $$createType5($result);
    });
}

export function AIRollbackPatchCheckpoint(req: ai$0.AIPatchRollbackRequest): $CancellablePromise<ai$0.AIPatchRollbackResult> {
    return $Call.ByID(3358042629, req).then(($result: any) => {
        return $$createType43($result);
    });
}

export function AISaveApprovalPolicy(policy: ai$0.AIApprovalPolicy): $CancellablePromise<ai$0.AIApprovalPolicy> {
    return $Call.ByID(3005051643, policy).then(($result: any) => {
        return $$createType5($result);
    });
}

export function AISaveConsentPolicy(policy: ai$0.AIConsentPolicy): $CancellablePromise<ai$0.AIConsentPolicy> {
    return $Call.ByID(2566415454, policy).then(($result: any) => {
        return $$createType8($result);
    });
}

export function AISaveMnemonicEntry(input: ai$0.AIMnemonicEntryInput): $CancellablePromise<ai$0.AIMnemonicEntry> {
    return $Call.ByID(1107955538, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function AISaveProviderSettings(settings: ai$0.AIProviderSettings): $CancellablePromise<ai$0.AIProviderDescriptor> {
    return $Call.ByID(2894980274, settings).then(($result: any) => {
        return $$createType3($result);
    });
}

export function AISearchMnemonic(req: ai$0.AIMnemonicSearchRequest): $CancellablePromise<ai$0.AIMnemonicEntry[]> {
    return $Call.ByID(3224526211, req).then(($result: any) => {
        return $$createType24($result);
    });
}

export function AISetMnemonicEnabled(enabled: boolean): $CancellablePromise<ai$0.AIStatus> {
    return $Call.ByID(32224322, enabled).then(($result: any) => {
        return $$createType12($result);
    });
}

export function AIStartChatRun(req: ai$0.AIChatRunRequest): $CancellablePromise<ai$0.AIChatRun> {
    return $Call.ByID(1756960180, req).then(($result: any) => {
        return $$createType2($result);
    });
}

export function AIStartProviderRuntime(req: ai$0.AIProviderRuntimeStartRequest): $CancellablePromise<ai$0.AIProviderRuntimeDescriptor> {
    return $Call.ByID(733577160, req).then(($result: any) => {
        return $$createType31($result);
    });
}

export function AIStopProviderRuntime(providerID: string): $CancellablePromise<ai$0.AIProviderRuntimeDescriptor> {
    return $Call.ByID(622949094, providerID).then(($result: any) => {
        return $$createType31($result);
    });
}

export function AISuggestChatMentions(req: ai$0.AIChatMentionQuery): $CancellablePromise<ai$0.AIChatMentionCandidate[]> {
    return $Call.ByID(1979552010, req).then(($result: any) => {
        return $$createType45($result);
    });
}

export function AITestProvider(providerID: string): $CancellablePromise<ai$0.AIProviderDescriptor> {
    return $Call.ByID(1815374578, providerID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function AIUpdateMnemonicEntry(id: string, patch: ai$0.AIMnemonicEntryPatch): $CancellablePromise<ai$0.AIMnemonicEntry> {
    return $Call.ByID(3053338550, id, patch).then(($result: any) => {
        return $$createType1($result);
    });
}

export function AnalyzeModels(modelName: string): $CancellablePromise<any> {
    return $Call.ByID(1703441345, modelName);
}

export function ApplyStagedAutoUpdate(): $CancellablePromise<$models.AutoUpdateStatus> {
    return $Call.ByID(3679133507).then(($result: any) => {
        return $$createType46($result);
    });
}

export function CacheClear(opts: system$0.CacheOptions): $CancellablePromise<string> {
    return $Call.ByID(2485317578, opts);
}

export function CancelApplicationClose(): $CancellablePromise<boolean> {
    return $Call.ByID(2241717081);
}

export function CancelAutoUpdate(): $CancellablePromise<$models.AutoUpdateStatus> {
    return $Call.ByID(1644581753).then(($result: any) => {
        return $$createType46($result);
    });
}

/**
 * CancelPrediction clears any pending predictions
 */
export function CancelPrediction(): $CancellablePromise<void> {
    return $Call.ByID(782425034);
}

export function CheckForAutoUpdate(): $CancellablePromise<$models.AutoUpdateStatus> {
    return $Call.ByID(3396333620).then(($result: any) => {
        return $$createType46($result);
    });
}

export function ClearApprovedDependencyActions(): $CancellablePromise<void> {
    return $Call.ByID(551981519);
}

export function ClearCompiled(): $CancellablePromise<string> {
    return $Call.ByID(3722612645);
}

export function ClearPrivateUpdateToken(): $CancellablePromise<$models.PrivateUpdateAuthStatus> {
    return $Call.ByID(2931162109).then(($result: any) => {
        return $$createType47($result);
    });
}

export function CloneRepository(repositoryURL: string, directory: string, projectName: string): $CancellablePromise<string> {
    return $Call.ByID(699215786, repositoryURL, directory, projectName);
}

export function CloseAllTerminals(): $CancellablePromise<void> {
    return $Call.ByID(2789416759);
}

export function CloseProject(): $CancellablePromise<void> {
    return $Call.ByID(371497096);
}

export function CloseTerminal(id: string): $CancellablePromise<void> {
    return $Call.ByID(2702963191, id);
}

export function ConfigCache(): $CancellablePromise<string> {
    return $Call.ByID(564655059);
}

export function ConfirmApplicationClose(): $CancellablePromise<boolean> {
    return $Call.ByID(2507142853);
}

/**
 * ConfirmPrediction is called when a command is executed
 */
export function ConfirmPrediction(input: string): $CancellablePromise<void> {
    return $Call.ByID(129421862, input);
}

export function CreateComponent(name: string, opts: plugins$0.ComponentOptions): $CancellablePromise<void> {
    return $Call.ByID(1817389248, name, opts);
}

export function CreateController(name: string, opts: plugins$0.ControllerOptions): $CancellablePromise<void> {
    return $Call.ByID(1147018977, name, opts);
}

export function CreateDirectory(dirPath: string): $CancellablePromise<void> {
    return $Call.ByID(148843624, dirPath);
}

export function CreateEnum(name: string, opts: plugins$0.EnumClassOptions): $CancellablePromise<void> {
    return $Call.ByID(2256510560, name, opts);
}

export function CreateEvent(name: string, opts: plugins$0.EventClassOptions): $CancellablePromise<void> {
    return $Call.ByID(2175910271, name, opts);
}

export function CreateFactory(name: string, opts: plugins$0.FactoryClassOptions): $CancellablePromise<void> {
    return $Call.ByID(2226223597, name, opts);
}

export function CreateJob(name: string, opts: plugins$0.JobOptions): $CancellablePromise<void> {
    return $Call.ByID(438146748, name, opts);
}

export function CreateLivewire(name: string, opts: plugins$0.LivewireComponentOptions): $CancellablePromise<void> {
    return $Call.ByID(4205678818, name, opts);
}

export function CreateMail(name: string, opts: plugins$0.MailOptions): $CancellablePromise<void> {
    return $Call.ByID(4095622286, name, opts);
}

export function CreateMigration(name: string, opts: plugins$0.MigrationOptions): $CancellablePromise<void> {
    return $Call.ByID(1635727883, name, opts);
}

export function CreateModel(name: string, opts: plugins$0.ModelOptions): $CancellablePromise<void> {
    return $Call.ByID(831544122, name, opts);
}

export function CreateNewProject(name: string, directory: string, framework: string): $CancellablePromise<string> {
    return $Call.ByID(2484331194, name, directory, framework);
}

export function CreateNotification(name: string, opts: plugins$0.NotificationOptions): $CancellablePromise<void> {
    return $Call.ByID(1709318310, name, opts);
}

export function CreatePolicy(name: string, opts: plugins$0.PolicyClassOptions): $CancellablePromise<void> {
    return $Call.ByID(3712890847, name, opts);
}

export function CreateResource(name: string, opts: plugins$0.ResourceClassOptions): $CancellablePromise<void> {
    return $Call.ByID(424049237, name, opts);
}

export function CreateSeeder(name: string, opts: plugins$0.SeederClassOptions): $CancellablePromise<void> {
    return $Call.ByID(2732034491, name, opts);
}

export function CreateTerminal(id: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2206554641, id, name);
}

export function CreateTerminalForProject(id: string, name: string, projectPath: string): $CancellablePromise<void> {
    return $Call.ByID(3177068569, id, name, projectPath);
}

export function DBSeed($class: string): $CancellablePromise<string> {
    return $Call.ByID(1771227798, $class);
}

export function DetectLanguage(code: string): $CancellablePromise<$models.LanguagePrediction[]> {
    return $Call.ByID(2080537768, code).then(($result: any) => {
        return $$createType49($result);
    });
}

export function DetectLanguageFromFile(filePath: string, content: string): $CancellablePromise<string> {
    return $Call.ByID(3871351310, filePath, content);
}

export function DispatchCommand(input: string): $CancellablePromise<$models.DispatcherResultJS> {
    return $Call.ByID(2776614912, input).then(($result: any) => {
        return $$createType50($result);
    });
}

export function DownloadAutoUpdate(): $CancellablePromise<$models.AutoUpdateStatus> {
    return $Call.ByID(2056857955).then(($result: any) => {
        return $$createType46($result);
    });
}

export function DumpAutoload(): $CancellablePromise<void> {
    return $Call.ByID(1668814544);
}

export function ExecuteQuery(query: string, bindings: any[]): $CancellablePromise<any> {
    return $Call.ByID(2868660388, query, bindings);
}

export function ExpandTag(input: string): $CancellablePromise<string> {
    return $Call.ByID(2843865679, input);
}

export function FindEnv(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(1851883877, path);
}

/**
 * FindFileByName searches for a file by name in a directory recursively
 * Returns all matching file paths
 */
export function FindFileByName(searchDir: string, fileName: string): $CancellablePromise<string[]> {
    return $Call.ByID(2000433386, searchDir, fileName).then(($result: any) => {
        return $$createType51($result);
    });
}

/**
 * FormatCode formats a file using code formatter (Prettier for JS/TS/HTML/CSS)
 */
export function FormatCode(filePath: string, content: string): $CancellablePromise<string> {
    return $Call.ByID(866530263, filePath, content);
}

export function GetAllLSPServers(): $CancellablePromise<$models.LSPServerInfo[]> {
    return $Call.ByID(797862055).then(($result: any) => {
        return $$createType53($result);
    });
}

export function GetAutoUpdateStatus(): $CancellablePromise<$models.AutoUpdateStatus> {
    return $Call.ByID(1364869703).then(($result: any) => {
        return $$createType46($result);
    });
}

/**
 * GetAutocompleteLanguageCapabilities returns language-level autocomplete support details.
 */
export function GetAutocompleteLanguageCapabilities(): $CancellablePromise<$models.AutocompleteLanguageCapability[]> {
    return $Call.ByID(3359005311).then(($result: any) => {
        return $$createType55($result);
    });
}

export function GetBackgroundShellStatus(): $CancellablePromise<$models.BackgroundShellStatusSnapshot> {
    return $Call.ByID(416663457).then(($result: any) => {
        return $$createType56($result);
    });
}

export function GetBuildInfo(): $CancellablePromise<$models.BuildInfo> {
    return $Call.ByID(3168473285).then(($result: any) => {
        return $$createType57($result);
    });
}

export function GetCurrentProjectFramework(): $CancellablePromise<string> {
    return $Call.ByID(3924508043);
}

export function GetCurrentProjectID(): $CancellablePromise<string> {
    return $Call.ByID(3837804544);
}

/**
 * GetCurrentProjectPath returns the current project root path
 */
export function GetCurrentProjectPath(): $CancellablePromise<string> {
    return $Call.ByID(3018154166);
}

export function GetCurrentProjectWindowSession(): $CancellablePromise<$models.ProjectWindowSessionPayload> {
    return $Call.ByID(2957557135).then(($result: any) => {
        return $$createType58($result);
    });
}

export function GetCurrentWorkDir(): $CancellablePromise<string> {
    return $Call.ByID(3338697468);
}

export function GetDependencyGraph(filePath: string, depth: number): $CancellablePromise<indexer$0.DependencyGraph | null> {
    return $Call.ByID(2819839938, filePath, depth).then(($result: any) => {
        return $$createType60($result);
    });
}

export function GetDependencyPolicyPlan(consentMode: string): $CancellablePromise<depsync$0.PolicyPlan> {
    return $Call.ByID(3641574495, consentMode).then(($result: any) => {
        return $$createType61($result);
    });
}

export function GetDependencySyncPlan(mode: string): $CancellablePromise<depsync$0.Plan> {
    return $Call.ByID(2260871246, mode).then(($result: any) => {
        return $$createType62($result);
    });
}

/**
 * GetDevToolsStatus returns installation status of development tools (PHP, Go, Node, etc.)
 */
export function GetDevToolsStatus(): $CancellablePromise<welcome$0.ToolStatus[]> {
    return $Call.ByID(4288915571).then(($result: any) => {
        return $$createType64($result);
    });
}

export function GetDispatcherPinned(): $CancellablePromise<$models.ResultItemJS[]> {
    return $Call.ByID(806680864).then(($result: any) => {
        return $$createType66($result);
    });
}

export function GetDispatcherRecent(): $CancellablePromise<$models.ResultItemJS[]> {
    return $Call.ByID(3736626413).then(($result: any) => {
        return $$createType66($result);
    });
}

export function GetDispatcherSuggestions(input: string): $CancellablePromise<$models.ResultItemJS[]> {
    return $Call.ByID(199250443, input).then(($result: any) => {
        return $$createType66($result);
    });
}

export function GetEditorCompletions(ctx: $models.EditorCompletionContext): $CancellablePromise<$models.EditorCompletionResult> {
    return $Call.ByID(780159089, ctx).then(($result: any) => {
        return $$createType67($result);
    });
}

export function GetExecutionProfiles(request: $models.ExecutionProfilesRequest): $CancellablePromise<execution$0.ProfileSet> {
    return $Call.ByID(3099827953, request).then(($result: any) => {
        return $$createType68($result);
    });
}

/**
 * GetGitBlame returns blame info for a file
 */
export function GetGitBlame(filePath: string): $CancellablePromise<string> {
    return $Call.ByID(805725620, filePath);
}

/**
 * GetGitBranch returns the current git branch name
 */
export function GetGitBranch(): $CancellablePromise<string> {
    return $Call.ByID(822115925);
}

/**
 * GetGitBranches returns list of all local branches
 */
export function GetGitBranches(): $CancellablePromise<string[]> {
    return $Call.ByID(3300336729).then(($result: any) => {
        return $$createType51($result);
    });
}

/**
 * GetGitCommitDiff returns the diff for a specific commit
 */
export function GetGitCommitDiff(commitHash: string): $CancellablePromise<string> {
    return $Call.ByID(1128195003, commitHash);
}

/**
 * GetGitDiff returns diff for a specific file or all changes
 */
export function GetGitDiff(filePath: string, staged: boolean): $CancellablePromise<string> {
    return $Call.ByID(2688063178, filePath, staged);
}

/**
 * GetGitFileAtCommit returns file content at specific commit
 */
export function GetGitFileAtCommit(filePath: string, commitHash: string): $CancellablePromise<string> {
    return $Call.ByID(824575699, filePath, commitHash);
}

/**
 * GetGitFileDiffBetweenCommits returns diff of a file between two commits
 */
export function GetGitFileDiffBetweenCommits(filePath: string, fromCommit: string, toCommit: string): $CancellablePromise<string> {
    return $Call.ByID(1493863738, filePath, fromCommit, toCommit);
}

/**
 * GetGitLog returns commit history
 */
export function GetGitLog(limit: number, filePath: string): $CancellablePromise<$models.GitCommitInfo[]> {
    return $Call.ByID(662482465, limit, filePath).then(($result: any) => {
        return $$createType70($result);
    });
}

/**
 * GetGitShow returns details of a specific commit
 */
export function GetGitShow(commitHash: string): $CancellablePromise<string> {
    return $Call.ByID(3575151916, commitHash);
}

/**
 * GetGitStatus returns git status in porcelain format
 */
export function GetGitStatus(): $CancellablePromise<string> {
    return $Call.ByID(4123560639);
}

export function GetInlineSuggestion(filePath: string, content: string, line: number, column: number, prefix: string): $CancellablePromise<string> {
    return $Call.ByID(1264721098, filePath, content, line, column, prefix);
}

export function GetLSPBinaryPath(serverID: string): $CancellablePromise<string> {
    return $Call.ByID(2087797756, serverID);
}

export function GetLSPForFile(filePath: string): $CancellablePromise<$models.LSPServerInfo | null> {
    return $Call.ByID(2936946335, filePath).then(($result: any) => {
        return $$createType71($result);
    });
}

/**
 * GetLSPInstallStatus returns installation status of LSP servers
 */
export function GetLSPInstallStatus(): $CancellablePromise<welcome$0.ToolStatus[]> {
    return $Call.ByID(1376901355).then(($result: any) => {
        return $$createType64($result);
    });
}

/**
 * GetLSPStatus returns health status of all LSP servers
 */
export function GetLSPStatus(): $CancellablePromise<lsp$0.ServerStatus[]> {
    return $Call.ByID(2864636116).then(($result: any) => {
        return $$createType73($result);
    });
}

export function GetLanguageForFile(filePath: string): $CancellablePromise<$models.LanguageInfoResult | null> {
    return $Call.ByID(3010003138, filePath).then(($result: any) => {
        return $$createType75($result);
    });
}

export function GetLaravelVersion(path: string): $CancellablePromise<string> {
    return $Call.ByID(3856876508, path);
}

export function GetLastAutocompleteTrace(): $CancellablePromise<brain$0.CompletionTrace> {
    return $Call.ByID(3298020088).then(($result: any) => {
        return $$createType76($result);
    });
}

export function GetMCPSettings(): $CancellablePromise<$models.MCPSettingsStatus> {
    return $Call.ByID(4245252768).then(($result: any) => {
        return $$createType77($result);
    });
}

export function GetMiddlewareList(): $CancellablePromise<any> {
    return $Call.ByID(1164193375);
}

export function GetPackagedOSIntegrationStatus(): $CancellablePromise<$models.PackagedOSIntegrationSnapshot> {
    return $Call.ByID(306335991).then(($result: any) => {
        return $$createType78($result);
    });
}

export function GetPluginCommands(): $CancellablePromise<$models.PluginCommandDefJS[]> {
    return $Call.ByID(657640170).then(($result: any) => {
        return $$createType80($result);
    });
}

export function GetPrivateUpdateAuthStatus(): $CancellablePromise<$models.PrivateUpdateAuthStatus> {
    return $Call.ByID(1353153095).then(($result: any) => {
        return $$createType47($result);
    });
}

export function GetProjectWindowSession(sessionID: string): $CancellablePromise<$models.ProjectWindowSessionPayload> {
    return $Call.ByID(3914333180, sessionID).then(($result: any) => {
        return $$createType58($result);
    });
}

export function GetRecentProjects(limit: number): $CancellablePromise<project$0.Project[]> {
    return $Call.ByID(2741556134, limit).then(($result: any) => {
        return $$createType82($result);
    });
}

export function GetRelatedFiles(filePath: string): $CancellablePromise<indexer$0.FileRelation[]> {
    return $Call.ByID(2982593757, filePath).then(($result: any) => {
        return $$createType84($result);
    });
}

export function GetRouteList(filter: string): $CancellablePromise<any> {
    return $Call.ByID(2062010460, filter);
}

export function GetSearchIndexStatus(): $CancellablePromise<dispatcher$0.SearchBackendStatus> {
    return $Call.ByID(3156983439).then(($result: any) => {
        return $$createType85($result);
    });
}

export function GetShellCapabilities(): $CancellablePromise<$models.ShellCapabilitiesSnapshot> {
    return $Call.ByID(1383723841).then(($result: any) => {
        return $$createType86($result);
    });
}

export function GetSupportedLanguages(): $CancellablePromise<string[]> {
    return $Call.ByID(3051367130).then(($result: any) => {
        return $$createType51($result);
    });
}

export function GetTerminalHistory(limit: number): $CancellablePromise<string[]> {
    return $Call.ByID(645152765, limit).then(($result: any) => {
        return $$createType51($result);
    });
}

export function GetTerminalPreview(command: string): $CancellablePromise<$models.TerminalPreviewJS> {
    return $Call.ByID(1649203157, command).then(($result: any) => {
        return $$createType87($result);
    });
}

export function GetWails3PackagedSmokeReport(args: string[]): $CancellablePromise<$models.Wails3PackagedSmokeReport> {
    return $Call.ByID(1809216711, args).then(($result: any) => {
        return $$createType88($result);
    });
}

export function GetWindowLeaseStatus(): $CancellablePromise<$models.WindowLeaseSnapshot> {
    return $Call.ByID(1757612373).then(($result: any) => {
        return $$createType89($result);
    });
}

/**
 * GoToDefinition finds definition for a symbol at given position
 * Uses indexed data for fast lookup, falls back to LSP
 */
export function GoToDefinition(filePath: string, content: string, line: number, column: number, word: string, beforeWord: string, afterWord: string): $CancellablePromise<$models.DefinitionResult[]> {
    return $Call.ByID(1326750791, filePath, content, line, column, word, beforeWord, afterWord).then(($result: any) => {
        return $$createType91($result);
    });
}

export function Greet(name: string): $CancellablePromise<string> {
    return $Call.ByID(2659711170, name);
}

export function ImportShellHistory(projectID: string, historyPath: string, workDir: string): $CancellablePromise<void> {
    return $Call.ByID(1481555862, projectID, historyPath, workDir);
}

export function IndexLaravelAll(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3240260503).then(($result: any) => {
        return $$createType92($result);
    });
}

export function IndexLaravelConfig(): $CancellablePromise<string> {
    return $Call.ByID(496107770);
}

export function IndexLaravelModels(): $CancellablePromise<string> {
    return $Call.ByID(2185329438);
}

export function IndexLaravelRoutes(): $CancellablePromise<string> {
    return $Call.ByID(1063508582);
}

export function IndexLaravelViews(): $CancellablePromise<string> {
    return $Call.ByID(2788361202);
}

export function InitDispatcherForProject(): $CancellablePromise<void> {
    return $Call.ByID(2987115106);
}

export function InspectEditorFile(filePath: string): $CancellablePromise<$models.EditorFileInspection> {
    return $Call.ByID(1991393444, filePath).then(($result: any) => {
        return $$createType93($result);
    });
}

export function InspectProject(): $CancellablePromise<any> {
    return $Call.ByID(2376510860);
}

export function InspectProjectAccess(path: string): $CancellablePromise<$models.ProjectAccessInspection> {
    return $Call.ByID(2417092806, path).then(($result: any) => {
        return $$createType94($result);
    });
}

export function InstallAll(): $CancellablePromise<void> {
    return $Call.ByID(3979437883);
}

export function InstallBreeze(): $CancellablePromise<void> {
    return $Call.ByID(3984307847);
}

/**
 * InstallDevTool installs a development tool or LSP server
 */
export function InstallDevTool(toolName: string): $CancellablePromise<string> {
    return $Call.ByID(3785770121, toolName);
}

export function InstallFortify(): $CancellablePromise<void> {
    return $Call.ByID(3683884497);
}

export function InstallJetstream(): $CancellablePromise<void> {
    return $Call.ByID(4262964215);
}

export function InstallLSPServer(serverID: string): $CancellablePromise<void> {
    return $Call.ByID(3352504172, serverID);
}

export function InstallLivewire(): $CancellablePromise<void> {
    return $Call.ByID(3749430535);
}

export function InstallPackage(name: string, opts: composer$0.InstallOptions): $CancellablePromise<void> {
    return $Call.ByID(611762984, name, opts);
}

export function IsLSPInstalling(serverID: string): $CancellablePromise<boolean> {
    return $Call.ByID(2897633925, serverID);
}

export function IsLangDetectorLoaded(): $CancellablePromise<boolean> {
    return $Call.ByID(1706972270);
}

export function IsLaravelProject(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(3484883515, path);
}

export function IsNativeFullscreen(): $CancellablePromise<boolean> {
    return $Call.ByID(852222967);
}

export function LSPApplyWorkspaceEdit(edit: $models.LSPWorkspaceEdit | null): $CancellablePromise<void> {
    return $Call.ByID(4218232197, edit);
}

export function LSPGetCodeActions(filePath: string, content: string, line: number, character: number): $CancellablePromise<$models.LSPCodeAction[]> {
    return $Call.ByID(2004919368, filePath, content, line, character).then(($result: any) => {
        return $$createType96($result);
    });
}

export function LSPGetDiagnostics(filePath: string): $CancellablePromise<$models.LSPDiagnostic[]> {
    return $Call.ByID(2740795840, filePath).then(($result: any) => {
        return $$createType98($result);
    });
}

/**
 * LSPGoToDefinition finds definition using unified LSP manager
 */
export function LSPGoToDefinition(filePath: string, content: string, line: number, character: number): $CancellablePromise<$models.LSPDefinitionResult[]> {
    return $Call.ByID(1637549358, filePath, content, line, character).then(($result: any) => {
        return $$createType100($result);
    });
}

/**
 * LSPHover returns hover information for a symbol
 */
export function LSPHover(filePath: string, content: string, line: number, character: number): $CancellablePromise<string> {
    return $Call.ByID(2120599106, filePath, content, line, character);
}

export function LSPPreloadProjectDiagnostics(projectPath: string): $CancellablePromise<boolean> {
    return $Call.ByID(2755018294, projectPath);
}

/**
 * LSPSignatureHelp returns signature help for a function call
 */
export function LSPSignatureHelp(filePath: string, content: string, line: number, character: number): $CancellablePromise<$models.SignatureHelpResult | null> {
    return $Call.ByID(4147834173, filePath, content, line, character).then(($result: any) => {
        return $$createType102($result);
    });
}

export function ListApprovedDependencyActions(): $CancellablePromise<string[]> {
    return $Call.ByID(3578679726).then(($result: any) => {
        return $$createType51($result);
    });
}

export function ListInstalledPackages(): $CancellablePromise<string> {
    return $Call.ByID(3315868544);
}

export function ListTerminalSessions(): $CancellablePromise<string[]> {
    return $Call.ByID(2383672116).then(($result: any) => {
        return $$createType51($result);
    });
}

export function Migrate(opts: system$0.MigrateOptions): $CancellablePromise<string> {
    return $Call.ByID(31804598, opts);
}

export function MigrateFresh(opts: system$0.MigrateRefreshOptions): $CancellablePromise<string> {
    return $Call.ByID(2851604802, opts);
}

export function MigrateRefresh(opts: system$0.MigrateRefreshOptions): $CancellablePromise<string> {
    return $Call.ByID(161550973, opts);
}

export function MigrateReset(opts: system$0.MigrateResetOptions): $CancellablePromise<string> {
    return $Call.ByID(3810832729, opts);
}

export function MigrateRollback(opts: system$0.MigrateRollbackOptions): $CancellablePromise<string> {
    return $Call.ByID(2746725622, opts);
}

export function MigrateSeed(opts: system$0.MigrateOptions): $CancellablePromise<string> {
    return $Call.ByID(3045603055, opts);
}

export function MigrateStatus(): $CancellablePromise<string> {
    return $Call.ByID(3450203256);
}

export function MoveProjectEntry(path: string, targetDirectory: string): $CancellablePromise<$models.ProjectEntryMoveResult> {
    return $Call.ByID(2860771743, path, targetDirectory).then(($result: any) => {
        return $$createType103($result);
    });
}

/**
 * NotifyFileChanged notifies LSP servers when a file content changes
 */
export function NotifyFileChanged(filePath: string, language: string, version: number, content: string): $CancellablePromise<void> {
    return $Call.ByID(3640445830, filePath, language, version, content);
}

/**
 * NotifyFileClosed notifies LSP servers when a file is closed
 */
export function NotifyFileClosed(filePath: string, language: string): $CancellablePromise<void> {
    return $Call.ByID(3753785758, filePath, language);
}

/**
 * NotifyFileOpened notifies LSP servers when a file is opened in the editor
 */
export function NotifyFileOpened(filePath: string, language: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(3996156971, filePath, language, content);
}

export function OpenNativeContextMenu(request: $models.NativeContextMenuRequest): $CancellablePromise<$models.NativeContextMenuResponse> {
    return $Call.ByID(2956928310, request).then(($result: any) => {
        return $$createType104($result);
    });
}

export function OpenProject(path: string): $CancellablePromise<void> {
    return $Call.ByID(517162042, path);
}

export function OpenProjectWindow(path: string): $CancellablePromise<$models.ProjectWindowLaunchResult> {
    return $Call.ByID(206289462, path).then(($result: any) => {
        return $$createType105($result);
    });
}

export function OpenProjectWindowSession(sessionID: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(3016106250, sessionID, path);
}

export function ParseCommand(input: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(2145746925, input).then(($result: any) => {
        return $$createType92($result);
    });
}

export function PinCommand(cmd: string): $CancellablePromise<void> {
    return $Call.ByID(1809965573, cmd);
}

export function PositionNativeWindowControls(closeX: number, closeY: number, minimiseX: number, minimiseY: number, maximiseX: number, maximiseY: number): $CancellablePromise<boolean> {
    return $Call.ByID(106707367, closeX, closeY, minimiseX, minimiseY, maximiseX, maximiseY);
}

export function PredictCommand(input: string): $CancellablePromise<$models.ClassResult | null> {
    return $Call.ByID(57982963, input).then(($result: any) => {
        return $$createType107($result);
    });
}

export function PredictTerminalCommand(req: $models.TerminalPredictionRequest): $CancellablePromise<$models.TerminalPredictionResponse> {
    return $Call.ByID(3772631451, req).then(($result: any) => {
        return $$createType108($result);
    });
}

export function PublishAssets(packageName: string, tags: string[]): $CancellablePromise<void> {
    return $Call.ByID(4032289609, packageName, tags);
}

export function QueueWork(connection: string, queue: string): $CancellablePromise<void> {
    return $Call.ByID(160704349, connection, queue);
}

export function ReadDirectory(dirPath: string): $CancellablePromise<$models.FileEntry[]> {
    return $Call.ByID(3882613584, dirPath).then(($result: any) => {
        return $$createType110($result);
    });
}

export function ReadEditorBinaryFile(filePath: string): $CancellablePromise<$models.EditorBinaryFile> {
    return $Call.ByID(38130499, filePath).then(($result: any) => {
        return $$createType111($result);
    });
}

export function ReadEditorFilePreview(filePath: string, maxBytes: number): $CancellablePromise<$models.EditorFilePreview> {
    return $Call.ByID(3674158986, filePath, maxBytes).then(($result: any) => {
        return $$createType112($result);
    });
}

export function ReadEditorVisualFile(filePath: string): $CancellablePromise<$models.EditorVisualFile> {
    return $Call.ByID(963892010, filePath).then(($result: any) => {
        return $$createType113($result);
    });
}

export function ReadFile(filePath: string): $CancellablePromise<string> {
    return $Call.ByID(1160596971, filePath);
}

export function RebuildSearchIndex(): $CancellablePromise<dispatcher$0.SearchBackendStatus> {
    return $Call.ByID(3600539824).then(($result: any) => {
        return $$createType85($result);
    });
}

export function RecordCommandExecution(projectID: string, command: string, workDir: string): $CancellablePromise<void> {
    return $Call.ByID(4263319117, projectID, command, workDir);
}

export function RecordCompletionUsage(label: string): $CancellablePromise<void> {
    return $Call.ByID(2439147269, label);
}

export function RecordFileAccess(filePath: string): $CancellablePromise<void> {
    return $Call.ByID(4232286036, filePath);
}

export function RecordGhostRejected(): $CancellablePromise<void> {
    return $Call.ByID(2901661065);
}

export function RecordGhostShown(): $CancellablePromise<void> {
    return $Call.ByID(3641459704);
}

export function RecordTypingActivity(chars: number): $CancellablePromise<void> {
    return $Call.ByID(438320990, chars);
}

export function RefreshNativeWindowControls(): $CancellablePromise<boolean> {
    return $Call.ByID(2428329793);
}

export function RemovePackage(name: string, opts: composer$0.RemoveOptions): $CancellablePromise<void> {
    return $Call.ByID(4138363611, name, opts);
}

export function RenameProjectEntry(path: string, newName: string): $CancellablePromise<$models.ProjectEntryRenameResult> {
    return $Call.ByID(121090124, path, newName).then(($result: any) => {
        return $$createType114($result);
    });
}

export function ResizeTerminal(id: string, rows: number, cols: number): $CancellablePromise<void> {
    return $Call.ByID(1887984285, id, rows, cols);
}

/**
 * RestartLSPServer force-restarts a specific LSP server.
 */
export function RestartLSPServer(language: string): $CancellablePromise<boolean> {
    return $Call.ByID(843672400, language);
}

export function RevealProjectEntry(path: string): $CancellablePromise<void> {
    return $Call.ByID(610992635, path);
}

export function RouteCache(): $CancellablePromise<string> {
    return $Call.ByID(1653131812);
}

export function RunBackgroundShellAction(actionID: string): $CancellablePromise<$models.BackgroundShellActionResult> {
    return $Call.ByID(2677002422, actionID).then(($result: any) => {
        return $$createType115($result);
    });
}

export function RunDependencyPolicySync(req: depsync$0.ExecuteRequest): $CancellablePromise<depsync$0.ExecuteResult> {
    return $Call.ByID(4055326678, req).then(($result: any) => {
        return $$createType116($result);
    });
}

/**
 * RunGitCommand executes a git command in the project directory
 */
export function RunGitCommand(args: string[]): $CancellablePromise<string> {
    return $Call.ByID(1772246131, args);
}

export function RunMigrate(): $CancellablePromise<void> {
    return $Call.ByID(970276291);
}

export function RunPackagedOSIntegrationAction(actionID: string): $CancellablePromise<$models.PackagedOSActionResult> {
    return $Call.ByID(212070764, actionID).then(($result: any) => {
        return $$createType117($result);
    });
}

export function RunWindowLeaseAction(actionID: string): $CancellablePromise<$models.WindowLeaseActionResult> {
    return $Call.ByID(1355862670, actionID).then(($result: any) => {
        return $$createType118($result);
    });
}

export function SaveMCPSettings(settings: mcp$0.Settings): $CancellablePromise<$models.MCPSettingsStatus> {
    return $Call.ByID(366671897, settings).then(($result: any) => {
        return $$createType77($result);
    });
}

export function SavePrivateUpdateToken(token: string): $CancellablePromise<$models.PrivateUpdateAuthStatus> {
    return $Call.ByID(3034741135, token).then(($result: any) => {
        return $$createType47($result);
    });
}

export function ScheduleRun(): $CancellablePromise<string> {
    return $Call.ByID(1996637713);
}

export function SearchClasses(prefix: string): $CancellablePromise<$models.ClassResult[]> {
    return $Call.ByID(1440811547, prefix).then(($result: any) => {
        return $$createType119($result);
    });
}

export function SearchContent(query: string): $CancellablePromise<$models.ResultItemJS[]> {
    return $Call.ByID(837782406, query).then(($result: any) => {
        return $$createType66($result);
    });
}

export function SearchFiles(pattern: string): $CancellablePromise<$models.ResultItemJS[]> {
    return $Call.ByID(3203090108, pattern).then(($result: any) => {
        return $$createType66($result);
    });
}

/**
 * SearchInProject searches for a query string in all project files
 */
export function SearchInProject(query: string, caseSensitive: boolean, useRegex: boolean, wholeWord: boolean): $CancellablePromise<$models.SearchResult[]> {
    return $Call.ByID(1951647779, query, caseSensitive, useRegex, wholeWord).then(($result: any) => {
        return $$createType121($result);
    });
}

export function SearchSymbols(query: string): $CancellablePromise<$models.ResultItemJS[]> {
    return $Call.ByID(342316914, query).then(($result: any) => {
        return $$createType66($result);
    });
}

export function SelectDirectory(title: string): $CancellablePromise<string> {
    return $Call.ByID(1735672136, title);
}

export function SelectOpenTarget(title: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(620958940, title).then(($result: any) => {
        return $$createType92($result);
    });
}

export function SendTerminalText(id: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(1308733900, id, text);
}

export function Serve(opts: system$0.ServeOptions): $CancellablePromise<void> {
    return $Call.ByID(1252611052, opts);
}

export function SetApplicationIconAppearance(appearance: string): $CancellablePromise<boolean> {
    return $Call.ByID(1321818672, appearance);
}

export function SetCloseConfirmationEnabled(enabled: boolean): $CancellablePromise<boolean> {
    return $Call.ByID(468326553, enabled);
}

export function SetNativeWindowControlsVisible(visible: boolean): $CancellablePromise<boolean> {
    return $Call.ByID(922935632, visible);
}

export function ShowPackageInfo(name: string): $CancellablePromise<string> {
    return $Call.ByID(2020960992, name);
}

export function StorageLink(): $CancellablePromise<string> {
    return $Call.ByID(3354398342);
}

export function SuggestCommand(input: string): $CancellablePromise<$models.CommandSuggestion[]> {
    return $Call.ByID(21596122, input).then(($result: any) => {
        return $$createType123($result);
    });
}

export function SyncApplicationMenuShortcuts(payload: $models.ApplicationMenuShortcutPayload[]): $CancellablePromise<void> {
    return $Call.ByID(3664212066, payload);
}

export function SyncProjectDependencies(mode: string): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(2790870830, mode).then(($result: any) => {
        return $$createType124($result);
    });
}

export function Tinker(): $CancellablePromise<void> {
    return $Call.ByID(79624690);
}

export function ToggleNativeFullscreen(): $CancellablePromise<void> {
    return $Call.ByID(169440215);
}

export function TrashProjectEntry(path: string): $CancellablePromise<void> {
    return $Call.ByID(840343694, path);
}

export function UnpinCommand(cmd: string): $CancellablePromise<void> {
    return $Call.ByID(1072443974, cmd);
}

export function UpdateAll(): $CancellablePromise<void> {
    return $Call.ByID(2857062695);
}

export function UpdatePackage(name: string): $CancellablePromise<void> {
    return $Call.ByID(3631571604, name);
}

/**
 * UpdatePrediction updates the speculative store based on terminal input
 */
export function UpdatePrediction(input: string): $CancellablePromise<void> {
    return $Call.ByID(1334482297, input);
}

export function ValidateEnvironment(): $CancellablePromise<{ [_ in string]?: boolean }> {
    return $Call.ByID(1433890444).then(($result: any) => {
        return $$createType125($result);
    });
}

export function ViewCache(): $CancellablePromise<string> {
    return $Call.ByID(690827050);
}

export function WriteFile(filePath: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(3562730546, filePath, content);
}

export function WriteTerminal(id: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(146795716, id, data);
}

// Private type creation functions
const $$createType0 = ai$0.AIPatchApplyResult.createFrom;
const $$createType1 = ai$0.AIMnemonicEntry.createFrom;
const $$createType2 = ai$0.AIChatRun.createFrom;
const $$createType3 = providers$0.AIProviderDescriptor.createFrom;
const $$createType4 = ai$0.AIToolCallResult.createFrom;
const $$createType5 = ai$0.AIApprovalPolicy.createFrom;
const $$createType6 = ai$0.AIChatRunArtifact.createFrom;
const $$createType7 = ai$0.AIChatRunEnvelope.createFrom;
const $$createType8 = ai$0.AIConsentPolicy.createFrom;
const $$createType9 = ai$0.AIContextSnapshot.createFrom;
const $$createType10 = ai$0.AIContinuationResponse.createFrom;
const $$createType11 = ai$0.AIEmbeddingStatus.createFrom;
const $$createType12 = ai$0.AIStatus.createFrom;
const $$createType13 = ai$0.AIMnemonicInspection.createFrom;
const $$createType14 = ai$0.AIAgentProfileDescriptor.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = ai$0.AIChatActionDescriptor.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = $Create.Array($$createType6);
const $$createType19 = $Create.Array($$createType7);
const $$createType20 = ai$0.AIContextProviderDescriptor.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = ai$0.AIEgressRecord.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = $Create.Array($$createType1);
const $$createType25 = ai$0.AIModelCapabilityDescriptor.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = ai$0.AIPendingApproval.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = ai$0.AIPromptWorkflowDescriptor.createFrom;
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = ai$0.AIProviderRuntimeDescriptor.createFrom;
const $$createType32 = $Create.Array($$createType31);
const $$createType33 = $Create.Array($$createType3);
const $$createType34 = ai$0.AIToolAuditRecord.createFrom;
const $$createType35 = $Create.Array($$createType34);
const $$createType36 = ai$0.AIToolDescriptor.createFrom;
const $$createType37 = $Create.Array($$createType36);
const $$createType38 = ai$0.AIBackgroundAgentPreviewResult.createFrom;
const $$createType39 = ai$0.AIPatchPreviewResult.createFrom;
const $$createType40 = ai$0.AIModelCapabilityProbeResult.createFrom;
const $$createType41 = ai$0.AIMnemonicWriteProposalResult.createFrom;
const $$createType42 = ai$0.AIDiscoveryResult.createFrom;
const $$createType43 = ai$0.AIPatchRollbackResult.createFrom;
const $$createType44 = ai$0.AIChatMentionCandidate.createFrom;
const $$createType45 = $Create.Array($$createType44);
const $$createType46 = $models.AutoUpdateStatus.createFrom;
const $$createType47 = $models.PrivateUpdateAuthStatus.createFrom;
const $$createType48 = $models.LanguagePrediction.createFrom;
const $$createType49 = $Create.Array($$createType48);
const $$createType50 = $models.DispatcherResultJS.createFrom;
const $$createType51 = $Create.Array($Create.Any);
const $$createType52 = $models.LSPServerInfo.createFrom;
const $$createType53 = $Create.Array($$createType52);
const $$createType54 = autocomplete$0.LanguageCapability.createFrom;
const $$createType55 = $Create.Array($$createType54);
const $$createType56 = $models.BackgroundShellStatusSnapshot.createFrom;
const $$createType57 = $models.BuildInfo.createFrom;
const $$createType58 = $models.ProjectWindowSessionPayload.createFrom;
const $$createType59 = indexer$0.DependencyGraph.createFrom;
const $$createType60 = $Create.Nullable($$createType59);
const $$createType61 = depsync$0.PolicyPlan.createFrom;
const $$createType62 = depsync$0.Plan.createFrom;
const $$createType63 = welcome$0.ToolStatus.createFrom;
const $$createType64 = $Create.Array($$createType63);
const $$createType65 = $models.ResultItemJS.createFrom;
const $$createType66 = $Create.Array($$createType65);
const $$createType67 = $models.EditorCompletionResult.createFrom;
const $$createType68 = execution$0.ProfileSet.createFrom;
const $$createType69 = $models.GitCommitInfo.createFrom;
const $$createType70 = $Create.Array($$createType69);
const $$createType71 = $Create.Nullable($$createType52);
const $$createType72 = lsp$0.ServerStatus.createFrom;
const $$createType73 = $Create.Array($$createType72);
const $$createType74 = $models.LanguageInfoResult.createFrom;
const $$createType75 = $Create.Nullable($$createType74);
const $$createType76 = brain$0.CompletionTrace.createFrom;
const $$createType77 = $models.MCPSettingsStatus.createFrom;
const $$createType78 = $models.PackagedOSIntegrationSnapshot.createFrom;
const $$createType79 = $models.PluginCommandDefJS.createFrom;
const $$createType80 = $Create.Array($$createType79);
const $$createType81 = project$0.Project.createFrom;
const $$createType82 = $Create.Array($$createType81);
const $$createType83 = indexer$0.FileRelation.createFrom;
const $$createType84 = $Create.Array($$createType83);
const $$createType85 = dispatcher$0.SearchBackendStatus.createFrom;
const $$createType86 = $models.ShellCapabilitiesSnapshot.createFrom;
const $$createType87 = $models.TerminalPreviewJS.createFrom;
const $$createType88 = $models.Wails3PackagedSmokeReport.createFrom;
const $$createType89 = $models.WindowLeaseSnapshot.createFrom;
const $$createType90 = $models.DefinitionResult.createFrom;
const $$createType91 = $Create.Array($$createType90);
const $$createType92 = $Create.Map($Create.Any, $Create.Any);
const $$createType93 = $models.EditorFileInspection.createFrom;
const $$createType94 = $models.ProjectAccessInspection.createFrom;
const $$createType95 = $models.LSPCodeAction.createFrom;
const $$createType96 = $Create.Array($$createType95);
const $$createType97 = $models.LSPDiagnostic.createFrom;
const $$createType98 = $Create.Array($$createType97);
const $$createType99 = $models.LSPDefinitionResult.createFrom;
const $$createType100 = $Create.Array($$createType99);
const $$createType101 = $models.SignatureHelpResult.createFrom;
const $$createType102 = $Create.Nullable($$createType101);
const $$createType103 = $models.ProjectEntryMoveResult.createFrom;
const $$createType104 = $models.NativeContextMenuResponse.createFrom;
const $$createType105 = $models.ProjectWindowLaunchResult.createFrom;
const $$createType106 = $models.ClassResult.createFrom;
const $$createType107 = $Create.Nullable($$createType106);
const $$createType108 = $models.TerminalPredictionResponse.createFrom;
const $$createType109 = $models.FileEntry.createFrom;
const $$createType110 = $Create.Array($$createType109);
const $$createType111 = $models.EditorBinaryFile.createFrom;
const $$createType112 = $models.EditorFilePreview.createFrom;
const $$createType113 = $models.EditorVisualFile.createFrom;
const $$createType114 = $models.ProjectEntryRenameResult.createFrom;
const $$createType115 = $models.BackgroundShellActionResult.createFrom;
const $$createType116 = depsync$0.ExecuteResult.createFrom;
const $$createType117 = $models.PackagedOSActionResult.createFrom;
const $$createType118 = $models.WindowLeaseActionResult.createFrom;
const $$createType119 = $Create.Array($$createType106);
const $$createType120 = $models.SearchResult.createFrom;
const $$createType121 = $Create.Array($$createType120);
const $$createType122 = $models.CommandSuggestion.createFrom;
const $$createType123 = $Create.Array($$createType122);
const $$createType124 = $Create.Map($Create.Any, $Create.Any);
const $$createType125 = $Create.Map($Create.Any, $Create.Any);
