// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as composer$0 from "./internal/composer/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as depsync$0 from "./internal/depsync/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as execution$0 from "./internal/execution/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as indexer$0 from "./internal/indexer/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as brain$0 from "./internal/indexer/brain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as lsp$0 from "./internal/indexer/lsp/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as plugins$0 from "./internal/plugins/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as project$0 from "./internal/project/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as system$0 from "./internal/system/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as welcome$0 from "./internal/ui/welcome/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AnalyzeModels(modelName: string): $CancellablePromise<any> {
    return $Call.ByID(1703441345, modelName);
}

export function CacheClear(opts: system$0.CacheOptions): $CancellablePromise<string> {
    return $Call.ByID(2485317578, opts);
}

/**
 * CancelPrediction clears any pending predictions
 */
export function CancelPrediction(): $CancellablePromise<void> {
    return $Call.ByID(782425034);
}

export function ClearApprovedDependencyActions(): $CancellablePromise<void> {
    return $Call.ByID(551981519);
}

export function ClearCompiled(): $CancellablePromise<string> {
    return $Call.ByID(3722612645);
}

export function CloneRepository(repositoryURL: string, directory: string, projectName: string): $CancellablePromise<string> {
    return $Call.ByID(699215786, repositoryURL, directory, projectName);
}

export function CloseAllTerminals(): $CancellablePromise<void> {
    return $Call.ByID(2789416759);
}

export function CloseProject(): $CancellablePromise<void> {
    return $Call.ByID(371497096);
}

export function CloseTerminal(id: string): $CancellablePromise<void> {
    return $Call.ByID(2702963191, id);
}

export function ConfigCache(): $CancellablePromise<string> {
    return $Call.ByID(564655059);
}

/**
 * ConfirmPrediction is called when a command is executed
 */
export function ConfirmPrediction(input: string): $CancellablePromise<void> {
    return $Call.ByID(129421862, input);
}

export function CreateComponent(name: string, opts: plugins$0.ComponentOptions): $CancellablePromise<void> {
    return $Call.ByID(1817389248, name, opts);
}

export function CreateController(name: string, opts: plugins$0.ControllerOptions): $CancellablePromise<void> {
    return $Call.ByID(1147018977, name, opts);
}

export function CreateDirectory(dirPath: string): $CancellablePromise<void> {
    return $Call.ByID(148843624, dirPath);
}

export function CreateEnum(name: string, opts: plugins$0.EnumClassOptions): $CancellablePromise<void> {
    return $Call.ByID(2256510560, name, opts);
}

export function CreateEvent(name: string, opts: plugins$0.EventClassOptions): $CancellablePromise<void> {
    return $Call.ByID(2175910271, name, opts);
}

export function CreateFactory(name: string, opts: plugins$0.FactoryClassOptions): $CancellablePromise<void> {
    return $Call.ByID(2226223597, name, opts);
}

export function CreateJob(name: string, opts: plugins$0.JobOptions): $CancellablePromise<void> {
    return $Call.ByID(438146748, name, opts);
}

export function CreateLivewire(name: string, opts: plugins$0.LivewireComponentOptions): $CancellablePromise<void> {
    return $Call.ByID(4205678818, name, opts);
}

export function CreateMail(name: string, opts: plugins$0.MailOptions): $CancellablePromise<void> {
    return $Call.ByID(4095622286, name, opts);
}

export function CreateMigration(name: string, opts: plugins$0.MigrationOptions): $CancellablePromise<void> {
    return $Call.ByID(1635727883, name, opts);
}

export function CreateModel(name: string, opts: plugins$0.ModelOptions): $CancellablePromise<void> {
    return $Call.ByID(831544122, name, opts);
}

export function CreateNewProject(name: string, directory: string, framework: string): $CancellablePromise<string> {
    return $Call.ByID(2484331194, name, directory, framework);
}

export function CreateNotification(name: string, opts: plugins$0.NotificationOptions): $CancellablePromise<void> {
    return $Call.ByID(1709318310, name, opts);
}

export function CreatePolicy(name: string, opts: plugins$0.PolicyClassOptions): $CancellablePromise<void> {
    return $Call.ByID(3712890847, name, opts);
}

export function CreateResource(name: string, opts: plugins$0.ResourceClassOptions): $CancellablePromise<void> {
    return $Call.ByID(424049237, name, opts);
}

export function CreateSeeder(name: string, opts: plugins$0.SeederClassOptions): $CancellablePromise<void> {
    return $Call.ByID(2732034491, name, opts);
}

export function CreateTerminal(id: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2206554641, id, name);
}

export function CreateTerminalForProject(id: string, name: string, projectPath: string): $CancellablePromise<void> {
    return $Call.ByID(3177068569, id, name, projectPath);
}

export function DBSeed($class: string): $CancellablePromise<string> {
    return $Call.ByID(1771227798, $class);
}

export function DetectLanguage(code: string): $CancellablePromise<$models.LanguagePrediction[]> {
    return $Call.ByID(2080537768, code).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DetectLanguageFromFile(filePath: string, content: string): $CancellablePromise<string> {
    return $Call.ByID(3871351310, filePath, content);
}

export function DispatchCommand(input: string): $CancellablePromise<$models.DispatcherResultJS> {
    return $Call.ByID(2776614912, input).then(($result: any) => {
        return $$createType2($result);
    });
}

export function DumpAutoload(): $CancellablePromise<void> {
    return $Call.ByID(1668814544);
}

export function ExecuteQuery(query: string, bindings: any[]): $CancellablePromise<any> {
    return $Call.ByID(2868660388, query, bindings);
}

export function ExpandTag(input: string): $CancellablePromise<string> {
    return $Call.ByID(2843865679, input);
}

export function FindEnv(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(1851883877, path);
}

/**
 * FindFileByName searches for a file by name in a directory recursively
 * Returns all matching file paths
 */
export function FindFileByName(searchDir: string, fileName: string): $CancellablePromise<string[]> {
    return $Call.ByID(2000433386, searchDir, fileName).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * FormatCode formats a file using code formatter (Prettier for JS/TS/HTML/CSS)
 */
export function FormatCode(filePath: string, content: string): $CancellablePromise<string> {
    return $Call.ByID(866530263, filePath, content);
}

export function GetAllLSPServers(): $CancellablePromise<$models.LSPServerInfo[]> {
    return $Call.ByID(797862055).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetBackgroundShellStatus(): $CancellablePromise<$models.BackgroundShellStatusSnapshot> {
    return $Call.ByID(416663457).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetCurrentProjectFramework(): $CancellablePromise<string> {
    return $Call.ByID(3924508043);
}

export function GetCurrentProjectID(): $CancellablePromise<string> {
    return $Call.ByID(3837804544);
}

/**
 * GetCurrentProjectPath returns the current project root path
 */
export function GetCurrentProjectPath(): $CancellablePromise<string> {
    return $Call.ByID(3018154166);
}

export function GetCurrentWorkDir(): $CancellablePromise<string> {
    return $Call.ByID(3338697468);
}

export function GetDependencyGraph(filePath: string, depth: number): $CancellablePromise<indexer$0.DependencyGraph | null> {
    return $Call.ByID(2819839938, filePath, depth).then(($result: any) => {
        return $$createType8($result);
    });
}

export function GetDependencyPolicyPlan(consentMode: string): $CancellablePromise<depsync$0.PolicyPlan> {
    return $Call.ByID(3641574495, consentMode).then(($result: any) => {
        return $$createType9($result);
    });
}

export function GetDependencySyncPlan(mode: string): $CancellablePromise<depsync$0.Plan> {
    return $Call.ByID(2260871246, mode).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * GetDevToolsStatus returns installation status of development tools (PHP, Go, Node, etc.)
 */
export function GetDevToolsStatus(): $CancellablePromise<welcome$0.ToolStatus[]> {
    return $Call.ByID(4288915571).then(($result: any) => {
        return $$createType12($result);
    });
}

export function GetDispatcherPinned(): $CancellablePromise<$models.ResultItemJS[]> {
    return $Call.ByID(806680864).then(($result: any) => {
        return $$createType14($result);
    });
}

export function GetDispatcherRecent(): $CancellablePromise<$models.ResultItemJS[]> {
    return $Call.ByID(3736626413).then(($result: any) => {
        return $$createType14($result);
    });
}

export function GetDispatcherSuggestions(input: string): $CancellablePromise<$models.ResultItemJS[]> {
    return $Call.ByID(199250443, input).then(($result: any) => {
        return $$createType14($result);
    });
}

export function GetEditorCompletions(ctx: $models.EditorCompletionContext): $CancellablePromise<$models.EditorCompletionResult> {
    return $Call.ByID(780159089, ctx).then(($result: any) => {
        return $$createType15($result);
    });
}

export function GetExecutionProfiles(request: $models.ExecutionProfilesRequest): $CancellablePromise<execution$0.ProfileSet> {
    return $Call.ByID(3099827953, request).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * GetGitBlame returns blame info for a file
 */
export function GetGitBlame(filePath: string): $CancellablePromise<string> {
    return $Call.ByID(805725620, filePath);
}

/**
 * GetGitBranch returns the current git branch name
 */
export function GetGitBranch(): $CancellablePromise<string> {
    return $Call.ByID(822115925);
}

/**
 * GetGitBranches returns list of all local branches
 */
export function GetGitBranches(): $CancellablePromise<string[]> {
    return $Call.ByID(3300336729).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetGitCommitDiff returns the diff for a specific commit
 */
export function GetGitCommitDiff(commitHash: string): $CancellablePromise<string> {
    return $Call.ByID(1128195003, commitHash);
}

/**
 * GetGitDiff returns diff for a specific file or all changes
 */
export function GetGitDiff(filePath: string, staged: boolean): $CancellablePromise<string> {
    return $Call.ByID(2688063178, filePath, staged);
}

/**
 * GetGitFileAtCommit returns file content at specific commit
 */
export function GetGitFileAtCommit(filePath: string, commitHash: string): $CancellablePromise<string> {
    return $Call.ByID(824575699, filePath, commitHash);
}

/**
 * GetGitFileDiffBetweenCommits returns diff of a file between two commits
 */
export function GetGitFileDiffBetweenCommits(filePath: string, fromCommit: string, toCommit: string): $CancellablePromise<string> {
    return $Call.ByID(1493863738, filePath, fromCommit, toCommit);
}

/**
 * GetGitLog returns commit history
 */
export function GetGitLog(limit: number, filePath: string): $CancellablePromise<$models.GitCommitInfo[]> {
    return $Call.ByID(662482465, limit, filePath).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * GetGitShow returns details of a specific commit
 */
export function GetGitShow(commitHash: string): $CancellablePromise<string> {
    return $Call.ByID(3575151916, commitHash);
}

/**
 * GetGitStatus returns git status in porcelain format
 */
export function GetGitStatus(): $CancellablePromise<string> {
    return $Call.ByID(4123560639);
}

export function GetInlineSuggestion(filePath: string, content: string, line: number, column: number, prefix: string): $CancellablePromise<string> {
    return $Call.ByID(1264721098, filePath, content, line, column, prefix);
}

export function GetLSPBinaryPath(serverID: string): $CancellablePromise<string> {
    return $Call.ByID(2087797756, serverID);
}

export function GetLSPForFile(filePath: string): $CancellablePromise<$models.LSPServerInfo | null> {
    return $Call.ByID(2936946335, filePath).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * GetLSPInstallStatus returns installation status of LSP servers
 */
export function GetLSPInstallStatus(): $CancellablePromise<welcome$0.ToolStatus[]> {
    return $Call.ByID(1376901355).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * GetLSPStatus returns health status of all LSP servers
 */
export function GetLSPStatus(): $CancellablePromise<lsp$0.ServerStatus[]> {
    return $Call.ByID(2864636116).then(($result: any) => {
        return $$createType21($result);
    });
}

export function GetLanguageForFile(filePath: string): $CancellablePromise<$models.LanguageInfoResult | null> {
    return $Call.ByID(3010003138, filePath).then(($result: any) => {
        return $$createType23($result);
    });
}

export function GetLaravelVersion(path: string): $CancellablePromise<string> {
    return $Call.ByID(3856876508, path);
}

export function GetLastAutocompleteTrace(): $CancellablePromise<brain$0.CompletionTrace> {
    return $Call.ByID(3298020088).then(($result: any) => {
        return $$createType24($result);
    });
}

export function GetMiddlewareList(): $CancellablePromise<any> {
    return $Call.ByID(1164193375);
}

export function GetPackagedOSIntegrationStatus(): $CancellablePromise<$models.PackagedOSIntegrationSnapshot> {
    return $Call.ByID(306335991).then(($result: any) => {
        return $$createType25($result);
    });
}

export function GetPluginCommands(): $CancellablePromise<$models.PluginCommandDefJS[]> {
    return $Call.ByID(657640170).then(($result: any) => {
        return $$createType27($result);
    });
}

export function GetRecentProjects(limit: number): $CancellablePromise<project$0.Project[]> {
    return $Call.ByID(2741556134, limit).then(($result: any) => {
        return $$createType29($result);
    });
}

export function GetRelatedFiles(filePath: string): $CancellablePromise<indexer$0.FileRelation[]> {
    return $Call.ByID(2982593757, filePath).then(($result: any) => {
        return $$createType31($result);
    });
}

export function GetRouteList(filter: string): $CancellablePromise<any> {
    return $Call.ByID(2062010460, filter);
}

export function GetShellCapabilities(): $CancellablePromise<$models.ShellCapabilitiesSnapshot> {
    return $Call.ByID(1383723841).then(($result: any) => {
        return $$createType32($result);
    });
}

export function GetSupportedLanguages(): $CancellablePromise<string[]> {
    return $Call.ByID(3051367130).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetTerminalHistory(limit: number): $CancellablePromise<string[]> {
    return $Call.ByID(645152765, limit).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetTerminalPreview(command: string): $CancellablePromise<$models.TerminalPreviewJS> {
    return $Call.ByID(1649203157, command).then(($result: any) => {
        return $$createType33($result);
    });
}

export function GetWails3PackagedSmokeReport(args: string[]): $CancellablePromise<$models.Wails3PackagedSmokeReport> {
    return $Call.ByID(1809216711, args).then(($result: any) => {
        return $$createType34($result);
    });
}

export function GetWindowLeaseStatus(): $CancellablePromise<$models.WindowLeaseSnapshot> {
    return $Call.ByID(1757612373).then(($result: any) => {
        return $$createType35($result);
    });
}

/**
 * GoToDefinition finds definition for a symbol at given position
 * Uses indexed data for fast lookup, falls back to LSP
 */
export function GoToDefinition(filePath: string, content: string, line: number, column: number, word: string, beforeWord: string, afterWord: string): $CancellablePromise<$models.DefinitionResult[]> {
    return $Call.ByID(1326750791, filePath, content, line, column, word, beforeWord, afterWord).then(($result: any) => {
        return $$createType37($result);
    });
}

export function Greet(name: string): $CancellablePromise<string> {
    return $Call.ByID(2659711170, name);
}

export function ImportShellHistory(projectID: string, historyPath: string, workDir: string): $CancellablePromise<void> {
    return $Call.ByID(1481555862, projectID, historyPath, workDir);
}

export function IndexLaravelAll(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3240260503).then(($result: any) => {
        return $$createType38($result);
    });
}

export function IndexLaravelConfig(): $CancellablePromise<string> {
    return $Call.ByID(496107770);
}

export function IndexLaravelModels(): $CancellablePromise<string> {
    return $Call.ByID(2185329438);
}

export function IndexLaravelRoutes(): $CancellablePromise<string> {
    return $Call.ByID(1063508582);
}

export function IndexLaravelViews(): $CancellablePromise<string> {
    return $Call.ByID(2788361202);
}

export function InitDispatcherForProject(): $CancellablePromise<void> {
    return $Call.ByID(2987115106);
}

export function InspectEditorFile(filePath: string): $CancellablePromise<$models.EditorFileInspection> {
    return $Call.ByID(1991393444, filePath).then(($result: any) => {
        return $$createType39($result);
    });
}

export function InspectProject(): $CancellablePromise<any> {
    return $Call.ByID(2376510860);
}

export function InspectProjectAccess(path: string): $CancellablePromise<$models.ProjectAccessInspection> {
    return $Call.ByID(2417092806, path).then(($result: any) => {
        return $$createType40($result);
    });
}

export function InstallAll(): $CancellablePromise<void> {
    return $Call.ByID(3979437883);
}

export function InstallBreeze(): $CancellablePromise<void> {
    return $Call.ByID(3984307847);
}

/**
 * InstallDevTool installs a development tool or LSP server
 */
export function InstallDevTool(toolName: string): $CancellablePromise<string> {
    return $Call.ByID(3785770121, toolName);
}

export function InstallFortify(): $CancellablePromise<void> {
    return $Call.ByID(3683884497);
}

export function InstallJetstream(): $CancellablePromise<void> {
    return $Call.ByID(4262964215);
}

export function InstallLSPServer(serverID: string): $CancellablePromise<void> {
    return $Call.ByID(3352504172, serverID);
}

export function InstallLivewire(): $CancellablePromise<void> {
    return $Call.ByID(3749430535);
}

export function InstallPackage(name: string, opts: composer$0.InstallOptions): $CancellablePromise<void> {
    return $Call.ByID(611762984, name, opts);
}

export function IsLSPInstalling(serverID: string): $CancellablePromise<boolean> {
    return $Call.ByID(2897633925, serverID);
}

export function IsLangDetectorLoaded(): $CancellablePromise<boolean> {
    return $Call.ByID(1706972270);
}

export function IsLaravelProject(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(3484883515, path);
}

export function IsNativeFullscreen(): $CancellablePromise<boolean> {
    return $Call.ByID(852222967);
}

export function LSPApplyWorkspaceEdit(edit: $models.LSPWorkspaceEdit | null): $CancellablePromise<void> {
    return $Call.ByID(4218232197, edit);
}

export function LSPGetCodeActions(filePath: string, content: string, line: number, character: number): $CancellablePromise<$models.LSPCodeAction[]> {
    return $Call.ByID(2004919368, filePath, content, line, character).then(($result: any) => {
        return $$createType42($result);
    });
}

export function LSPGetDiagnostics(filePath: string): $CancellablePromise<$models.LSPDiagnostic[]> {
    return $Call.ByID(2740795840, filePath).then(($result: any) => {
        return $$createType44($result);
    });
}

/**
 * LSPGoToDefinition finds definition using unified LSP manager
 */
export function LSPGoToDefinition(filePath: string, content: string, line: number, character: number): $CancellablePromise<$models.LSPDefinitionResult[]> {
    return $Call.ByID(1637549358, filePath, content, line, character).then(($result: any) => {
        return $$createType46($result);
    });
}

/**
 * LSPHover returns hover information for a symbol
 */
export function LSPHover(filePath: string, content: string, line: number, character: number): $CancellablePromise<string> {
    return $Call.ByID(2120599106, filePath, content, line, character);
}

export function LSPPreloadProjectDiagnostics(projectPath: string): $CancellablePromise<boolean> {
    return $Call.ByID(2755018294, projectPath);
}

/**
 * LSPSignatureHelp returns signature help for a function call
 */
export function LSPSignatureHelp(filePath: string, content: string, line: number, character: number): $CancellablePromise<$models.SignatureHelpResult | null> {
    return $Call.ByID(4147834173, filePath, content, line, character).then(($result: any) => {
        return $$createType48($result);
    });
}

export function ListApprovedDependencyActions(): $CancellablePromise<string[]> {
    return $Call.ByID(3578679726).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ListInstalledPackages(): $CancellablePromise<string> {
    return $Call.ByID(3315868544);
}

export function ListTerminalSessions(): $CancellablePromise<string[]> {
    return $Call.ByID(2383672116).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Migrate(opts: system$0.MigrateOptions): $CancellablePromise<string> {
    return $Call.ByID(31804598, opts);
}

export function MigrateFresh(opts: system$0.MigrateRefreshOptions): $CancellablePromise<string> {
    return $Call.ByID(2851604802, opts);
}

export function MigrateRefresh(opts: system$0.MigrateRefreshOptions): $CancellablePromise<string> {
    return $Call.ByID(161550973, opts);
}

export function MigrateReset(opts: system$0.MigrateResetOptions): $CancellablePromise<string> {
    return $Call.ByID(3810832729, opts);
}

export function MigrateRollback(opts: system$0.MigrateRollbackOptions): $CancellablePromise<string> {
    return $Call.ByID(2746725622, opts);
}

export function MigrateSeed(opts: system$0.MigrateOptions): $CancellablePromise<string> {
    return $Call.ByID(3045603055, opts);
}

export function MigrateStatus(): $CancellablePromise<string> {
    return $Call.ByID(3450203256);
}

/**
 * NotifyFileChanged notifies LSP servers when a file content changes
 */
export function NotifyFileChanged(filePath: string, language: string, version: number, content: string): $CancellablePromise<void> {
    return $Call.ByID(3640445830, filePath, language, version, content);
}

/**
 * NotifyFileClosed notifies LSP servers when a file is closed
 */
export function NotifyFileClosed(filePath: string, language: string): $CancellablePromise<void> {
    return $Call.ByID(3753785758, filePath, language);
}

/**
 * NotifyFileOpened notifies LSP servers when a file is opened in the editor
 */
export function NotifyFileOpened(filePath: string, language: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(3996156971, filePath, language, content);
}

export function OpenNativeContextMenu(request: $models.NativeContextMenuRequest): $CancellablePromise<$models.NativeContextMenuResponse> {
    return $Call.ByID(2956928310, request).then(($result: any) => {
        return $$createType49($result);
    });
}

export function OpenProject(path: string): $CancellablePromise<void> {
    return $Call.ByID(517162042, path);
}

export function ParseCommand(input: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(2145746925, input).then(($result: any) => {
        return $$createType38($result);
    });
}

export function PinCommand(cmd: string): $CancellablePromise<void> {
    return $Call.ByID(1809965573, cmd);
}

export function PredictCommand(input: string): $CancellablePromise<$models.ClassResult | null> {
    return $Call.ByID(57982963, input).then(($result: any) => {
        return $$createType51($result);
    });
}

export function PredictTerminalCommand(req: $models.TerminalPredictionRequest): $CancellablePromise<$models.TerminalPredictionResponse> {
    return $Call.ByID(3772631451, req).then(($result: any) => {
        return $$createType52($result);
    });
}

export function PublishAssets(packageName: string, tags: string[]): $CancellablePromise<void> {
    return $Call.ByID(4032289609, packageName, tags);
}

export function QueueWork(connection: string, queue: string): $CancellablePromise<void> {
    return $Call.ByID(160704349, connection, queue);
}

export function ReadDirectory(dirPath: string): $CancellablePromise<$models.FileEntry[]> {
    return $Call.ByID(3882613584, dirPath).then(($result: any) => {
        return $$createType54($result);
    });
}

export function ReadEditorFilePreview(filePath: string, maxBytes: number): $CancellablePromise<$models.EditorFilePreview> {
    return $Call.ByID(3674158986, filePath, maxBytes).then(($result: any) => {
        return $$createType55($result);
    });
}

export function ReadEditorVisualFile(filePath: string): $CancellablePromise<$models.EditorVisualFile> {
    return $Call.ByID(963892010, filePath).then(($result: any) => {
        return $$createType56($result);
    });
}

export function ReadFile(filePath: string): $CancellablePromise<string> {
    return $Call.ByID(1160596971, filePath);
}

export function RecordCommandExecution(projectID: string, command: string, workDir: string): $CancellablePromise<void> {
    return $Call.ByID(4263319117, projectID, command, workDir);
}

export function RecordCompletionUsage(label: string): $CancellablePromise<void> {
    return $Call.ByID(2439147269, label);
}

export function RecordFileAccess(filePath: string): $CancellablePromise<void> {
    return $Call.ByID(4232286036, filePath);
}

export function RecordGhostRejected(): $CancellablePromise<void> {
    return $Call.ByID(2901661065);
}

export function RecordGhostShown(): $CancellablePromise<void> {
    return $Call.ByID(3641459704);
}

export function RecordTypingActivity(chars: number): $CancellablePromise<void> {
    return $Call.ByID(438320990, chars);
}

export function RemovePackage(name: string, opts: composer$0.RemoveOptions): $CancellablePromise<void> {
    return $Call.ByID(4138363611, name, opts);
}

export function RenameProjectEntry(path: string, newName: string): $CancellablePromise<$models.ProjectEntryRenameResult> {
    return $Call.ByID(121090124, path, newName).then(($result: any) => {
        return $$createType57($result);
    });
}

export function ResizeTerminal(id: string, rows: number, cols: number): $CancellablePromise<void> {
    return $Call.ByID(1887984285, id, rows, cols);
}

/**
 * RestartLSPServer force-restarts a specific LSP server.
 */
export function RestartLSPServer(language: string): $CancellablePromise<boolean> {
    return $Call.ByID(843672400, language);
}

export function RevealProjectEntry(path: string): $CancellablePromise<void> {
    return $Call.ByID(610992635, path);
}

export function RouteCache(): $CancellablePromise<string> {
    return $Call.ByID(1653131812);
}

export function RunBackgroundShellAction(actionID: string): $CancellablePromise<$models.BackgroundShellActionResult> {
    return $Call.ByID(2677002422, actionID).then(($result: any) => {
        return $$createType58($result);
    });
}

export function RunDependencyPolicySync(req: depsync$0.ExecuteRequest): $CancellablePromise<depsync$0.ExecuteResult> {
    return $Call.ByID(4055326678, req).then(($result: any) => {
        return $$createType59($result);
    });
}

/**
 * RunGitCommand executes a git command in the project directory
 */
export function RunGitCommand(args: string[]): $CancellablePromise<string> {
    return $Call.ByID(1772246131, args);
}

export function RunMigrate(): $CancellablePromise<void> {
    return $Call.ByID(970276291);
}

export function RunPackagedOSIntegrationAction(actionID: string): $CancellablePromise<$models.PackagedOSActionResult> {
    return $Call.ByID(212070764, actionID).then(($result: any) => {
        return $$createType60($result);
    });
}

export function RunWindowLeaseAction(actionID: string): $CancellablePromise<$models.WindowLeaseActionResult> {
    return $Call.ByID(1355862670, actionID).then(($result: any) => {
        return $$createType61($result);
    });
}

export function ScheduleRun(): $CancellablePromise<string> {
    return $Call.ByID(1996637713);
}

export function SearchClasses(prefix: string): $CancellablePromise<$models.ClassResult[]> {
    return $Call.ByID(1440811547, prefix).then(($result: any) => {
        return $$createType62($result);
    });
}

export function SearchContent(query: string): $CancellablePromise<$models.ResultItemJS[]> {
    return $Call.ByID(837782406, query).then(($result: any) => {
        return $$createType14($result);
    });
}

export function SearchFiles(pattern: string): $CancellablePromise<$models.ResultItemJS[]> {
    return $Call.ByID(3203090108, pattern).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * SearchInProject searches for a query string in all project files
 */
export function SearchInProject(query: string, caseSensitive: boolean, useRegex: boolean, wholeWord: boolean): $CancellablePromise<$models.SearchResult[]> {
    return $Call.ByID(1951647779, query, caseSensitive, useRegex, wholeWord).then(($result: any) => {
        return $$createType64($result);
    });
}

export function SearchSymbols(query: string): $CancellablePromise<$models.ResultItemJS[]> {
    return $Call.ByID(342316914, query).then(($result: any) => {
        return $$createType14($result);
    });
}

export function SelectDirectory(title: string): $CancellablePromise<string> {
    return $Call.ByID(1735672136, title);
}

export function SendTerminalText(id: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(1308733900, id, text);
}

export function Serve(opts: system$0.ServeOptions): $CancellablePromise<void> {
    return $Call.ByID(1252611052, opts);
}

export function SetNativeWindowControlsVisible(visible: boolean): $CancellablePromise<boolean> {
    return $Call.ByID(922935632, visible);
}

export function ShowPackageInfo(name: string): $CancellablePromise<string> {
    return $Call.ByID(2020960992, name);
}

export function StorageLink(): $CancellablePromise<string> {
    return $Call.ByID(3354398342);
}

export function SuggestCommand(input: string): $CancellablePromise<$models.CommandSuggestion[]> {
    return $Call.ByID(21596122, input).then(($result: any) => {
        return $$createType66($result);
    });
}

export function SyncApplicationMenuShortcuts(payload: $models.ApplicationMenuShortcutPayload[]): $CancellablePromise<void> {
    return $Call.ByID(3664212066, payload);
}

export function SyncProjectDependencies(mode: string): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(2790870830, mode).then(($result: any) => {
        return $$createType67($result);
    });
}

export function Tinker(): $CancellablePromise<void> {
    return $Call.ByID(79624690);
}

export function ToggleNativeFullscreen(): $CancellablePromise<void> {
    return $Call.ByID(169440215);
}

export function TrashProjectEntry(path: string): $CancellablePromise<void> {
    return $Call.ByID(840343694, path);
}

export function UnpinCommand(cmd: string): $CancellablePromise<void> {
    return $Call.ByID(1072443974, cmd);
}

export function UpdateAll(): $CancellablePromise<void> {
    return $Call.ByID(2857062695);
}

export function UpdatePackage(name: string): $CancellablePromise<void> {
    return $Call.ByID(3631571604, name);
}

/**
 * UpdatePrediction updates the speculative store based on terminal input
 */
export function UpdatePrediction(input: string): $CancellablePromise<void> {
    return $Call.ByID(1334482297, input);
}

export function ValidateEnvironment(): $CancellablePromise<{ [_ in string]?: boolean }> {
    return $Call.ByID(1433890444).then(($result: any) => {
        return $$createType68($result);
    });
}

export function ViewCache(): $CancellablePromise<string> {
    return $Call.ByID(690827050);
}

export function WriteFile(filePath: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(3562730546, filePath, content);
}

export function WriteTerminal(id: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(146795716, id, data);
}

// Private type creation functions
const $$createType0 = $models.LanguagePrediction.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.DispatcherResultJS.createFrom;
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $models.LSPServerInfo.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.BackgroundShellStatusSnapshot.createFrom;
const $$createType7 = indexer$0.DependencyGraph.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = depsync$0.PolicyPlan.createFrom;
const $$createType10 = depsync$0.Plan.createFrom;
const $$createType11 = welcome$0.ToolStatus.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.ResultItemJS.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $models.EditorCompletionResult.createFrom;
const $$createType16 = execution$0.ProfileSet.createFrom;
const $$createType17 = $models.GitCommitInfo.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = $Create.Nullable($$createType4);
const $$createType20 = lsp$0.ServerStatus.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = $models.LanguageInfoResult.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = brain$0.CompletionTrace.createFrom;
const $$createType25 = $models.PackagedOSIntegrationSnapshot.createFrom;
const $$createType26 = $models.PluginCommandDefJS.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = project$0.Project.createFrom;
const $$createType29 = $Create.Array($$createType28);
const $$createType30 = indexer$0.FileRelation.createFrom;
const $$createType31 = $Create.Array($$createType30);
const $$createType32 = $models.ShellCapabilitiesSnapshot.createFrom;
const $$createType33 = $models.TerminalPreviewJS.createFrom;
const $$createType34 = $models.Wails3PackagedSmokeReport.createFrom;
const $$createType35 = $models.WindowLeaseSnapshot.createFrom;
const $$createType36 = $models.DefinitionResult.createFrom;
const $$createType37 = $Create.Array($$createType36);
const $$createType38 = $Create.Map($Create.Any, $Create.Any);
const $$createType39 = $models.EditorFileInspection.createFrom;
const $$createType40 = $models.ProjectAccessInspection.createFrom;
const $$createType41 = $models.LSPCodeAction.createFrom;
const $$createType42 = $Create.Array($$createType41);
const $$createType43 = $models.LSPDiagnostic.createFrom;
const $$createType44 = $Create.Array($$createType43);
const $$createType45 = $models.LSPDefinitionResult.createFrom;
const $$createType46 = $Create.Array($$createType45);
const $$createType47 = $models.SignatureHelpResult.createFrom;
const $$createType48 = $Create.Nullable($$createType47);
const $$createType49 = $models.NativeContextMenuResponse.createFrom;
const $$createType50 = $models.ClassResult.createFrom;
const $$createType51 = $Create.Nullable($$createType50);
const $$createType52 = $models.TerminalPredictionResponse.createFrom;
const $$createType53 = $models.FileEntry.createFrom;
const $$createType54 = $Create.Array($$createType53);
const $$createType55 = $models.EditorFilePreview.createFrom;
const $$createType56 = $models.EditorVisualFile.createFrom;
const $$createType57 = $models.ProjectEntryRenameResult.createFrom;
const $$createType58 = $models.BackgroundShellActionResult.createFrom;
const $$createType59 = depsync$0.ExecuteResult.createFrom;
const $$createType60 = $models.PackagedOSActionResult.createFrom;
const $$createType61 = $models.WindowLeaseActionResult.createFrom;
const $$createType62 = $Create.Array($$createType50);
const $$createType63 = $models.SearchResult.createFrom;
const $$createType64 = $Create.Array($$createType63);
const $$createType65 = $models.CommandSuggestion.createFrom;
const $$createType66 = $Create.Array($$createType65);
const $$createType67 = $Create.Map($Create.Any, $Create.Any);
const $$createType68 = $Create.Map($Create.Any, $Create.Any);
