// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as App from "./app.js";
export {
    App
};

export {
    ApplicationMenuShortcutPayload,
    ClassResult,
    CommandSuggestion,
    DefinitionResult,
    DispatcherResultJS,
    EditorCompletion,
    EditorCompletionContext,
    EditorCompletionResult,
    ExecutionProfilesRequest,
    FileEntry,
    FlagDefJS,
    GitCommitInfo,
    LSPCodeAction,
    LSPDefinitionResult,
    LSPDiagnostic,
    LSPPosition,
    LSPRange,
    LSPServerInfo,
    LSPTextEdit,
    LSPWorkspaceEdit,
    LanguageInfoResult,
    LanguagePrediction,
    ParameterInfo,
    PluginCommandDefJS,
    ProjectEntryRenameResult,
    ResultItemJS,
    SearchResult,
    ShellCapabilitiesSnapshot,
    ShellCapabilityDescriptor,
    ShellCapabilityStatus,
    SignatureHelpResult,
    SignatureInfo,
    TerminalPredictionRequest,
    TerminalPredictionResponse,
    TerminalPreviewJS,
    TextEditJSON
} from "./models.js";
