// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as terminal$0 from "./internal/terminal/models.js";

export class ApplicationMenuShortcutPayload {
    "actionId": string;
    "label": string;
    "group": string;
    "shortcuts": string[];

    /** Creates a new ApplicationMenuShortcutPayload instance. */
    constructor($$source: Partial<ApplicationMenuShortcutPayload> = {}) {
        if (!("actionId" in $$source)) {
            this["actionId"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("group" in $$source)) {
            this["group"] = "";
        }
        if (!("shortcuts" in $$source)) {
            this["shortcuts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApplicationMenuShortcutPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): ApplicationMenuShortcutPayload {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("shortcuts" in $$parsedSource) {
            $$parsedSource["shortcuts"] = $$createField3_0($$parsedSource["shortcuts"]);
        }
        return new ApplicationMenuShortcutPayload($$parsedSource as Partial<ApplicationMenuShortcutPayload>);
    }
}

/**
 * ClassResult represents a class search result
 */
export class ClassResult {
    "name": string;
    "kind": string;
    "namespace": string;
    "filePath": string;
    "line": number;
    "pending": boolean;
    "extra"?: { [_ in string]?: string };

    /** Creates a new ClassResult instance. */
    constructor($$source: Partial<ClassResult> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("line" in $$source)) {
            this["line"] = 0;
        }
        if (!("pending" in $$source)) {
            this["pending"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClassResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ClassResult {
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extra" in $$parsedSource) {
            $$parsedSource["extra"] = $$createField6_0($$parsedSource["extra"]);
        }
        return new ClassResult($$parsedSource as Partial<ClassResult>);
    }
}

/**
 * CommandSuggestion represents a terminal command suggestion
 */
export class CommandSuggestion {
    "text": string;
    "description": string;
    "kind": string;

    /** Creates a new CommandSuggestion instance. */
    constructor($$source: Partial<CommandSuggestion> = {}) {
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandSuggestion instance from a string or object.
     */
    static createFrom($$source: any = {}): CommandSuggestion {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommandSuggestion($$parsedSource as Partial<CommandSuggestion>);
    }
}

/**
 * DefinitionResult represents a single Go to Definition result
 */
export class DefinitionResult {
    "path": string;
    "line": number;
    "context": string;
    "displayPath": string;

    /** Creates a new DefinitionResult instance. */
    constructor($$source: Partial<DefinitionResult> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("line" in $$source)) {
            this["line"] = 0;
        }
        if (!("context" in $$source)) {
            this["context"] = "";
        }
        if (!("displayPath" in $$source)) {
            this["displayPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DefinitionResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DefinitionResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DefinitionResult($$parsedSource as Partial<DefinitionResult>);
    }
}

export class DispatcherResultJS {
    "success": boolean;
    "output": string;
    "error": string;
    "resultType": number;
    "items": ResultItemJS[];
    "preview": string;
    "shouldClose": boolean;

    /** Creates a new DispatcherResultJS instance. */
    constructor($$source: Partial<DispatcherResultJS> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("output" in $$source)) {
            this["output"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("resultType" in $$source)) {
            this["resultType"] = 0;
        }
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("preview" in $$source)) {
            this["preview"] = "";
        }
        if (!("shouldClose" in $$source)) {
            this["shouldClose"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DispatcherResultJS instance from a string or object.
     */
    static createFrom($$source: any = {}): DispatcherResultJS {
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField4_0($$parsedSource["items"]);
        }
        return new DispatcherResultJS($$parsedSource as Partial<DispatcherResultJS>);
    }
}

export class EditorCompletion {
    "label": string;
    "text": string;
    "detail": string;
    "documentation"?: string;
    "typeInfo"?: string;
    "kind": string;
    "source": string;
    "insertText": string;
    "isSnippet": boolean;
    "priority": number;
    "highlightPositions"?: number[];
    "matchType"?: string;
    "additionalTextEdits"?: TextEditJSON[];

    /** Creates a new EditorCompletion instance. */
    constructor($$source: Partial<EditorCompletion> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("insertText" in $$source)) {
            this["insertText"] = "";
        }
        if (!("isSnippet" in $$source)) {
            this["isSnippet"] = false;
        }
        if (!("priority" in $$source)) {
            this["priority"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EditorCompletion instance from a string or object.
     */
    static createFrom($$source: any = {}): EditorCompletion {
        const $$createField10_0 = $$createType4;
        const $$createField12_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("highlightPositions" in $$parsedSource) {
            $$parsedSource["highlightPositions"] = $$createField10_0($$parsedSource["highlightPositions"]);
        }
        if ("additionalTextEdits" in $$parsedSource) {
            $$parsedSource["additionalTextEdits"] = $$createField12_0($$parsedSource["additionalTextEdits"]);
        }
        return new EditorCompletion($$parsedSource as Partial<EditorCompletion>);
    }
}

/**
 * EditorCompletionContext represents completion request context
 */
export class EditorCompletionContext {
    "filePath": string;
    "language": string;
    "line": number;
    "column": number;
    "lineText": string;
    "textBefore": string;
    "textAfter": string;
    "fullText": string;
    "currentClass": string;
    "currentMethod": string;
    "imports": string[];
    "triggerChar": string;
    "requestId"?: string;

    /** Creates a new EditorCompletionContext instance. */
    constructor($$source: Partial<EditorCompletionContext> = {}) {
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("line" in $$source)) {
            this["line"] = 0;
        }
        if (!("column" in $$source)) {
            this["column"] = 0;
        }
        if (!("lineText" in $$source)) {
            this["lineText"] = "";
        }
        if (!("textBefore" in $$source)) {
            this["textBefore"] = "";
        }
        if (!("textAfter" in $$source)) {
            this["textAfter"] = "";
        }
        if (!("fullText" in $$source)) {
            this["fullText"] = "";
        }
        if (!("currentClass" in $$source)) {
            this["currentClass"] = "";
        }
        if (!("currentMethod" in $$source)) {
            this["currentMethod"] = "";
        }
        if (!("imports" in $$source)) {
            this["imports"] = [];
        }
        if (!("triggerChar" in $$source)) {
            this["triggerChar"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EditorCompletionContext instance from a string or object.
     */
    static createFrom($$source: any = {}): EditorCompletionContext {
        const $$createField10_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("imports" in $$parsedSource) {
            $$parsedSource["imports"] = $$createField10_0($$parsedSource["imports"]);
        }
        return new EditorCompletionContext($$parsedSource as Partial<EditorCompletionContext>);
    }
}

/**
 * EditorCompletionResult represents completion response
 */
export class EditorCompletionResult {
    "primary": EditorCompletion | null;
    "items": EditorCompletion[];
    "ghostText"?: string;
    "ghostConfidence"?: number;
    "showGhost": boolean;
    "requestId"?: string;
    "stale"?: boolean;

    /** Creates a new EditorCompletionResult instance. */
    constructor($$source: Partial<EditorCompletionResult> = {}) {
        if (!("primary" in $$source)) {
            this["primary"] = null;
        }
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("showGhost" in $$source)) {
            this["showGhost"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EditorCompletionResult instance from a string or object.
     */
    static createFrom($$source: any = {}): EditorCompletionResult {
        const $$createField0_0 = $$createType8;
        const $$createField1_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("primary" in $$parsedSource) {
            $$parsedSource["primary"] = $$createField0_0($$parsedSource["primary"]);
        }
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField1_0($$parsedSource["items"]);
        }
        return new EditorCompletionResult($$parsedSource as Partial<EditorCompletionResult>);
    }
}

export class ExecutionProfilesRequest {
    "projectPath": string;
    "activeFilePath": string;
    "activeFileName": string;
    "activeFileContent": string;
    "activeFileLanguage": string;

    /** Creates a new ExecutionProfilesRequest instance. */
    constructor($$source: Partial<ExecutionProfilesRequest> = {}) {
        if (!("projectPath" in $$source)) {
            this["projectPath"] = "";
        }
        if (!("activeFilePath" in $$source)) {
            this["activeFilePath"] = "";
        }
        if (!("activeFileName" in $$source)) {
            this["activeFileName"] = "";
        }
        if (!("activeFileContent" in $$source)) {
            this["activeFileContent"] = "";
        }
        if (!("activeFileLanguage" in $$source)) {
            this["activeFileLanguage"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExecutionProfilesRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ExecutionProfilesRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExecutionProfilesRequest($$parsedSource as Partial<ExecutionProfilesRequest>);
    }
}

export class FileEntry {
    "name": string;
    "path": string;
    "isDirectory": boolean;

    /** Creates a new FileEntry instance. */
    constructor($$source: Partial<FileEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("isDirectory" in $$source)) {
            this["isDirectory"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): FileEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileEntry($$parsedSource as Partial<FileEntry>);
    }
}

export class FlagDefJS {
    "name": string;
    "short": string;
    "description": string;
    "hasValue": boolean;

    /** Creates a new FlagDefJS instance. */
    constructor($$source: Partial<FlagDefJS> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("short" in $$source)) {
            this["short"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("hasValue" in $$source)) {
            this["hasValue"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FlagDefJS instance from a string or object.
     */
    static createFrom($$source: any = {}): FlagDefJS {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FlagDefJS($$parsedSource as Partial<FlagDefJS>);
    }
}

/**
 * GitCommitInfo represents a single commit
 */
export class GitCommitInfo {
    "hash": string;
    "shortHash": string;
    "author": string;
    "authorEmail": string;
    "date": string;
    "subject": string;
    "body": string;
    "parents": string;

    /** Creates a new GitCommitInfo instance. */
    constructor($$source: Partial<GitCommitInfo> = {}) {
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }
        if (!("shortHash" in $$source)) {
            this["shortHash"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("authorEmail" in $$source)) {
            this["authorEmail"] = "";
        }
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("subject" in $$source)) {
            this["subject"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("parents" in $$source)) {
            this["parents"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitCommitInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): GitCommitInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitCommitInfo($$parsedSource as Partial<GitCommitInfo>);
    }
}

export class LSPCodeAction {
    "title": string;
    "kind"?: string;
    "isPreferred"?: boolean;
    "edit"?: LSPWorkspaceEdit | null;
    "hasCommand": boolean;

    /** Creates a new LSPCodeAction instance. */
    constructor($$source: Partial<LSPCodeAction> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("hasCommand" in $$source)) {
            this["hasCommand"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LSPCodeAction instance from a string or object.
     */
    static createFrom($$source: any = {}): LSPCodeAction {
        const $$createField3_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("edit" in $$parsedSource) {
            $$parsedSource["edit"] = $$createField3_0($$parsedSource["edit"]);
        }
        return new LSPCodeAction($$parsedSource as Partial<LSPCodeAction>);
    }
}

/**
 * LSPDefinitionResult represents a definition location from LSP
 */
export class LSPDefinitionResult {
    "path": string;
    "line": number;
    "char": number;

    /** Creates a new LSPDefinitionResult instance. */
    constructor($$source: Partial<LSPDefinitionResult> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("line" in $$source)) {
            this["line"] = 0;
        }
        if (!("char" in $$source)) {
            this["char"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LSPDefinitionResult instance from a string or object.
     */
    static createFrom($$source: any = {}): LSPDefinitionResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LSPDefinitionResult($$parsedSource as Partial<LSPDefinitionResult>);
    }
}

export class LSPDiagnostic {
    "range": LSPRange;
    "severity": number;
    "code"?: string;
    "source"?: string;
    "message": string;

    /** Creates a new LSPDiagnostic instance. */
    constructor($$source: Partial<LSPDiagnostic> = {}) {
        if (!("range" in $$source)) {
            this["range"] = (new LSPRange());
        }
        if (!("severity" in $$source)) {
            this["severity"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LSPDiagnostic instance from a string or object.
     */
    static createFrom($$source: any = {}): LSPDiagnostic {
        const $$createField0_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("range" in $$parsedSource) {
            $$parsedSource["range"] = $$createField0_0($$parsedSource["range"]);
        }
        return new LSPDiagnostic($$parsedSource as Partial<LSPDiagnostic>);
    }
}

export class LSPPosition {
    "line": number;
    "character": number;

    /** Creates a new LSPPosition instance. */
    constructor($$source: Partial<LSPPosition> = {}) {
        if (!("line" in $$source)) {
            this["line"] = 0;
        }
        if (!("character" in $$source)) {
            this["character"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LSPPosition instance from a string or object.
     */
    static createFrom($$source: any = {}): LSPPosition {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LSPPosition($$parsedSource as Partial<LSPPosition>);
    }
}

export class LSPRange {
    "start": LSPPosition;
    "end": LSPPosition;

    /** Creates a new LSPRange instance. */
    constructor($$source: Partial<LSPRange> = {}) {
        if (!("start" in $$source)) {
            this["start"] = (new LSPPosition());
        }
        if (!("end" in $$source)) {
            this["end"] = (new LSPPosition());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LSPRange instance from a string or object.
     */
    static createFrom($$source: any = {}): LSPRange {
        const $$createField0_0 = $$createType13;
        const $$createField1_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("start" in $$parsedSource) {
            $$parsedSource["start"] = $$createField0_0($$parsedSource["start"]);
        }
        if ("end" in $$parsedSource) {
            $$parsedSource["end"] = $$createField1_0($$parsedSource["end"]);
        }
        return new LSPRange($$parsedSource as Partial<LSPRange>);
    }
}

export class LSPServerInfo {
    "id": string;
    "name": string;
    "languages": string[];
    "extensions": string[];
    "installed": boolean;
    "version": string;
    "canInstall": boolean;
    "installCmd": string;

    /** Creates a new LSPServerInfo instance. */
    constructor($$source: Partial<LSPServerInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("languages" in $$source)) {
            this["languages"] = [];
        }
        if (!("extensions" in $$source)) {
            this["extensions"] = [];
        }
        if (!("installed" in $$source)) {
            this["installed"] = false;
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("canInstall" in $$source)) {
            this["canInstall"] = false;
        }
        if (!("installCmd" in $$source)) {
            this["installCmd"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LSPServerInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): LSPServerInfo {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("languages" in $$parsedSource) {
            $$parsedSource["languages"] = $$createField2_0($$parsedSource["languages"]);
        }
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField3_0($$parsedSource["extensions"]);
        }
        return new LSPServerInfo($$parsedSource as Partial<LSPServerInfo>);
    }
}

export class LSPTextEdit {
    "range": LSPRange;
    "newText": string;

    /** Creates a new LSPTextEdit instance. */
    constructor($$source: Partial<LSPTextEdit> = {}) {
        if (!("range" in $$source)) {
            this["range"] = (new LSPRange());
        }
        if (!("newText" in $$source)) {
            this["newText"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LSPTextEdit instance from a string or object.
     */
    static createFrom($$source: any = {}): LSPTextEdit {
        const $$createField0_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("range" in $$parsedSource) {
            $$parsedSource["range"] = $$createField0_0($$parsedSource["range"]);
        }
        return new LSPTextEdit($$parsedSource as Partial<LSPTextEdit>);
    }
}

export class LSPWorkspaceEdit {
    "changes": { [_ in string]?: LSPTextEdit[] };

    /** Creates a new LSPWorkspaceEdit instance. */
    constructor($$source: Partial<LSPWorkspaceEdit> = {}) {
        if (!("changes" in $$source)) {
            this["changes"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LSPWorkspaceEdit instance from a string or object.
     */
    static createFrom($$source: any = {}): LSPWorkspaceEdit {
        const $$createField0_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("changes" in $$parsedSource) {
            $$parsedSource["changes"] = $$createField0_0($$parsedSource["changes"]);
        }
        return new LSPWorkspaceEdit($$parsedSource as Partial<LSPWorkspaceEdit>);
    }
}

export class LanguageInfoResult {
    "id": string;
    "name": string;
    "lspServerId": string;
    "lspInstalled": boolean;
    "canInstallLsp": boolean;
    "arleSupported": boolean;

    /** Creates a new LanguageInfoResult instance. */
    constructor($$source: Partial<LanguageInfoResult> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("lspServerId" in $$source)) {
            this["lspServerId"] = "";
        }
        if (!("lspInstalled" in $$source)) {
            this["lspInstalled"] = false;
        }
        if (!("canInstallLsp" in $$source)) {
            this["canInstallLsp"] = false;
        }
        if (!("arleSupported" in $$source)) {
            this["arleSupported"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LanguageInfoResult instance from a string or object.
     */
    static createFrom($$source: any = {}): LanguageInfoResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LanguageInfoResult($$parsedSource as Partial<LanguageInfoResult>);
    }
}

export class LanguagePrediction {
    "language": string;
    "confidence": number;

    /** Creates a new LanguagePrediction instance. */
    constructor($$source: Partial<LanguagePrediction> = {}) {
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("confidence" in $$source)) {
            this["confidence"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LanguagePrediction instance from a string or object.
     */
    static createFrom($$source: any = {}): LanguagePrediction {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LanguagePrediction($$parsedSource as Partial<LanguagePrediction>);
    }
}

/**
 * ParameterInfo represents a parameter info
 */
export class ParameterInfo {
    "label": string;
    "documentation": string;

    /** Creates a new ParameterInfo instance. */
    constructor($$source: Partial<ParameterInfo> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("documentation" in $$source)) {
            this["documentation"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ParameterInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ParameterInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ParameterInfo($$parsedSource as Partial<ParameterInfo>);
    }
}

export class PluginCommandDefJS {
    "plugin": string;
    "prefix": string;
    "name": string;
    "description": string;
    "outputKind": string;
    "pathPattern": string;
    "namespace": string;
    "flags": FlagDefJS[];

    /** Creates a new PluginCommandDefJS instance. */
    constructor($$source: Partial<PluginCommandDefJS> = {}) {
        if (!("plugin" in $$source)) {
            this["plugin"] = "";
        }
        if (!("prefix" in $$source)) {
            this["prefix"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("outputKind" in $$source)) {
            this["outputKind"] = "";
        }
        if (!("pathPattern" in $$source)) {
            this["pathPattern"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("flags" in $$source)) {
            this["flags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginCommandDefJS instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginCommandDefJS {
        const $$createField7_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("flags" in $$parsedSource) {
            $$parsedSource["flags"] = $$createField7_0($$parsedSource["flags"]);
        }
        return new PluginCommandDefJS($$parsedSource as Partial<PluginCommandDefJS>);
    }
}

export class ProjectEntryRenameResult {
    "newPath": string;
    "isDirectory": boolean;

    /** Creates a new ProjectEntryRenameResult instance. */
    constructor($$source: Partial<ProjectEntryRenameResult> = {}) {
        if (!("newPath" in $$source)) {
            this["newPath"] = "";
        }
        if (!("isDirectory" in $$source)) {
            this["isDirectory"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectEntryRenameResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectEntryRenameResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectEntryRenameResult($$parsedSource as Partial<ProjectEntryRenameResult>);
    }
}

export class ResultItemJS {
    "id": string;
    "icon": string;
    "title": string;
    "subtitle": string;
    "action": string;
    "actionLabel": string;
    "filePath": string;
    "line": number;
    "score": number;

    /** Creates a new ResultItemJS instance. */
    constructor($$source: Partial<ResultItemJS> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("subtitle" in $$source)) {
            this["subtitle"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("actionLabel" in $$source)) {
            this["actionLabel"] = "";
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("line" in $$source)) {
            this["line"] = 0;
        }
        if (!("score" in $$source)) {
            this["score"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResultItemJS instance from a string or object.
     */
    static createFrom($$source: any = {}): ResultItemJS {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResultItemJS($$parsedSource as Partial<ResultItemJS>);
    }
}

/**
 * SearchResult represents a single search match
 */
export class SearchResult {
    "file": string;
    "line": number;
    "column": number;
    "preview": string;
    "matchStart": number;
    "matchEnd": number;
    "priority": number;

    /** Creates a new SearchResult instance. */
    constructor($$source: Partial<SearchResult> = {}) {
        if (!("file" in $$source)) {
            this["file"] = "";
        }
        if (!("line" in $$source)) {
            this["line"] = 0;
        }
        if (!("column" in $$source)) {
            this["column"] = 0;
        }
        if (!("preview" in $$source)) {
            this["preview"] = "";
        }
        if (!("matchStart" in $$source)) {
            this["matchStart"] = 0;
        }
        if (!("matchEnd" in $$source)) {
            this["matchEnd"] = 0;
        }
        if (!("priority" in $$source)) {
            this["priority"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchResult($$parsedSource as Partial<SearchResult>);
    }
}

/**
 * SignatureHelpResult represents a signature help result for frontend
 */
export class SignatureHelpResult {
    "signatures": SignatureInfo[];
    "activeSignature": number;
    "activeParameter": number;

    /** Creates a new SignatureHelpResult instance. */
    constructor($$source: Partial<SignatureHelpResult> = {}) {
        if (!("signatures" in $$source)) {
            this["signatures"] = [];
        }
        if (!("activeSignature" in $$source)) {
            this["activeSignature"] = 0;
        }
        if (!("activeParameter" in $$source)) {
            this["activeParameter"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SignatureHelpResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SignatureHelpResult {
        const $$createField0_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("signatures" in $$parsedSource) {
            $$parsedSource["signatures"] = $$createField0_0($$parsedSource["signatures"]);
        }
        return new SignatureHelpResult($$parsedSource as Partial<SignatureHelpResult>);
    }
}

/**
 * SignatureInfo represents a function signature
 */
export class SignatureInfo {
    "label": string;
    "documentation": string;
    "parameters": ParameterInfo[];

    /** Creates a new SignatureInfo instance. */
    constructor($$source: Partial<SignatureInfo> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("documentation" in $$source)) {
            this["documentation"] = "";
        }
        if (!("parameters" in $$source)) {
            this["parameters"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SignatureInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SignatureInfo {
        const $$createField2_0 = $$createType22;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("parameters" in $$parsedSource) {
            $$parsedSource["parameters"] = $$createField2_0($$parsedSource["parameters"]);
        }
        return new SignatureInfo($$parsedSource as Partial<SignatureInfo>);
    }
}

export class TerminalPredictionRequest {
    "input": string;
    "workDir": string;
    "projectID": string;

    /** Creates a new TerminalPredictionRequest instance. */
    constructor($$source: Partial<TerminalPredictionRequest> = {}) {
        if (!("input" in $$source)) {
            this["input"] = "";
        }
        if (!("workDir" in $$source)) {
            this["workDir"] = "";
        }
        if (!("projectID" in $$source)) {
            this["projectID"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalPredictionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): TerminalPredictionRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalPredictionRequest($$parsedSource as Partial<TerminalPredictionRequest>);
    }
}

export class TerminalPredictionResponse {
    "predictions": terminal$0.PredictionResult[];

    /** Creates a new TerminalPredictionResponse instance. */
    constructor($$source: Partial<TerminalPredictionResponse> = {}) {
        if (!("predictions" in $$source)) {
            this["predictions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalPredictionResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): TerminalPredictionResponse {
        const $$createField0_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("predictions" in $$parsedSource) {
            $$parsedSource["predictions"] = $$createField0_0($$parsedSource["predictions"]);
        }
        return new TerminalPredictionResponse($$parsedSource as Partial<TerminalPredictionResponse>);
    }
}

export class TerminalPreviewJS {
    "output": string;
    "error": string;
    "isSafe": boolean;
    "exitCode": number;
    "truncated": boolean;

    /** Creates a new TerminalPreviewJS instance. */
    constructor($$source: Partial<TerminalPreviewJS> = {}) {
        if (!("output" in $$source)) {
            this["output"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("isSafe" in $$source)) {
            this["isSafe"] = false;
        }
        if (!("exitCode" in $$source)) {
            this["exitCode"] = 0;
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalPreviewJS instance from a string or object.
     */
    static createFrom($$source: any = {}): TerminalPreviewJS {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalPreviewJS($$parsedSource as Partial<TerminalPreviewJS>);
    }
}

export class TextEditJSON {
    "startLine": number;
    "startColumn": number;
    "endLine": number;
    "endColumn": number;
    "text": string;

    /** Creates a new TextEditJSON instance. */
    constructor($$source: Partial<TextEditJSON> = {}) {
        if (!("startLine" in $$source)) {
            this["startLine"] = 0;
        }
        if (!("startColumn" in $$source)) {
            this["startColumn"] = 0;
        }
        if (!("endLine" in $$source)) {
            this["endLine"] = 0;
        }
        if (!("endColumn" in $$source)) {
            this["endColumn"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TextEditJSON instance from a string or object.
     */
    static createFrom($$source: any = {}): TextEditJSON {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TextEditJSON($$parsedSource as Partial<TextEditJSON>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = ResultItemJS.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = TextEditJSON.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = EditorCompletion.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $Create.Array($$createType7);
const $$createType10 = LSPWorkspaceEdit.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = LSPRange.createFrom;
const $$createType13 = LSPPosition.createFrom;
const $$createType14 = LSPTextEdit.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = $Create.Map($Create.Any, $$createType15);
const $$createType17 = FlagDefJS.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = SignatureInfo.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = ParameterInfo.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = terminal$0.PredictionResult.createFrom;
const $$createType24 = $Create.Array($$createType23);
