// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ai$0 from "../ai/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as providers$0 from "../ai/providers/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as autocomplete$0 from "../autocomplete/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as composer$0 from "../composer/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as depsync$0 from "../depsync/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dispatcher$0 from "../dispatcher/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as execution$0 from "../execution/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as indexer$0 from "../indexer/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as brain$0 from "../indexer/brain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as lsp$0 from "../indexer/lsp/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mcp$0 from "../mcp/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as plugins$0 from "../plugins/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as project$0 from "../project/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as system$0 from "../system/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as welcome$0 from "../ui/welcome/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AIAcceptPlan(req: ai$0.AIAcceptPlanRequest): $CancellablePromise<ai$0.AIWorkflowRunResult> {
    return $Call.ByID(2889851111, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function AIApplyPatchArtifact(req: ai$0.AIPatchApplyRequest): $CancellablePromise<ai$0.AIPatchApplyResult> {
    return $Call.ByID(1259517548, req).then(($result: any) => {
        return $$createType1($result);
    });
}

export function AIApproveMnemonicEntryProposal(req: ai$0.AIMnemonicApproveProposalRequest): $CancellablePromise<ai$0.AIMnemonicEntry> {
    return $Call.ByID(3460816649, req).then(($result: any) => {
        return $$createType2($result);
    });
}

export function AICancelChatRun(runID: string): $CancellablePromise<ai$0.AIChatRun> {
    return $Call.ByID(1854363573, runID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function AICancelProviderAuth(sessionID: string): $CancellablePromise<ai$0.AIProviderAuthSession> {
    return $Call.ByID(4158315653, sessionID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function AIClearChatRuns(): $CancellablePromise<void> {
    return $Call.ByID(2039088801);
}

export function AIClearMnemonic(): $CancellablePromise<void> {
    return $Call.ByID(3157662221);
}

export function AIClearProviderSecret(providerID: string): $CancellablePromise<ai$0.AIProviderDescriptor> {
    return $Call.ByID(2030348068, providerID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function AIClearState(): $CancellablePromise<void> {
    return $Call.ByID(975839874);
}

export function AICompactChatSession(req: ai$0.AIContextCompactionRequest): $CancellablePromise<ai$0.AIContextCompactionResult> {
    return $Call.ByID(3573578537, req).then(($result: any) => {
        return $$createType6($result);
    });
}

export function AIDeleteChatSession(chatSessionID: string): $CancellablePromise<void> {
    return $Call.ByID(1013189835, chatSessionID);
}

export function AIDeleteMnemonicEntry(id: string): $CancellablePromise<void> {
    return $Call.ByID(3906936029, id);
}

export function AIExecuteToolCall(req: ai$0.AIToolCallRequest): $CancellablePromise<ai$0.AIToolCallResult> {
    return $Call.ByID(814731225, req).then(($result: any) => {
        return $$createType7($result);
    });
}

export function AIGetApprovalPolicy(): $CancellablePromise<ai$0.AIApprovalPolicy> {
    return $Call.ByID(3650690973).then(($result: any) => {
        return $$createType8($result);
    });
}

export function AIGetChatRun(runID: string): $CancellablePromise<ai$0.AIChatRun> {
    return $Call.ByID(603794087, runID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function AIGetChatRunArtifact(artifactID: string): $CancellablePromise<ai$0.AIChatRunArtifact> {
    return $Call.ByID(1983686025, artifactID).then(($result: any) => {
        return $$createType9($result);
    });
}

export function AIGetChatRunEnvelope(runID: string): $CancellablePromise<ai$0.AIChatRunEnvelope> {
    return $Call.ByID(1086241275, runID).then(($result: any) => {
        return $$createType10($result);
    });
}

export function AIGetConsentPolicy(): $CancellablePromise<ai$0.AIConsentPolicy> {
    return $Call.ByID(1800928692).then(($result: any) => {
        return $$createType11($result);
    });
}

export function AIGetContextContinuationPlan(chatSessionID: string): $CancellablePromise<ai$0.AIContextContinuationPlan> {
    return $Call.ByID(2652800875, chatSessionID).then(($result: any) => {
        return $$createType12($result);
    });
}

export function AIGetContextPreview(req: ai$0.AIContextRequest): $CancellablePromise<ai$0.AIContextSnapshot> {
    return $Call.ByID(2027484301, req).then(($result: any) => {
        return $$createType13($result);
    });
}

export function AIGetEditorContinuation(req: ai$0.AIContextRequest, providerID: string, model: string): $CancellablePromise<ai$0.AIContinuationResponse> {
    return $Call.ByID(2763431662, req, providerID, model).then(($result: any) => {
        return $$createType14($result);
    });
}

export function AIGetEmbeddingStatus(): $CancellablePromise<ai$0.AIEmbeddingStatus> {
    return $Call.ByID(1701132287).then(($result: any) => {
        return $$createType15($result);
    });
}

export function AIGetPredictionStatus(): $CancellablePromise<ai$0.AIPredictionStatus> {
    return $Call.ByID(502851175).then(($result: any) => {
        return $$createType16($result);
    });
}

export function AIGetProviderAuthSession(sessionID: string): $CancellablePromise<ai$0.AIProviderAuthSession> {
    return $Call.ByID(244439353, sessionID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function AIGetStatus(): $CancellablePromise<ai$0.AIStatus> {
    return $Call.ByID(2779991082).then(($result: any) => {
        return $$createType17($result);
    });
}

export function AIGetTerminalContinuation(req: ai$0.AIContextRequest, providerID: string, model: string): $CancellablePromise<ai$0.AIContinuationResponse> {
    return $Call.ByID(1030608623, req, providerID, model).then(($result: any) => {
        return $$createType14($result);
    });
}

export function AIInspectMnemonic(runID: string): $CancellablePromise<ai$0.AIMnemonicInspection> {
    return $Call.ByID(3529150760, runID).then(($result: any) => {
        return $$createType18($result);
    });
}

export function AIListAgentProfiles(): $CancellablePromise<ai$0.AIAgentProfileDescriptor[]> {
    return $Call.ByID(1854270319).then(($result: any) => {
        return $$createType20($result);
    });
}

export function AIListChatActions(): $CancellablePromise<ai$0.AIChatActionDescriptor[]> {
    return $Call.ByID(3237612505).then(($result: any) => {
        return $$createType22($result);
    });
}

export function AIListChatRunArtifacts(runID: string): $CancellablePromise<ai$0.AIChatRunArtifact[]> {
    return $Call.ByID(3081304714, runID).then(($result: any) => {
        return $$createType23($result);
    });
}

export function AIListChatRuns(limit: number): $CancellablePromise<ai$0.AIChatRunEnvelope[]> {
    return $Call.ByID(1998840304, limit).then(($result: any) => {
        return $$createType24($result);
    });
}

export function AIListContextCapsules(chatSessionID: string, limit: number): $CancellablePromise<ai$0.AIContextCapsuleSummary[]> {
    return $Call.ByID(214452907, chatSessionID, limit).then(($result: any) => {
        return $$createType26($result);
    });
}

export function AIListContextProviders(): $CancellablePromise<ai$0.AIContextProviderDescriptor[]> {
    return $Call.ByID(1718679039).then(($result: any) => {
        return $$createType28($result);
    });
}

export function AIListEgressRecords(limit: number): $CancellablePromise<ai$0.AIEgressRecord[]> {
    return $Call.ByID(1679514795, limit).then(($result: any) => {
        return $$createType30($result);
    });
}

export function AIListMnemonicEntries(limit: number): $CancellablePromise<ai$0.AIMnemonicEntry[]> {
    return $Call.ByID(2702940612, limit).then(($result: any) => {
        return $$createType31($result);
    });
}

export function AIListModelCapabilities(): $CancellablePromise<ai$0.AIModelCapabilityDescriptor[]> {
    return $Call.ByID(1679118339).then(($result: any) => {
        return $$createType33($result);
    });
}

export function AIListPendingApprovals(limit: number): $CancellablePromise<ai$0.AIPendingApproval[]> {
    return $Call.ByID(3049082509, limit).then(($result: any) => {
        return $$createType35($result);
    });
}

export function AIListPromptWorkflows(): $CancellablePromise<ai$0.AIPromptWorkflowDescriptor[]> {
    return $Call.ByID(1521013216).then(($result: any) => {
        return $$createType37($result);
    });
}

export function AIListProviderRuntimes(): $CancellablePromise<ai$0.AIProviderRuntimeDescriptor[]> {
    return $Call.ByID(3533759660).then(($result: any) => {
        return $$createType39($result);
    });
}

export function AIListProviders(): $CancellablePromise<ai$0.AIProviderDescriptor[]> {
    return $Call.ByID(271990918).then(($result: any) => {
        return $$createType40($result);
    });
}

export function AIListToolAudit(limit: number): $CancellablePromise<ai$0.AIToolAuditRecord[]> {
    return $Call.ByID(560606393, limit).then(($result: any) => {
        return $$createType42($result);
    });
}

export function AIListTools(): $CancellablePromise<ai$0.AIToolDescriptor[]> {
    return $Call.ByID(202355223).then(($result: any) => {
        return $$createType44($result);
    });
}

export function AIPreviewBackgroundAgent(req: ai$0.AIBackgroundAgentPreviewRequest): $CancellablePromise<ai$0.AIBackgroundAgentPreviewResult> {
    return $Call.ByID(574574373, req).then(($result: any) => {
        return $$createType45($result);
    });
}

export function AIPreviewPatch(req: ai$0.AIPatchPreviewRequest): $CancellablePromise<ai$0.AIPatchPreviewResult> {
    return $Call.ByID(1140697846, req).then(($result: any) => {
        return $$createType46($result);
    });
}

export function AIProbeModelCapability(req: ai$0.AIModelCapabilityProbeRequest): $CancellablePromise<ai$0.AIModelCapabilityProbeResult> {
    return $Call.ByID(3550373077, req).then(($result: any) => {
        return $$createType47($result);
    });
}

export function AIProposeMnemonicEntry(req: ai$0.AIMnemonicWriteProposalRequest): $CancellablePromise<ai$0.AIMnemonicWriteProposalResult> {
    return $Call.ByID(4016510054, req).then(($result: any) => {
        return $$createType48($result);
    });
}

export function AIRefreshLocalProviders(): $CancellablePromise<ai$0.AIDiscoveryResult> {
    return $Call.ByID(3987994608).then(($result: any) => {
        return $$createType49($result);
    });
}

export function AIRequestPlanRevision(req: ai$0.AIRequestPlanRevisionRequest): $CancellablePromise<ai$0.AIWorkflowRunResult> {
    return $Call.ByID(189525835, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function AIResizeAgentTerminal(runID: string, rows: number, cols: number): $CancellablePromise<void> {
    return $Call.ByID(29476953, runID, rows, cols);
}

export function AIRevokeApprovalPolicy(): $CancellablePromise<ai$0.AIApprovalPolicy> {
    return $Call.ByID(4049094955).then(($result: any) => {
        return $$createType8($result);
    });
}

export function AIRevokeContextCapsule(capsuleID: string): $CancellablePromise<ai$0.AIContextCapsuleSummary> {
    return $Call.ByID(1889277476, capsuleID).then(($result: any) => {
        return $$createType25($result);
    });
}

export function AIRollbackPatchCheckpoint(req: ai$0.AIPatchRollbackRequest): $CancellablePromise<ai$0.AIPatchRollbackResult> {
    return $Call.ByID(4293294088, req).then(($result: any) => {
        return $$createType50($result);
    });
}

export function AISaveApprovalPolicy(policy: ai$0.AIApprovalPolicy): $CancellablePromise<ai$0.AIApprovalPolicy> {
    return $Call.ByID(1405553028, policy).then(($result: any) => {
        return $$createType8($result);
    });
}

export function AISaveConsentPolicy(policy: ai$0.AIConsentPolicy): $CancellablePromise<ai$0.AIConsentPolicy> {
    return $Call.ByID(3889255099, policy).then(($result: any) => {
        return $$createType11($result);
    });
}

export function AISaveMnemonicEntry(input: ai$0.AIMnemonicEntryInput): $CancellablePromise<ai$0.AIMnemonicEntry> {
    return $Call.ByID(2691631747, input).then(($result: any) => {
        return $$createType2($result);
    });
}

export function AISavePredictionSettings(settings: ai$0.AIPredictionSettings): $CancellablePromise<ai$0.AIPredictionStatus> {
    return $Call.ByID(3644810605, settings).then(($result: any) => {
        return $$createType16($result);
    });
}

export function AISaveProviderSettings(settings: ai$0.AIProviderSettings): $CancellablePromise<ai$0.AIProviderDescriptor> {
    return $Call.ByID(3522702413, settings).then(($result: any) => {
        return $$createType5($result);
    });
}

export function AISearchMnemonic(req: ai$0.AIMnemonicSearchRequest): $CancellablePromise<ai$0.AIMnemonicEntry[]> {
    return $Call.ByID(1441185784, req).then(($result: any) => {
        return $$createType31($result);
    });
}

export function AISetMnemonicEnabled(enabled: boolean): $CancellablePromise<ai$0.AIStatus> {
    return $Call.ByID(1942126141, enabled).then(($result: any) => {
        return $$createType17($result);
    });
}

export function AIStartAgentAuthRun(providerID: string): $CancellablePromise<ai$0.AIChatRun> {
    return $Call.ByID(4220143164, providerID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function AIStartChatRun(req: ai$0.AIChatRunRequest): $CancellablePromise<ai$0.AIChatRun> {
    return $Call.ByID(2798365791, req).then(($result: any) => {
        return $$createType3($result);
    });
}

export function AIStartLinkedReview(req: ai$0.AIStartLinkedReviewRequest): $CancellablePromise<ai$0.AIWorkflowRunResult> {
    return $Call.ByID(260566205, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function AIStartProviderOAuth(providerID: string): $CancellablePromise<ai$0.AIProviderAuthSession> {
    return $Call.ByID(2003605964, providerID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function AIStartProviderRuntime(req: ai$0.AIProviderRuntimeStartRequest): $CancellablePromise<ai$0.AIProviderRuntimeDescriptor> {
    return $Call.ByID(228515795, req).then(($result: any) => {
        return $$createType38($result);
    });
}

export function AIStopProviderRuntime(providerID: string): $CancellablePromise<ai$0.AIProviderRuntimeDescriptor> {
    return $Call.ByID(2440051207, providerID).then(($result: any) => {
        return $$createType38($result);
    });
}

export function AISubmitQuestionAnswer(req: ai$0.AIQuestionAnswerRequest): $CancellablePromise<ai$0.AIQuestionAnswerResult> {
    return $Call.ByID(2209184122, req).then(($result: any) => {
        return $$createType51($result);
    });
}

export function AISuggestChatMentions(req: ai$0.AIChatMentionQuery): $CancellablePromise<ai$0.AIChatMentionCandidate[]> {
    return $Call.ByID(2827541899, req).then(($result: any) => {
        return $$createType53($result);
    });
}

export function AITestProvider(providerID: string): $CancellablePromise<ai$0.AIProviderDescriptor> {
    return $Call.ByID(1869330485, providerID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function AIUpdateMnemonicEntry(id: string, patch: ai$0.AIMnemonicEntryPatch): $CancellablePromise<ai$0.AIMnemonicEntry> {
    return $Call.ByID(2338728471, id, patch).then(($result: any) => {
        return $$createType2($result);
    });
}

export function AIWriteAgentTerminalInput(runID: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(2821198052, runID, data);
}

export function AnalyzeModels(modelName: string): $CancellablePromise<any> {
    return $Call.ByID(2530714008, modelName);
}

export function ApplyStagedAutoUpdate(): $CancellablePromise<$models.AutoUpdateStatus> {
    return $Call.ByID(3193954122).then(($result: any) => {
        return $$createType54($result);
    });
}

export function CacheClear(opts: system$0.CacheOptions): $CancellablePromise<string> {
    return $Call.ByID(2300795393, opts);
}

export function CancelApplicationClose(): $CancellablePromise<boolean> {
    return $Call.ByID(2135757718);
}

export function CancelAutoUpdate(): $CancellablePromise<$models.AutoUpdateStatus> {
    return $Call.ByID(2131516226).then(($result: any) => {
        return $$createType54($result);
    });
}

/**
 * CancelPrediction clears any pending predictions
 */
export function CancelPrediction(): $CancellablePromise<void> {
    return $Call.ByID(997180161);
}

export function CheckForAutoUpdate(): $CancellablePromise<$models.AutoUpdateStatus> {
    return $Call.ByID(2020379119).then(($result: any) => {
        return $$createType54($result);
    });
}

export function ClearApprovedDependencyActions(): $CancellablePromise<void> {
    return $Call.ByID(871148448);
}

export function ClearCompiled(): $CancellablePromise<string> {
    return $Call.ByID(2560055152);
}

export function ClearPrivateUpdateToken(): $CancellablePromise<$models.PrivateUpdateAuthStatus> {
    return $Call.ByID(1040294288).then(($result: any) => {
        return $$createType55($result);
    });
}

export function CloneRepository(repositoryURL: string, directory: string, projectName: string): $CancellablePromise<string> {
    return $Call.ByID(2251544015, repositoryURL, directory, projectName);
}

export function CloseAllTerminals(): $CancellablePromise<void> {
    return $Call.ByID(1103140018);
}

export function CloseProject(): $CancellablePromise<void> {
    return $Call.ByID(3009242219);
}

export function CloseTerminal(id: string): $CancellablePromise<void> {
    return $Call.ByID(2644038578, id);
}

export function ConfigCache(): $CancellablePromise<string> {
    return $Call.ByID(3018436242);
}

export function ConfirmApplicationClose(): $CancellablePromise<boolean> {
    return $Call.ByID(3112892232);
}

/**
 * ConfirmPrediction is called when a command is executed
 */
export function ConfirmPrediction(input: string): $CancellablePromise<void> {
    return $Call.ByID(3111888563, input);
}

export function CreateComponent(name: string, opts: plugins$0.ComponentOptions): $CancellablePromise<void> {
    return $Call.ByID(724601609, name, opts);
}

export function CreateController(name: string, opts: plugins$0.ControllerOptions): $CancellablePromise<void> {
    return $Call.ByID(1404292690, name, opts);
}

export function CreateDirectory(dirPath: string): $CancellablePromise<void> {
    return $Call.ByID(1087386121, dirPath);
}

export function CreateEnum(name: string, opts: plugins$0.EnumClassOptions): $CancellablePromise<void> {
    return $Call.ByID(3183386139, name, opts);
}

export function CreateEvent(name: string, opts: plugins$0.EventClassOptions): $CancellablePromise<void> {
    return $Call.ByID(3252456582, name, opts);
}

export function CreateFactory(name: string, opts: plugins$0.FactoryClassOptions): $CancellablePromise<void> {
    return $Call.ByID(3634170540, name, opts);
}

export function CreateJob(name: string, opts: plugins$0.JobOptions): $CancellablePromise<void> {
    return $Call.ByID(697686413, name, opts);
}

export function CreateLivewire(name: string, opts: plugins$0.LivewireComponentOptions): $CancellablePromise<void> {
    return $Call.ByID(3882498309, name, opts);
}

export function CreateMail(name: string, opts: plugins$0.MailOptions): $CancellablePromise<void> {
    return $Call.ByID(3277600329, name, opts);
}

export function CreateMigration(name: string, opts: plugins$0.MigrationOptions): $CancellablePromise<void> {
    return $Call.ByID(2297098426, name, opts);
}

export function CreateModel(name: string, opts: plugins$0.ModelOptions): $CancellablePromise<void> {
    return $Call.ByID(2896850663, name, opts);
}

export function CreateNewProject(name: string, directory: string, framework: string): $CancellablePromise<string> {
    return $Call.ByID(980233337, name, directory, framework);
}

export function CreateNotification(name: string, opts: plugins$0.NotificationOptions): $CancellablePromise<void> {
    return $Call.ByID(2834322489, name, opts);
}

export function CreatePolicy(name: string, opts: plugins$0.PolicyClassOptions): $CancellablePromise<void> {
    return $Call.ByID(311290828, name, opts);
}

export function CreateResource(name: string, opts: plugins$0.ResourceClassOptions): $CancellablePromise<void> {
    return $Call.ByID(20571138, name, opts);
}

export function CreateSeeder(name: string, opts: plugins$0.SeederClassOptions): $CancellablePromise<void> {
    return $Call.ByID(459891752, name, opts);
}

export function CreateTerminal(id: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(235502754, id, name);
}

export function CreateTerminalForProject(id: string, name: string, projectPath: string): $CancellablePromise<void> {
    return $Call.ByID(2729386138, id, name, projectPath);
}

export function DBSeed($class: string): $CancellablePromise<string> {
    return $Call.ByID(2375229505, $class);
}

export function DetectLanguage(code: string): $CancellablePromise<$models.LanguagePrediction[]> {
    return $Call.ByID(2559271775, code).then(($result: any) => {
        return $$createType57($result);
    });
}

export function DetectLanguageFromFile(filePath: string, content: string): $CancellablePromise<string> {
    return $Call.ByID(63419757, filePath, content);
}

export function DispatchCommand(input: string): $CancellablePromise<$models.DispatcherResultJS> {
    return $Call.ByID(473229233, input).then(($result: any) => {
        return $$createType58($result);
    });
}

export function DownloadAutoUpdate(): $CancellablePromise<$models.AutoUpdateStatus> {
    return $Call.ByID(658382952).then(($result: any) => {
        return $$createType54($result);
    });
}

export function DumpAutoload(): $CancellablePromise<void> {
    return $Call.ByID(328600187);
}

export function ExecuteQuery(query: string, bindings: any[]): $CancellablePromise<any> {
    return $Call.ByID(1025973563, query, bindings);
}

export function ExpandTag(input: string): $CancellablePromise<string> {
    return $Call.ByID(1025885202, input);
}

export function FindEnv(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(2841662776, path);
}

/**
 * FindFileByName searches for a file by name in a directory recursively
 * Returns all matching file paths
 */
export function FindFileByName(searchDir: string, fileName: string): $CancellablePromise<string[]> {
    return $Call.ByID(1401680497, searchDir, fileName).then(($result: any) => {
        return $$createType59($result);
    });
}

/**
 * FormatCode formats a file using code formatter (Prettier for JS/TS/HTML/CSS)
 */
export function FormatCode(filePath: string, content: string): $CancellablePromise<string> {
    return $Call.ByID(2905248636, filePath, content);
}

export function GetAllLSPServers(): $CancellablePromise<$models.LSPServerInfo[]> {
    return $Call.ByID(4096872364).then(($result: any) => {
        return $$createType61($result);
    });
}

export function GetAutoUpdateStatus(): $CancellablePromise<$models.AutoUpdateStatus> {
    return $Call.ByID(3794369294).then(($result: any) => {
        return $$createType54($result);
    });
}

/**
 * GetAutocompleteLanguageCapabilities returns language-level autocomplete support details.
 */
export function GetAutocompleteLanguageCapabilities(): $CancellablePromise<$models.AutocompleteLanguageCapability[]> {
    return $Call.ByID(1283257190).then(($result: any) => {
        return $$createType63($result);
    });
}

export function GetBackgroundShellStatus(): $CancellablePromise<$models.BackgroundShellStatusSnapshot> {
    return $Call.ByID(3067698102).then(($result: any) => {
        return $$createType64($result);
    });
}

export function GetBuildInfo(): $CancellablePromise<$models.BuildInfo> {
    return $Call.ByID(2280510586).then(($result: any) => {
        return $$createType65($result);
    });
}

export function GetCurrentProjectFramework(): $CancellablePromise<string> {
    return $Call.ByID(1203248336);
}

export function GetCurrentProjectID(): $CancellablePromise<string> {
    return $Call.ByID(3371273781);
}

/**
 * GetCurrentProjectPath returns the current project root path
 */
export function GetCurrentProjectPath(): $CancellablePromise<string> {
    return $Call.ByID(2593824287);
}

export function GetCurrentProjectWindowSession(): $CancellablePromise<$models.ProjectWindowSessionPayload> {
    return $Call.ByID(3077915216).then(($result: any) => {
        return $$createType66($result);
    });
}

export function GetCurrentWorkDir(): $CancellablePromise<string> {
    return $Call.ByID(2525994829);
}

export function GetDependencyGraph(filePath: string, depth: number): $CancellablePromise<indexer$0.DependencyGraph | null> {
    return $Call.ByID(2362147149, filePath, depth).then(($result: any) => {
        return $$createType68($result);
    });
}

export function GetDependencyPolicyPlan(consentMode: string): $CancellablePromise<depsync$0.PolicyPlan> {
    return $Call.ByID(2830371102, consentMode).then(($result: any) => {
        return $$createType69($result);
    });
}

export function GetDependencySyncPlan(mode: string): $CancellablePromise<depsync$0.Plan> {
    return $Call.ByID(2210020427, mode).then(($result: any) => {
        return $$createType70($result);
    });
}

/**
 * GetDevToolsStatus returns installation status of development tools (PHP, Go, Node, etc.)
 */
export function GetDevToolsStatus(): $CancellablePromise<welcome$0.ToolStatus[]> {
    return $Call.ByID(2497445234).then(($result: any) => {
        return $$createType72($result);
    });
}

export function GetDispatcherPinned(): $CancellablePromise<$models.ResultItemJS[]> {
    return $Call.ByID(3370448653).then(($result: any) => {
        return $$createType74($result);
    });
}

export function GetDispatcherRecent(): $CancellablePromise<$models.ResultItemJS[]> {
    return $Call.ByID(1437673616).then(($result: any) => {
        return $$createType74($result);
    });
}

export function GetDispatcherSuggestions(input: string): $CancellablePromise<$models.ResultItemJS[]> {
    return $Call.ByID(3251177080, input).then(($result: any) => {
        return $$createType74($result);
    });
}

export function GetEditorCompletions(ctx: $models.EditorCompletionContext): $CancellablePromise<$models.EditorCompletionResult> {
    return $Call.ByID(1922551346, ctx).then(($result: any) => {
        return $$createType75($result);
    });
}

export function GetExecutionProfiles(request: $models.ExecutionProfilesRequest): $CancellablePromise<execution$0.ProfileSet> {
    return $Call.ByID(3416027546, request).then(($result: any) => {
        return $$createType76($result);
    });
}

/**
 * GetGitBlame returns blame info for a file
 */
export function GetGitBlame(filePath: string): $CancellablePromise<string> {
    return $Call.ByID(2639483025, filePath);
}

/**
 * GetGitBranch returns the current git branch name
 */
export function GetGitBranch(): $CancellablePromise<string> {
    return $Call.ByID(1278498146);
}

/**
 * GetGitBranches returns list of all local branches
 */
export function GetGitBranches(): $CancellablePromise<string[]> {
    return $Call.ByID(1460332482).then(($result: any) => {
        return $$createType59($result);
    });
}

/**
 * GetGitCommitDiff returns the diff for a specific commit
 */
export function GetGitCommitDiff(commitHash: string): $CancellablePromise<string> {
    return $Call.ByID(2746986204, commitHash);
}

/**
 * GetGitDiff returns diff for a specific file or all changes
 */
export function GetGitDiff(filePath: string, staged: boolean): $CancellablePromise<string> {
    return $Call.ByID(3611457121, filePath, staged);
}

/**
 * GetGitFileAtCommit returns file content at specific commit
 */
export function GetGitFileAtCommit(filePath: string, commitHash: string): $CancellablePromise<string> {
    return $Call.ByID(3015872912, filePath, commitHash);
}

/**
 * GetGitFileDiffBetweenCommits returns diff of a file between two commits
 */
export function GetGitFileDiffBetweenCommits(filePath: string, fromCommit: string, toCommit: string): $CancellablePromise<string> {
    return $Call.ByID(2722806557, filePath, fromCommit, toCommit);
}

/**
 * GetGitLog returns commit history
 */
export function GetGitLog(limit: number, filePath: string): $CancellablePromise<$models.GitCommitInfo[]> {
    return $Call.ByID(3703725424, limit, filePath).then(($result: any) => {
        return $$createType78($result);
    });
}

/**
 * GetGitShow returns details of a specific commit
 */
export function GetGitShow(commitHash: string): $CancellablePromise<string> {
    return $Call.ByID(40344143, commitHash);
}

/**
 * GetGitStatus returns git status in porcelain format
 */
export function GetGitStatus(): $CancellablePromise<string> {
    return $Call.ByID(1919747364);
}

export function GetInlineSuggestion(filePath: string, content: string, line: number, column: number, prefix: string): $CancellablePromise<string> {
    return $Call.ByID(376927191, filePath, content, line, column, prefix);
}

export function GetLSPBinaryPath(serverID: string): $CancellablePromise<string> {
    return $Call.ByID(2696895551, serverID);
}

export function GetLSPForFile(filePath: string): $CancellablePromise<$models.LSPServerInfo | null> {
    return $Call.ByID(1917781466, filePath).then(($result: any) => {
        return $$createType79($result);
    });
}

/**
 * GetLSPInstallStatus returns installation status of LSP servers
 */
export function GetLSPInstallStatus(): $CancellablePromise<welcome$0.ToolStatus[]> {
    return $Call.ByID(3615222070).then(($result: any) => {
        return $$createType72($result);
    });
}

/**
 * GetLSPStatus returns health status of all LSP servers
 */
export function GetLSPStatus(): $CancellablePromise<lsp$0.ServerStatus[]> {
    return $Call.ByID(3128036363).then(($result: any) => {
        return $$createType81($result);
    });
}

export function GetLanguageForFile(filePath: string): $CancellablePromise<$models.LanguageInfoResult | null> {
    return $Call.ByID(3906744297, filePath).then(($result: any) => {
        return $$createType83($result);
    });
}

export function GetLaravelVersion(path: string): $CancellablePromise<string> {
    return $Call.ByID(2721087573, path);
}

export function GetLastAutocompleteTrace(): $CancellablePromise<brain$0.CompletionTrace> {
    return $Call.ByID(3503910979).then(($result: any) => {
        return $$createType84($result);
    });
}

export function GetMCPSettings(): $CancellablePromise<$models.MCPSettingsStatus> {
    return $Call.ByID(272325539).then(($result: any) => {
        return $$createType85($result);
    });
}

export function GetMiddlewareList(): $CancellablePromise<any> {
    return $Call.ByID(2180579094);
}

export function GetPackagedOSIntegrationStatus(): $CancellablePromise<$models.PackagedOSIntegrationSnapshot> {
    return $Call.ByID(3845279568).then(($result: any) => {
        return $$createType86($result);
    });
}

export function GetPluginCommands(): $CancellablePromise<$models.PluginCommandDefJS[]> {
    return $Call.ByID(931735635).then(($result: any) => {
        return $$createType88($result);
    });
}

export function GetPrivateUpdateAuthStatus(): $CancellablePromise<$models.PrivateUpdateAuthStatus> {
    return $Call.ByID(926527160).then(($result: any) => {
        return $$createType55($result);
    });
}

export function GetProjectWindowSession(sessionID: string): $CancellablePromise<$models.ProjectWindowSessionPayload> {
    return $Call.ByID(3178930845, sessionID).then(($result: any) => {
        return $$createType66($result);
    });
}

export function GetRecentProjects(limit: number): $CancellablePromise<project$0.Project[]> {
    return $Call.ByID(1425955691, limit).then(($result: any) => {
        return $$createType90($result);
    });
}

export function GetRelatedFiles(filePath: string): $CancellablePromise<indexer$0.FileRelation[]> {
    return $Call.ByID(2278641048, filePath).then(($result: any) => {
        return $$createType92($result);
    });
}

export function GetRouteList(filter: string): $CancellablePromise<any> {
    return $Call.ByID(4183578243, filter);
}

export function GetSearchIndexStatus(): $CancellablePromise<dispatcher$0.SearchBackendStatus> {
    return $Call.ByID(3845559944).then(($result: any) => {
        return $$createType93($result);
    });
}

export function GetShellCapabilities(): $CancellablePromise<$models.ShellCapabilitiesSnapshot> {
    return $Call.ByID(1382644170).then(($result: any) => {
        return $$createType94($result);
    });
}

export function GetSupportedLanguages(): $CancellablePromise<string[]> {
    return $Call.ByID(2571379691).then(($result: any) => {
        return $$createType59($result);
    });
}

export function GetTerminalHistory(limit: number): $CancellablePromise<string[]> {
    return $Call.ByID(3017116498, limit).then(($result: any) => {
        return $$createType59($result);
    });
}

export function GetTerminalPreview(command: string): $CancellablePromise<$models.TerminalPreviewJS> {
    return $Call.ByID(2082398734, command).then(($result: any) => {
        return $$createType95($result);
    });
}

export function GetWails3PackagedSmokeReport(args: string[]): $CancellablePromise<$models.Wails3PackagedSmokeReport> {
    return $Call.ByID(2800269332, args).then(($result: any) => {
        return $$createType96($result);
    });
}

export function GetWindowLeaseStatus(): $CancellablePromise<$models.WindowLeaseSnapshot> {
    return $Call.ByID(493136510).then(($result: any) => {
        return $$createType97($result);
    });
}

/**
 * GoToDefinition finds definition for a symbol at given position
 * Uses indexed data for fast lookup, falls back to LSP
 */
export function GoToDefinition(filePath: string, content: string, line: number, column: number, word: string, beforeWord: string, afterWord: string): $CancellablePromise<$models.DefinitionResult[]> {
    return $Call.ByID(478407520, filePath, content, line, column, word, beforeWord, afterWord).then(($result: any) => {
        return $$createType99($result);
    });
}

export function Greet(name: string): $CancellablePromise<string> {
    return $Call.ByID(2912079387, name);
}

export function ImportShellHistory(projectID: string, historyPath: string, workDir: string): $CancellablePromise<void> {
    return $Call.ByID(853170281, projectID, historyPath, workDir);
}

export function IndexLaravelAll(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3426453654).then(($result: any) => {
        return $$createType100($result);
    });
}

export function IndexLaravelConfig(): $CancellablePromise<string> {
    return $Call.ByID(4060223649);
}

export function IndexLaravelModels(): $CancellablePromise<string> {
    return $Call.ByID(3474920777);
}

export function IndexLaravelRoutes(): $CancellablePromise<string> {
    return $Call.ByID(1889572537);
}

export function IndexLaravelViews(): $CancellablePromise<string> {
    return $Call.ByID(2169319791);
}

export function InitDispatcherForProject(): $CancellablePromise<void> {
    return $Call.ByID(3004685225);
}

export function InspectEditorFile(filePath: string): $CancellablePromise<$models.EditorFileInspection> {
    return $Call.ByID(114260637, filePath).then(($result: any) => {
        return $$createType101($result);
    });
}

export function InspectProject(): $CancellablePromise<any> {
    return $Call.ByID(4029723443);
}

export function InspectProjectAccess(path: string): $CancellablePromise<$models.ProjectAccessInspection> {
    return $Call.ByID(2130412873, path).then(($result: any) => {
        return $$createType102($result);
    });
}

export function InstallAll(): $CancellablePromise<void> {
    return $Call.ByID(2006479156);
}

export function InstallBreeze(): $CancellablePromise<void> {
    return $Call.ByID(3885650062);
}

/**
 * InstallDevTool installs a development tool or LSP server
 */
export function InstallDevTool(toolName: string): $CancellablePromise<string> {
    return $Call.ByID(3418213846, toolName);
}

export function InstallFortify(): $CancellablePromise<void> {
    return $Call.ByID(1632069174);
}

export function InstallJetstream(): $CancellablePromise<void> {
    return $Call.ByID(498778204);
}

export function InstallLSPServer(serverID: string): $CancellablePromise<void> {
    return $Call.ByID(3999527395, serverID);
}

export function InstallLivewire(): $CancellablePromise<void> {
    return $Call.ByID(2728774898);
}

export function InstallPackage(name: string, opts: composer$0.InstallOptions): $CancellablePromise<void> {
    return $Call.ByID(2452996107, name, opts);
}

export function IsLSPInstalling(serverID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3994420820, serverID);
}

export function IsLangDetectorLoaded(): $CancellablePromise<boolean> {
    return $Call.ByID(765696061);
}

export function IsLaravelProject(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(3205795312, path);
}

export function IsNativeFullscreen(): $CancellablePromise<boolean> {
    return $Call.ByID(238593744);
}

export function LSPApplyWorkspaceEdit(edit: $models.LSPWorkspaceEdit | null): $CancellablePromise<void> {
    return $Call.ByID(693429932, edit);
}

export function LSPGetCodeActions(filePath: string, content: string, line: number, character: number): $CancellablePromise<$models.LSPCodeAction[]> {
    return $Call.ByID(3094221445, filePath, content, line, character).then(($result: any) => {
        return $$createType104($result);
    });
}

export function LSPGetDiagnostics(filePath: string): $CancellablePromise<$models.LSPDiagnostic[]> {
    return $Call.ByID(2460201797, filePath).then(($result: any) => {
        return $$createType106($result);
    });
}

/**
 * LSPGoToDefinition finds definition using unified LSP manager
 */
export function LSPGoToDefinition(filePath: string, content: string, line: number, character: number): $CancellablePromise<$models.LSPDefinitionResult[]> {
    return $Call.ByID(1788738471, filePath, content, line, character).then(($result: any) => {
        return $$createType108($result);
    });
}

/**
 * LSPHover returns hover information for a symbol
 */
export function LSPHover(filePath: string, content: string, line: number, character: number): $CancellablePromise<string> {
    return $Call.ByID(1356682693, filePath, content, line, character);
}

export function LSPPreloadProjectDiagnostics(projectPath: string): $CancellablePromise<boolean> {
    return $Call.ByID(3440809205, projectPath);
}

/**
 * LSPSignatureHelp returns signature help for a function call
 */
export function LSPSignatureHelp(filePath: string, content: string, line: number, character: number): $CancellablePromise<$models.SignatureHelpResult | null> {
    return $Call.ByID(1305918266, filePath, content, line, character).then(($result: any) => {
        return $$createType110($result);
    });
}

export function ListApprovedDependencyActions(): $CancellablePromise<string[]> {
    return $Call.ByID(2370967423).then(($result: any) => {
        return $$createType59($result);
    });
}

export function ListInstalledPackages(): $CancellablePromise<string> {
    return $Call.ByID(299341705);
}

export function ListTerminalSessions(): $CancellablePromise<string[]> {
    return $Call.ByID(1100446623).then(($result: any) => {
        return $$createType59($result);
    });
}

export function Migrate(opts: system$0.MigrateOptions): $CancellablePromise<string> {
    return $Call.ByID(384045079, opts);
}

export function MigrateFresh(opts: system$0.MigrateRefreshOptions): $CancellablePromise<string> {
    return $Call.ByID(3039983393, opts);
}

export function MigrateRefresh(opts: system$0.MigrateRefreshOptions): $CancellablePromise<string> {
    return $Call.ByID(448313018, opts);
}

export function MigrateReset(opts: system$0.MigrateResetOptions): $CancellablePromise<string> {
    return $Call.ByID(3735398646, opts);
}

export function MigrateRollback(opts: system$0.MigrateRollbackOptions): $CancellablePromise<string> {
    return $Call.ByID(4044463411, opts);
}

export function MigrateSeed(opts: system$0.MigrateOptions): $CancellablePromise<string> {
    return $Call.ByID(3764159498, opts);
}

export function MigrateStatus(): $CancellablePromise<string> {
    return $Call.ByID(287664385);
}

export function MoveProjectEntry(path: string, targetDirectory: string): $CancellablePromise<$models.ProjectEntryMoveResult> {
    return $Call.ByID(1959204684, path, targetDirectory).then(($result: any) => {
        return $$createType111($result);
    });
}

/**
 * NotifyFileChanged notifies LSP servers when a file content changes
 */
export function NotifyFileChanged(filePath: string, language: string, version: number, content: string): $CancellablePromise<void> {
    return $Call.ByID(1567090827, filePath, language, version, content);
}

/**
 * NotifyFileClosed notifies LSP servers when a file is closed
 */
export function NotifyFileClosed(filePath: string, language: string): $CancellablePromise<void> {
    return $Call.ByID(2376410677, filePath, language);
}

/**
 * NotifyFileOpened notifies LSP servers when a file is opened in the editor
 */
export function NotifyFileOpened(filePath: string, language: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(625133520, filePath, language, content);
}

export function OpenNativeContextMenu(request: $models.NativeContextMenuRequest): $CancellablePromise<$models.NativeContextMenuResponse> {
    return $Call.ByID(4034583415, request).then(($result: any) => {
        return $$createType112($result);
    });
}

export function OpenProject(path: string): $CancellablePromise<void> {
    return $Call.ByID(2842778799, path);
}

export function OpenProjectWindow(path: string): $CancellablePromise<$models.ProjectWindowLaunchResult> {
    return $Call.ByID(3704102895, path).then(($result: any) => {
        return $$createType113($result);
    });
}

export function OpenProjectWindowSession(sessionID: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(1171889337, sessionID, path);
}

export function ParseCommand(input: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(1388141726, input).then(($result: any) => {
        return $$createType100($result);
    });
}

export function PinCommand(cmd: string): $CancellablePromise<void> {
    return $Call.ByID(3339839442, cmd);
}

export function PositionNativeWindowControls(closeX: number, closeY: number, minimiseX: number, minimiseY: number, maximiseX: number, maximiseY: number): $CancellablePromise<boolean> {
    return $Call.ByID(3063460412, closeX, closeY, minimiseX, minimiseY, maximiseX, maximiseY);
}

export function PredictCommand(input: string): $CancellablePromise<$models.ClassResult | null> {
    return $Call.ByID(3501135860, input).then(($result: any) => {
        return $$createType115($result);
    });
}

export function PredictTerminalCommand(req: $models.TerminalPredictionRequest): $CancellablePromise<$models.TerminalPredictionResponse> {
    return $Call.ByID(2824179160, req).then(($result: any) => {
        return $$createType116($result);
    });
}

export function PublishAssets(packageName: string, tags: string[]): $CancellablePromise<void> {
    return $Call.ByID(560416464, packageName, tags);
}

export function QueueWork(connection: string, queue: string): $CancellablePromise<void> {
    return $Call.ByID(1975917236, connection, queue);
}

export function ReadDirectory(dirPath: string): $CancellablePromise<$models.FileEntry[]> {
    return $Call.ByID(500956621, dirPath).then(($result: any) => {
        return $$createType118($result);
    });
}

export function ReadEditorBinaryFile(filePath: string): $CancellablePromise<$models.EditorBinaryFile> {
    return $Call.ByID(1714943980, filePath).then(($result: any) => {
        return $$createType119($result);
    });
}

export function ReadEditorFilePreview(filePath: string, maxBytes: number): $CancellablePromise<$models.EditorFilePreview> {
    return $Call.ByID(1734762579, filePath, maxBytes).then(($result: any) => {
        return $$createType120($result);
    });
}

export function ReadEditorVisualFile(filePath: string): $CancellablePromise<$models.EditorVisualFile> {
    return $Call.ByID(3196754789, filePath).then(($result: any) => {
        return $$createType121($result);
    });
}

export function ReadFile(filePath: string): $CancellablePromise<string> {
    return $Call.ByID(2878347744, filePath);
}

export function RebuildSearchIndex(): $CancellablePromise<dispatcher$0.SearchBackendStatus> {
    return $Call.ByID(1241435419).then(($result: any) => {
        return $$createType93($result);
    });
}

export function RecordCommandExecution(projectID: string, command: string, workDir: string): $CancellablePromise<void> {
    return $Call.ByID(1046187262, projectID, command, workDir);
}

export function RecordCompletionUsage(label: string): $CancellablePromise<void> {
    return $Call.ByID(2432176424, label);
}

export function RecordFileAccess(filePath: string): $CancellablePromise<void> {
    return $Call.ByID(774283707, filePath);
}

export function RecordGhostRejected(): $CancellablePromise<void> {
    return $Call.ByID(1513171292);
}

export function RecordGhostShown(): $CancellablePromise<void> {
    return $Call.ByID(207276895);
}

export function RecordTypingActivity(chars: number): $CancellablePromise<void> {
    return $Call.ByID(1790719449, chars);
}

export function RefreshNativeWindowControls(): $CancellablePromise<boolean> {
    return $Call.ByID(2092322392);
}

export function RemovePackage(name: string, opts: composer$0.RemoveOptions): $CancellablePromise<void> {
    return $Call.ByID(3740764738, name, opts);
}

export function RenameProjectEntry(path: string, newName: string): $CancellablePromise<$models.ProjectEntryRenameResult> {
    return $Call.ByID(1128153851, path, newName).then(($result: any) => {
        return $$createType122($result);
    });
}

export function ResizeTerminal(id: string, rows: number, cols: number): $CancellablePromise<void> {
    return $Call.ByID(2378749434, id, rows, cols);
}

/**
 * RestartLSPServer force-restarts a specific LSP server.
 */
export function RestartLSPServer(language: string): $CancellablePromise<boolean> {
    return $Call.ByID(3339885415, language);
}

export function RevealProjectEntry(path: string): $CancellablePromise<void> {
    return $Call.ByID(3073650660, path);
}

export function RouteCache(): $CancellablePromise<string> {
    return $Call.ByID(3088116603);
}

export function RunBackgroundShellAction(actionID: string): $CancellablePromise<$models.BackgroundShellActionResult> {
    return $Call.ByID(2676301637, actionID).then(($result: any) => {
        return $$createType123($result);
    });
}

export function RunDependencyPolicySync(req: depsync$0.ExecuteRequest): $CancellablePromise<depsync$0.ExecuteResult> {
    return $Call.ByID(4132946231, req).then(($result: any) => {
        return $$createType124($result);
    });
}

/**
 * RunGitCommand executes a git command in the project directory
 */
export function RunGitCommand(args: string[]): $CancellablePromise<string> {
    return $Call.ByID(400581002, args);
}

export function RunMigrate(): $CancellablePromise<void> {
    return $Call.ByID(3041314932);
}

export function RunPackagedOSIntegrationAction(actionID: string): $CancellablePromise<$models.PackagedOSActionResult> {
    return $Call.ByID(1943779455, actionID).then(($result: any) => {
        return $$createType125($result);
    });
}

export function RunWindowLeaseAction(actionID: string): $CancellablePromise<$models.WindowLeaseActionResult> {
    return $Call.ByID(1655910089, actionID).then(($result: any) => {
        return $$createType126($result);
    });
}

export function SaveMCPSettings(settings: mcp$0.Settings): $CancellablePromise<$models.MCPSettingsStatus> {
    return $Call.ByID(2796781428, settings).then(($result: any) => {
        return $$createType85($result);
    });
}

export function SavePrivateUpdateToken(token: string): $CancellablePromise<$models.PrivateUpdateAuthStatus> {
    return $Call.ByID(2166894452, token).then(($result: any) => {
        return $$createType55($result);
    });
}

export function ScheduleRun(): $CancellablePromise<string> {
    return $Call.ByID(2056674812);
}

export function SearchClasses(prefix: string): $CancellablePromise<$models.ClassResult[]> {
    return $Call.ByID(874301014, prefix).then(($result: any) => {
        return $$createType127($result);
    });
}

export function SearchContent(query: string): $CancellablePromise<$models.ResultItemJS[]> {
    return $Call.ByID(2143790527, query).then(($result: any) => {
        return $$createType74($result);
    });
}

export function SearchFiles(pattern: string): $CancellablePromise<$models.ResultItemJS[]> {
    return $Call.ByID(993821393, pattern).then(($result: any) => {
        return $$createType74($result);
    });
}

/**
 * SearchInProject searches for a query string in all project files
 */
export function SearchInProject(query: string, caseSensitive: boolean, useRegex: boolean, wholeWord: boolean): $CancellablePromise<$models.SearchResult[]> {
    return $Call.ByID(2391516234, query, caseSensitive, useRegex, wholeWord).then(($result: any) => {
        return $$createType129($result);
    });
}

export function SearchSymbols(query: string): $CancellablePromise<$models.ResultItemJS[]> {
    return $Call.ByID(597251807, query).then(($result: any) => {
        return $$createType74($result);
    });
}

export function SelectDirectory(title: string): $CancellablePromise<string> {
    return $Call.ByID(2804908541, title);
}

export function SelectOpenTarget(title: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3890198791, title).then(($result: any) => {
        return $$createType100($result);
    });
}

export function SendTerminalText(id: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(2730424515, id, text);
}

export function Serve(opts: system$0.ServeOptions): $CancellablePromise<void> {
    return $Call.ByID(3429320129, opts);
}

export function SetApplicationIconAppearance(appearance: string): $CancellablePromise<boolean> {
    return $Call.ByID(2459870727, appearance);
}

export function SetCloseConfirmationEnabled(enabled: boolean): $CancellablePromise<boolean> {
    return $Call.ByID(409774704, enabled);
}

export function SetNativeWindowControlsVisible(visible: boolean): $CancellablePromise<boolean> {
    return $Call.ByID(3411965839, visible);
}

export function ShowPackageInfo(name: string): $CancellablePromise<string> {
    return $Call.ByID(207457449, name);
}

export function StorageLink(): $CancellablePromise<string> {
    return $Call.ByID(2745057471);
}

export function SuggestCommand(input: string): $CancellablePromise<$models.CommandSuggestion[]> {
    return $Call.ByID(141691869, input).then(($result: any) => {
        return $$createType131($result);
    });
}

export function SyncApplicationMenuShortcuts(payload: $models.ApplicationMenuShortcutPayload[]): $CancellablePromise<void> {
    return $Call.ByID(2305528493, payload);
}

export function SyncApplicationMenuState(payload: $models.ShellMenuStatePayload): $CancellablePromise<void> {
    return $Call.ByID(666990439, payload);
}

export function SyncProjectDependencies(mode: string): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(3713092259, mode).then(($result: any) => {
        return $$createType132($result);
    });
}

export function Tinker(): $CancellablePromise<void> {
    return $Call.ByID(3296933401);
}

export function ToggleNativeFullscreen(): $CancellablePromise<void> {
    return $Call.ByID(3730786860);
}

export function TrashProjectEntry(path: string): $CancellablePromise<void> {
    return $Call.ByID(1597950935, path);
}

export function UnpinCommand(cmd: string): $CancellablePromise<void> {
    return $Call.ByID(2316907637, cmd);
}

export function UpdateAll(): $CancellablePromise<void> {
    return $Call.ByID(3341221074);
}

export function UpdatePackage(name: string): $CancellablePromise<void> {
    return $Call.ByID(2217986349, name);
}

/**
 * UpdatePrediction updates the speculative store based on terminal input
 */
export function UpdatePrediction(input: string): $CancellablePromise<void> {
    return $Call.ByID(190856246, input);
}

export function ValidateEnvironment(): $CancellablePromise<{ [_ in string]?: boolean }> {
    return $Call.ByID(3496235921).then(($result: any) => {
        return $$createType133($result);
    });
}

export function ViewCache(): $CancellablePromise<string> {
    return $Call.ByID(1742689507);
}

export function WriteFile(filePath: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(313870991, filePath, content);
}

export function WriteTerminal(id: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(3664655101, id, data);
}

// Private type creation functions
const $$createType0 = ai$0.AIWorkflowRunResult.createFrom;
const $$createType1 = ai$0.AIPatchApplyResult.createFrom;
const $$createType2 = ai$0.AIMnemonicEntry.createFrom;
const $$createType3 = ai$0.AIChatRun.createFrom;
const $$createType4 = ai$0.AIProviderAuthSession.createFrom;
const $$createType5 = providers$0.AIProviderDescriptor.createFrom;
const $$createType6 = ai$0.AIContextCompactionResult.createFrom;
const $$createType7 = ai$0.AIToolCallResult.createFrom;
const $$createType8 = ai$0.AIApprovalPolicy.createFrom;
const $$createType9 = ai$0.AIChatRunArtifact.createFrom;
const $$createType10 = ai$0.AIChatRunEnvelope.createFrom;
const $$createType11 = ai$0.AIConsentPolicy.createFrom;
const $$createType12 = ai$0.AIContextContinuationPlan.createFrom;
const $$createType13 = ai$0.AIContextSnapshot.createFrom;
const $$createType14 = ai$0.AIContinuationResponse.createFrom;
const $$createType15 = ai$0.AIEmbeddingStatus.createFrom;
const $$createType16 = ai$0.AIPredictionStatus.createFrom;
const $$createType17 = ai$0.AIStatus.createFrom;
const $$createType18 = ai$0.AIMnemonicInspection.createFrom;
const $$createType19 = ai$0.AIAgentProfileDescriptor.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = ai$0.AIChatActionDescriptor.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = $Create.Array($$createType9);
const $$createType24 = $Create.Array($$createType10);
const $$createType25 = ai$0.AIContextCapsuleSummary.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = ai$0.AIContextProviderDescriptor.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = ai$0.AIEgressRecord.createFrom;
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = $Create.Array($$createType2);
const $$createType32 = ai$0.AIModelCapabilityDescriptor.createFrom;
const $$createType33 = $Create.Array($$createType32);
const $$createType34 = ai$0.AIPendingApproval.createFrom;
const $$createType35 = $Create.Array($$createType34);
const $$createType36 = ai$0.AIPromptWorkflowDescriptor.createFrom;
const $$createType37 = $Create.Array($$createType36);
const $$createType38 = ai$0.AIProviderRuntimeDescriptor.createFrom;
const $$createType39 = $Create.Array($$createType38);
const $$createType40 = $Create.Array($$createType5);
const $$createType41 = ai$0.AIToolAuditRecord.createFrom;
const $$createType42 = $Create.Array($$createType41);
const $$createType43 = ai$0.AIToolDescriptor.createFrom;
const $$createType44 = $Create.Array($$createType43);
const $$createType45 = ai$0.AIBackgroundAgentPreviewResult.createFrom;
const $$createType46 = ai$0.AIPatchPreviewResult.createFrom;
const $$createType47 = ai$0.AIModelCapabilityProbeResult.createFrom;
const $$createType48 = ai$0.AIMnemonicWriteProposalResult.createFrom;
const $$createType49 = ai$0.AIDiscoveryResult.createFrom;
const $$createType50 = ai$0.AIPatchRollbackResult.createFrom;
const $$createType51 = ai$0.AIQuestionAnswerResult.createFrom;
const $$createType52 = ai$0.AIChatMentionCandidate.createFrom;
const $$createType53 = $Create.Array($$createType52);
const $$createType54 = $models.AutoUpdateStatus.createFrom;
const $$createType55 = $models.PrivateUpdateAuthStatus.createFrom;
const $$createType56 = $models.LanguagePrediction.createFrom;
const $$createType57 = $Create.Array($$createType56);
const $$createType58 = $models.DispatcherResultJS.createFrom;
const $$createType59 = $Create.Array($Create.Any);
const $$createType60 = $models.LSPServerInfo.createFrom;
const $$createType61 = $Create.Array($$createType60);
const $$createType62 = autocomplete$0.LanguageCapability.createFrom;
const $$createType63 = $Create.Array($$createType62);
const $$createType64 = $models.BackgroundShellStatusSnapshot.createFrom;
const $$createType65 = $models.BuildInfo.createFrom;
const $$createType66 = $models.ProjectWindowSessionPayload.createFrom;
const $$createType67 = indexer$0.DependencyGraph.createFrom;
const $$createType68 = $Create.Nullable($$createType67);
const $$createType69 = depsync$0.PolicyPlan.createFrom;
const $$createType70 = depsync$0.Plan.createFrom;
const $$createType71 = welcome$0.ToolStatus.createFrom;
const $$createType72 = $Create.Array($$createType71);
const $$createType73 = $models.ResultItemJS.createFrom;
const $$createType74 = $Create.Array($$createType73);
const $$createType75 = $models.EditorCompletionResult.createFrom;
const $$createType76 = execution$0.ProfileSet.createFrom;
const $$createType77 = $models.GitCommitInfo.createFrom;
const $$createType78 = $Create.Array($$createType77);
const $$createType79 = $Create.Nullable($$createType60);
const $$createType80 = lsp$0.ServerStatus.createFrom;
const $$createType81 = $Create.Array($$createType80);
const $$createType82 = $models.LanguageInfoResult.createFrom;
const $$createType83 = $Create.Nullable($$createType82);
const $$createType84 = brain$0.CompletionTrace.createFrom;
const $$createType85 = $models.MCPSettingsStatus.createFrom;
const $$createType86 = $models.PackagedOSIntegrationSnapshot.createFrom;
const $$createType87 = $models.PluginCommandDefJS.createFrom;
const $$createType88 = $Create.Array($$createType87);
const $$createType89 = project$0.Project.createFrom;
const $$createType90 = $Create.Array($$createType89);
const $$createType91 = indexer$0.FileRelation.createFrom;
const $$createType92 = $Create.Array($$createType91);
const $$createType93 = dispatcher$0.SearchBackendStatus.createFrom;
const $$createType94 = $models.ShellCapabilitiesSnapshot.createFrom;
const $$createType95 = $models.TerminalPreviewJS.createFrom;
const $$createType96 = $models.Wails3PackagedSmokeReport.createFrom;
const $$createType97 = $models.WindowLeaseSnapshot.createFrom;
const $$createType98 = $models.DefinitionResult.createFrom;
const $$createType99 = $Create.Array($$createType98);
const $$createType100 = $Create.Map($Create.Any, $Create.Any);
const $$createType101 = $models.EditorFileInspection.createFrom;
const $$createType102 = $models.ProjectAccessInspection.createFrom;
const $$createType103 = $models.LSPCodeAction.createFrom;
const $$createType104 = $Create.Array($$createType103);
const $$createType105 = $models.LSPDiagnostic.createFrom;
const $$createType106 = $Create.Array($$createType105);
const $$createType107 = $models.LSPDefinitionResult.createFrom;
const $$createType108 = $Create.Array($$createType107);
const $$createType109 = $models.SignatureHelpResult.createFrom;
const $$createType110 = $Create.Nullable($$createType109);
const $$createType111 = $models.ProjectEntryMoveResult.createFrom;
const $$createType112 = $models.NativeContextMenuResponse.createFrom;
const $$createType113 = $models.ProjectWindowLaunchResult.createFrom;
const $$createType114 = $models.ClassResult.createFrom;
const $$createType115 = $Create.Nullable($$createType114);
const $$createType116 = $models.TerminalPredictionResponse.createFrom;
const $$createType117 = $models.FileEntry.createFrom;
const $$createType118 = $Create.Array($$createType117);
const $$createType119 = $models.EditorBinaryFile.createFrom;
const $$createType120 = $models.EditorFilePreview.createFrom;
const $$createType121 = $models.EditorVisualFile.createFrom;
const $$createType122 = $models.ProjectEntryRenameResult.createFrom;
const $$createType123 = $models.BackgroundShellActionResult.createFrom;
const $$createType124 = depsync$0.ExecuteResult.createFrom;
const $$createType125 = $models.PackagedOSActionResult.createFrom;
const $$createType126 = $models.WindowLeaseActionResult.createFrom;
const $$createType127 = $Create.Array($$createType114);
const $$createType128 = $models.SearchResult.createFrom;
const $$createType129 = $Create.Array($$createType128);
const $$createType130 = $models.CommandSuggestion.createFrom;
const $$createType131 = $Create.Array($$createType130);
const $$createType132 = $Create.Map($Create.Any, $Create.Any);
const $$createType133 = $Create.Map($Create.Any, $Create.Any);
