// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

export class Action {
    "id": string;
    "ecosystem": string;
    "tool": string;
    "manifest": string;
    "label": string;
    "executable": string;
    "args": string;
    "safe": boolean;
    "capability": DependencyCapability;
    "mutationRisk": MutationRisk;
    "requiresConsent": boolean;

    /** Creates a new Action instance. */
    constructor($$source: Partial<Action> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("ecosystem" in $$source)) {
            this["ecosystem"] = "";
        }
        if (!("tool" in $$source)) {
            this["tool"] = "";
        }
        if (!("manifest" in $$source)) {
            this["manifest"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("executable" in $$source)) {
            this["executable"] = "";
        }
        if (!("args" in $$source)) {
            this["args"] = "";
        }
        if (!("safe" in $$source)) {
            this["safe"] = false;
        }
        if (!("capability" in $$source)) {
            this["capability"] = DependencyCapability.$zero;
        }
        if (!("mutationRisk" in $$source)) {
            this["mutationRisk"] = MutationRisk.$zero;
        }
        if (!("requiresConsent" in $$source)) {
            this["requiresConsent"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Action instance from a string or object.
     */
    static createFrom($$source: any = {}): Action {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Action($$parsedSource as Partial<Action>);
    }
}

export class ActionDescriptor {
    "action": Action;
    "manifestDir": string;
    "availabilityState": AvailabilityState;
    "availabilityReason"?: string;
    "requiresConsent": boolean;
    "approvalEligible": boolean;

    /** Creates a new ActionDescriptor instance. */
    constructor($$source: Partial<ActionDescriptor> = {}) {
        if (!("action" in $$source)) {
            this["action"] = (new Action());
        }
        if (!("manifestDir" in $$source)) {
            this["manifestDir"] = "";
        }
        if (!("availabilityState" in $$source)) {
            this["availabilityState"] = AvailabilityState.$zero;
        }
        if (!("requiresConsent" in $$source)) {
            this["requiresConsent"] = false;
        }
        if (!("approvalEligible" in $$source)) {
            this["approvalEligible"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActionDescriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): ActionDescriptor {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("action" in $$parsedSource) {
            $$parsedSource["action"] = $$createField0_0($$parsedSource["action"]);
        }
        return new ActionDescriptor($$parsedSource as Partial<ActionDescriptor>);
    }
}

export class ActionOutcome {
    "actionId": string;
    "action": Action;
    "status": OutcomeStatus;
    "message": string;

    /** Creates a new ActionOutcome instance. */
    constructor($$source: Partial<ActionOutcome> = {}) {
        if (!("actionId" in $$source)) {
            this["actionId"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = (new Action());
        }
        if (!("status" in $$source)) {
            this["status"] = OutcomeStatus.$zero;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActionOutcome instance from a string or object.
     */
    static createFrom($$source: any = {}): ActionOutcome {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("action" in $$parsedSource) {
            $$parsedSource["action"] = $$createField1_0($$parsedSource["action"]);
        }
        return new ActionOutcome($$parsedSource as Partial<ActionOutcome>);
    }
}

export enum AvailabilityState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AvailabilityRunnable = "runnable",
    AvailabilityUnavailable = "unavailable",
};

export class Command {
    "label": string;
    "executable": string;
    "args": string;
    "safe": boolean;
    "capability"?: DependencyCapability;
    "mutationRisk"?: MutationRisk;

    /** Creates a new Command instance. */
    constructor($$source: Partial<Command> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("executable" in $$source)) {
            this["executable"] = "";
        }
        if (!("args" in $$source)) {
            this["args"] = "";
        }
        if (!("safe" in $$source)) {
            this["safe"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Command instance from a string or object.
     */
    static createFrom($$source: any = {}): Command {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Command($$parsedSource as Partial<Command>);
    }
}

export enum ConsentMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ConsentModeConfirmOncePerProject = "confirm-once-per-project",
    ConsentModeConfirmEachTime = "confirm-each-time",
    ConsentModeNeverAuto = "never-auto",
};

export enum DependencyCapability {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CapabilityResolveOnly = "resolve_only",
    CapabilityDeclareAndLock = "declare_and_lock",
    CapabilityDeclareAndInstall = "declare_and_install",
    CapabilityInitInfrastructure = "init_plugins_modules",
};

export class ExecuteRequest {
    "policy": Policy;
    "approvedActionIds": string[];
    "persistApprovals": boolean;
    "dryRun": boolean;

    /** Creates a new ExecuteRequest instance. */
    constructor($$source: Partial<ExecuteRequest> = {}) {
        if (!("policy" in $$source)) {
            this["policy"] = (new Policy());
        }
        if (!("approvedActionIds" in $$source)) {
            this["approvedActionIds"] = [];
        }
        if (!("persistApprovals" in $$source)) {
            this["persistApprovals"] = false;
        }
        if (!("dryRun" in $$source)) {
            this["dryRun"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExecuteRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ExecuteRequest {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("policy" in $$parsedSource) {
            $$parsedSource["policy"] = $$createField0_0($$parsedSource["policy"]);
        }
        if ("approvedActionIds" in $$parsedSource) {
            $$parsedSource["approvedActionIds"] = $$createField1_0($$parsedSource["approvedActionIds"]);
        }
        return new ExecuteRequest($$parsedSource as Partial<ExecuteRequest>);
    }
}

export class ExecuteResult {
    "outcomes": ActionOutcome[];

    /** Creates a new ExecuteResult instance. */
    constructor($$source: Partial<ExecuteResult> = {}) {
        if (!("outcomes" in $$source)) {
            this["outcomes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExecuteResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ExecuteResult {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("outcomes" in $$parsedSource) {
            $$parsedSource["outcomes"] = $$createField0_0($$parsedSource["outcomes"]);
        }
        return new ExecuteResult($$parsedSource as Partial<ExecuteResult>);
    }
}

export class FlatExecuteResult {
    "results": { [_ in string]?: string };
    "blocked": { [_ in string]?: string };

    /** Creates a new FlatExecuteResult instance. */
    constructor($$source: Partial<FlatExecuteResult> = {}) {
        if (!("results" in $$source)) {
            this["results"] = {};
        }
        if (!("blocked" in $$source)) {
            this["blocked"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FlatExecuteResult instance from a string or object.
     */
    static createFrom($$source: any = {}): FlatExecuteResult {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField0_0($$parsedSource["results"]);
        }
        if ("blocked" in $$parsedSource) {
            $$parsedSource["blocked"] = $$createField1_0($$parsedSource["blocked"]);
        }
        return new FlatExecuteResult($$parsedSource as Partial<FlatExecuteResult>);
    }
}

export class FlatPolicyPlan {
    "projectPath": string;
    "policy": Policy;
    "actions": Action[];

    /** Creates a new FlatPolicyPlan instance. */
    constructor($$source: Partial<FlatPolicyPlan> = {}) {
        if (!("projectPath" in $$source)) {
            this["projectPath"] = "";
        }
        if (!("policy" in $$source)) {
            this["policy"] = (new Policy());
        }
        if (!("actions" in $$source)) {
            this["actions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FlatPolicyPlan instance from a string or object.
     */
    static createFrom($$source: any = {}): FlatPolicyPlan {
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("policy" in $$parsedSource) {
            $$parsedSource["policy"] = $$createField1_0($$parsedSource["policy"]);
        }
        if ("actions" in $$parsedSource) {
            $$parsedSource["actions"] = $$createField2_0($$parsedSource["actions"]);
        }
        return new FlatPolicyPlan($$parsedSource as Partial<FlatPolicyPlan>);
    }
}

export class Manager {
    "ecosystem": string;
    "tool": string;
    "manifest": string;
    "commands": Command[];

    /** Creates a new Manager instance. */
    constructor($$source: Partial<Manager> = {}) {
        if (!("ecosystem" in $$source)) {
            this["ecosystem"] = "";
        }
        if (!("tool" in $$source)) {
            this["tool"] = "";
        }
        if (!("manifest" in $$source)) {
            this["manifest"] = "";
        }
        if (!("commands" in $$source)) {
            this["commands"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Manager instance from a string or object.
     */
    static createFrom($$source: any = {}): Manager {
        const $$createField3_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("commands" in $$parsedSource) {
            $$parsedSource["commands"] = $$createField3_0($$parsedSource["commands"]);
        }
        return new Manager($$parsedSource as Partial<Manager>);
    }
}

export enum Mode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ModeManual = "manual",
    ModeSafeAuto = "safe-auto",
    ModeFullAuto = "full-auto",
};

export enum MutationRisk {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RiskLow = "low",
    RiskMedium = "medium",
    RiskHigh = "high",
};

export enum OutcomeStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OutcomeCompleted = "completed",
    OutcomeFailed = "failed",
    OutcomeBlocked = "blocked",
    OutcomeUnavailable = "unavailable",
    OutcomePlanned = "planned",
};

export class Plan {
    "projectPath": string;
    "mode": Mode;
    "managers": Manager[];

    /** Creates a new Plan instance. */
    constructor($$source: Partial<Plan> = {}) {
        if (!("projectPath" in $$source)) {
            this["projectPath"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = Mode.$zero;
        }
        if (!("managers" in $$source)) {
            this["managers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Plan instance from a string or object.
     */
    static createFrom($$source: any = {}): Plan {
        const $$createField2_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("managers" in $$parsedSource) {
            $$parsedSource["managers"] = $$createField2_0($$parsedSource["managers"]);
        }
        return new Plan($$parsedSource as Partial<Plan>);
    }
}

export class Policy {
    "consentMode": ConsentMode;
    "autoApproveLowRisk": boolean;

    /** Creates a new Policy instance. */
    constructor($$source: Partial<Policy> = {}) {
        if (!("consentMode" in $$source)) {
            this["consentMode"] = ConsentMode.$zero;
        }
        if (!("autoApproveLowRisk" in $$source)) {
            this["autoApproveLowRisk"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Policy instance from a string or object.
     */
    static createFrom($$source: any = {}): Policy {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Policy($$parsedSource as Partial<Policy>);
    }
}

export class PolicyPlan {
    "projectPath": string;
    "policy": Policy;
    "runnableActions": ActionDescriptor[];
    "unavailableActions": ActionDescriptor[];
    "discoveryWarnings"?: string[];
    "discoveryIncomplete": boolean;

    /** Creates a new PolicyPlan instance. */
    constructor($$source: Partial<PolicyPlan> = {}) {
        if (!("projectPath" in $$source)) {
            this["projectPath"] = "";
        }
        if (!("policy" in $$source)) {
            this["policy"] = (new Policy());
        }
        if (!("runnableActions" in $$source)) {
            this["runnableActions"] = [];
        }
        if (!("unavailableActions" in $$source)) {
            this["unavailableActions"] = [];
        }
        if (!("discoveryIncomplete" in $$source)) {
            this["discoveryIncomplete"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PolicyPlan instance from a string or object.
     */
    static createFrom($$source: any = {}): PolicyPlan {
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType12;
        const $$createField3_0 = $$createType12;
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("policy" in $$parsedSource) {
            $$parsedSource["policy"] = $$createField1_0($$parsedSource["policy"]);
        }
        if ("runnableActions" in $$parsedSource) {
            $$parsedSource["runnableActions"] = $$createField2_0($$parsedSource["runnableActions"]);
        }
        if ("unavailableActions" in $$parsedSource) {
            $$parsedSource["unavailableActions"] = $$createField3_0($$parsedSource["unavailableActions"]);
        }
        if ("discoveryWarnings" in $$parsedSource) {
            $$parsedSource["discoveryWarnings"] = $$createField4_0($$parsedSource["discoveryWarnings"]);
        }
        return new PolicyPlan($$parsedSource as Partial<PolicyPlan>);
    }
}

export class PolicyPlanRequest {
    "policy": Policy;

    /** Creates a new PolicyPlanRequest instance. */
    constructor($$source: Partial<PolicyPlanRequest> = {}) {
        if (!("policy" in $$source)) {
            this["policy"] = (new Policy());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PolicyPlanRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): PolicyPlanRequest {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("policy" in $$parsedSource) {
            $$parsedSource["policy"] = $$createField0_0($$parsedSource["policy"]);
        }
        return new PolicyPlanRequest($$parsedSource as Partial<PolicyPlanRequest>);
    }
}

// Private type creation functions
const $$createType0 = Action.createFrom;
const $$createType1 = Policy.createFrom;
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = ActionOutcome.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = $Create.Array($$createType0);
const $$createType7 = Command.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = Manager.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = ActionDescriptor.createFrom;
const $$createType12 = $Create.Array($$createType11);
