// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as providers$0 from "./providers/models.js";

export class AIAgentProfileDescriptor {
    "id": string;
    "name": string;
    "description": string;
    "builtIn": boolean;
    "enabled": boolean;
    "toolKinds"?: AIToolKind[];

    /** Creates a new AIAgentProfileDescriptor instance. */
    constructor($$source: Partial<AIAgentProfileDescriptor> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("builtIn" in $$source)) {
            this["builtIn"] = false;
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIAgentProfileDescriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): AIAgentProfileDescriptor {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("toolKinds" in $$parsedSource) {
            $$parsedSource["toolKinds"] = $$createField5_0($$parsedSource["toolKinds"]);
        }
        return new AIAgentProfileDescriptor($$parsedSource as Partial<AIAgentProfileDescriptor>);
    }
}

export enum AIApprovalHardDeny {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AIApprovalHardDenySecrets = "secrets",
    AIApprovalHardDenySensitivePaths = "sensitive_paths",
    AIApprovalHardDenyNonLoopbackNetwork = "non_loopback_network",
    AIApprovalHardDenyFrontierCloudEgress = "frontier_cloud_egress",
    AIApprovalHardDenyDestructiveShell = "destructive_shell_commands",
    AIApprovalHardDenyOutsideProjectWrite = "outside_project_writes",
};

export enum AIApprovalMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AIApprovalModeAskEachTime = "ask_each_time",
    AIApprovalModeReadOnlyAllowed = "read_only_allowed",
    AIApprovalModeFullAccess = "full_access",
};

export class AIApprovalPolicy {
    "mode": AIApprovalMode;
    "scope": AIApprovalScope;
    "projectSessionId"?: string;
    "projectPathHash"?: string;
    "expiresAt"?: string;
    "grantedAt"?: string;
    "grantedBy"?: string;
    "revokedAt"?: string;
    "allowedToolKinds": AIToolKind[];
    "hardDenyCategories": AIApprovalHardDeny[];
    "updatedAt"?: string;

    /** Creates a new AIApprovalPolicy instance. */
    constructor($$source: Partial<AIApprovalPolicy> = {}) {
        if (!("mode" in $$source)) {
            this["mode"] = AIApprovalMode.$zero;
        }
        if (!("scope" in $$source)) {
            this["scope"] = (new AIApprovalScope());
        }
        if (!("allowedToolKinds" in $$source)) {
            this["allowedToolKinds"] = [];
        }
        if (!("hardDenyCategories" in $$source)) {
            this["hardDenyCategories"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIApprovalPolicy instance from a string or object.
     */
    static createFrom($$source: any = {}): AIApprovalPolicy {
        const $$createField1_0 = $$createType1;
        const $$createField8_0 = $$createType0;
        const $$createField9_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("scope" in $$parsedSource) {
            $$parsedSource["scope"] = $$createField1_0($$parsedSource["scope"]);
        }
        if ("allowedToolKinds" in $$parsedSource) {
            $$parsedSource["allowedToolKinds"] = $$createField8_0($$parsedSource["allowedToolKinds"]);
        }
        if ("hardDenyCategories" in $$parsedSource) {
            $$parsedSource["hardDenyCategories"] = $$createField9_0($$parsedSource["hardDenyCategories"]);
        }
        return new AIApprovalPolicy($$parsedSource as Partial<AIApprovalPolicy>);
    }
}

export class AIApprovalScope {
    "projectSessionId"?: string;
    "projectPathHash"?: string;

    /** Creates a new AIApprovalScope instance. */
    constructor($$source: Partial<AIApprovalScope> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIApprovalScope instance from a string or object.
     */
    static createFrom($$source: any = {}): AIApprovalScope {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIApprovalScope($$parsedSource as Partial<AIApprovalScope>);
    }
}

export class AIApprovalSummary {
    "mode": AIApprovalMode;
    "fullAccessActive": boolean;
    "projectSessionId"?: string;
    "projectPathHash"?: string;
    "expiresAt"?: string;
    "revokedAt"?: string;
    "allowedToolKinds": AIToolKind[];
    "hardDenyCategories": AIApprovalHardDeny[];

    /** Creates a new AIApprovalSummary instance. */
    constructor($$source: Partial<AIApprovalSummary> = {}) {
        if (!("mode" in $$source)) {
            this["mode"] = AIApprovalMode.$zero;
        }
        if (!("fullAccessActive" in $$source)) {
            this["fullAccessActive"] = false;
        }
        if (!("allowedToolKinds" in $$source)) {
            this["allowedToolKinds"] = [];
        }
        if (!("hardDenyCategories" in $$source)) {
            this["hardDenyCategories"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIApprovalSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): AIApprovalSummary {
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("allowedToolKinds" in $$parsedSource) {
            $$parsedSource["allowedToolKinds"] = $$createField6_0($$parsedSource["allowedToolKinds"]);
        }
        if ("hardDenyCategories" in $$parsedSource) {
            $$parsedSource["hardDenyCategories"] = $$createField7_0($$parsedSource["hardDenyCategories"]);
        }
        return new AIApprovalSummary($$parsedSource as Partial<AIApprovalSummary>);
    }
}

export enum AIChatAction {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AIChatActionDebug = "debug",
    AIChatActionPlan = "plan",
    AIChatActionBuild = "build",
};

export class AIChatActionDescriptor {
    "id": AIChatAction;
    "name": string;
    "description": string;
    "builtIn": boolean;
    "mayProposeTools": boolean;
    "expectsToolProposals": boolean;
    "readOnlyIntent": boolean;
    "showPlanStructure": boolean;
    "executionUnavailable": boolean;

    /** Creates a new AIChatActionDescriptor instance. */
    constructor($$source: Partial<AIChatActionDescriptor> = {}) {
        if (!("id" in $$source)) {
            this["id"] = AIChatAction.$zero;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("builtIn" in $$source)) {
            this["builtIn"] = false;
        }
        if (!("mayProposeTools" in $$source)) {
            this["mayProposeTools"] = false;
        }
        if (!("expectsToolProposals" in $$source)) {
            this["expectsToolProposals"] = false;
        }
        if (!("readOnlyIntent" in $$source)) {
            this["readOnlyIntent"] = false;
        }
        if (!("showPlanStructure" in $$source)) {
            this["showPlanStructure"] = false;
        }
        if (!("executionUnavailable" in $$source)) {
            this["executionUnavailable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIChatActionDescriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): AIChatActionDescriptor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIChatActionDescriptor($$parsedSource as Partial<AIChatActionDescriptor>);
    }
}

export class AIChatRun {
    "id": string;
    "sessionId": string;
    "projectSessionId"?: string;
    "action": AIChatAction;
    "status": string;
    "providerId"?: string;
    "model"?: string;
    "userPrompt"?: string;
    "response"?: string;
    "error"?: string;
    "contextSummary"?: AIContextSummary | null;
    "toolProposals"?: AIToolProposal[];
    "egressRecordId"?: string;
    "mnemonicRequested": boolean;
    "canCancel": boolean;
    "createdAt": string;
    "updatedAt": string;

    /** Creates a new AIChatRun instance. */
    constructor($$source: Partial<AIChatRun> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = AIChatAction.$zero;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("mnemonicRequested" in $$source)) {
            this["mnemonicRequested"] = false;
        }
        if (!("canCancel" in $$source)) {
            this["canCancel"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIChatRun instance from a string or object.
     */
    static createFrom($$source: any = {}): AIChatRun {
        const $$createField10_0 = $$createType4;
        const $$createField11_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("contextSummary" in $$parsedSource) {
            $$parsedSource["contextSummary"] = $$createField10_0($$parsedSource["contextSummary"]);
        }
        if ("toolProposals" in $$parsedSource) {
            $$parsedSource["toolProposals"] = $$createField11_0($$parsedSource["toolProposals"]);
        }
        return new AIChatRun($$parsedSource as Partial<AIChatRun>);
    }
}

export class AIChatRunEnvelope {
    "id": string;
    "sessionId": string;
    "projectSessionId"?: string;
    "action": AIChatAction;
    "status": string;
    "providerId"?: string;
    "model"?: string;
    "error"?: string;
    "canCancel": boolean;
    "contextSummary"?: AIContextSummary | null;
    "providerEnvelope"?: AIProviderEnvelope | null;
    "egressSummary"?: AIEgressSummary | null;
    "disclosureSummary": AIContextDisclosureSummary;
    "approvalSummary": AIApprovalSummary;
    "consentSummary": AIConsentSummary;
    "toolProposals"?: AIToolProposal[];
    "toolProposalSummary": AIToolProposalSummary;
    "mnemonicInclusion": AIMnemonicInclusionSummary;
    "createdAt": string;
    "updatedAt": string;

    /** Creates a new AIChatRunEnvelope instance. */
    constructor($$source: Partial<AIChatRunEnvelope> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = AIChatAction.$zero;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("canCancel" in $$source)) {
            this["canCancel"] = false;
        }
        if (!("disclosureSummary" in $$source)) {
            this["disclosureSummary"] = (new AIContextDisclosureSummary());
        }
        if (!("approvalSummary" in $$source)) {
            this["approvalSummary"] = (new AIApprovalSummary());
        }
        if (!("consentSummary" in $$source)) {
            this["consentSummary"] = (new AIConsentSummary());
        }
        if (!("toolProposalSummary" in $$source)) {
            this["toolProposalSummary"] = (new AIToolProposalSummary());
        }
        if (!("mnemonicInclusion" in $$source)) {
            this["mnemonicInclusion"] = (new AIMnemonicInclusionSummary());
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIChatRunEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): AIChatRunEnvelope {
        const $$createField9_0 = $$createType4;
        const $$createField10_0 = $$createType8;
        const $$createField11_0 = $$createType10;
        const $$createField12_0 = $$createType11;
        const $$createField13_0 = $$createType12;
        const $$createField14_0 = $$createType13;
        const $$createField15_0 = $$createType6;
        const $$createField16_0 = $$createType14;
        const $$createField17_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("contextSummary" in $$parsedSource) {
            $$parsedSource["contextSummary"] = $$createField9_0($$parsedSource["contextSummary"]);
        }
        if ("providerEnvelope" in $$parsedSource) {
            $$parsedSource["providerEnvelope"] = $$createField10_0($$parsedSource["providerEnvelope"]);
        }
        if ("egressSummary" in $$parsedSource) {
            $$parsedSource["egressSummary"] = $$createField11_0($$parsedSource["egressSummary"]);
        }
        if ("disclosureSummary" in $$parsedSource) {
            $$parsedSource["disclosureSummary"] = $$createField12_0($$parsedSource["disclosureSummary"]);
        }
        if ("approvalSummary" in $$parsedSource) {
            $$parsedSource["approvalSummary"] = $$createField13_0($$parsedSource["approvalSummary"]);
        }
        if ("consentSummary" in $$parsedSource) {
            $$parsedSource["consentSummary"] = $$createField14_0($$parsedSource["consentSummary"]);
        }
        if ("toolProposals" in $$parsedSource) {
            $$parsedSource["toolProposals"] = $$createField15_0($$parsedSource["toolProposals"]);
        }
        if ("toolProposalSummary" in $$parsedSource) {
            $$parsedSource["toolProposalSummary"] = $$createField16_0($$parsedSource["toolProposalSummary"]);
        }
        if ("mnemonicInclusion" in $$parsedSource) {
            $$parsedSource["mnemonicInclusion"] = $$createField17_0($$parsedSource["mnemonicInclusion"]);
        }
        return new AIChatRunEnvelope($$parsedSource as Partial<AIChatRunEnvelope>);
    }
}

export class AIChatRunRequest {
    "sessionId"?: string;
    "action": AIChatAction;
    "prompt": string;
    "providerId"?: string;
    "model"?: string;
    "includeMnemonic": boolean;
    "includeMCP": boolean;
    "includeSkills": boolean;
    "maxTokens"?: number;
    "context"?: AIContextRequest;

    /** Creates a new AIChatRunRequest instance. */
    constructor($$source: Partial<AIChatRunRequest> = {}) {
        if (!("action" in $$source)) {
            this["action"] = AIChatAction.$zero;
        }
        if (!("prompt" in $$source)) {
            this["prompt"] = "";
        }
        if (!("includeMnemonic" in $$source)) {
            this["includeMnemonic"] = false;
        }
        if (!("includeMCP" in $$source)) {
            this["includeMCP"] = false;
        }
        if (!("includeSkills" in $$source)) {
            this["includeSkills"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIChatRunRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): AIChatRunRequest {
        const $$createField9_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("context" in $$parsedSource) {
            $$parsedSource["context"] = $$createField9_0($$parsedSource["context"]);
        }
        return new AIChatRunRequest($$parsedSource as Partial<AIChatRunRequest>);
    }
}

export class AIConsentPolicy {
    "localProvidersAccepted": boolean;
    "remoteProvidersAccepted": boolean;
    "frontierProvidersAccepted": boolean;
    "providerPolicies"?: AIProviderDataPolicy[];
    "acceptedAt"?: string;
    "updatedAt"?: string;

    /** Creates a new AIConsentPolicy instance. */
    constructor($$source: Partial<AIConsentPolicy> = {}) {
        if (!("localProvidersAccepted" in $$source)) {
            this["localProvidersAccepted"] = false;
        }
        if (!("remoteProvidersAccepted" in $$source)) {
            this["remoteProvidersAccepted"] = false;
        }
        if (!("frontierProvidersAccepted" in $$source)) {
            this["frontierProvidersAccepted"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConsentPolicy instance from a string or object.
     */
    static createFrom($$source: any = {}): AIConsentPolicy {
        const $$createField3_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("providerPolicies" in $$parsedSource) {
            $$parsedSource["providerPolicies"] = $$createField3_0($$parsedSource["providerPolicies"]);
        }
        return new AIConsentPolicy($$parsedSource as Partial<AIConsentPolicy>);
    }
}

export class AIConsentSummary {
    "localProvidersAccepted": boolean;
    "remoteProvidersAccepted": boolean;
    "frontierProvidersAccepted": boolean;
    "policySource": string;

    /** Creates a new AIConsentSummary instance. */
    constructor($$source: Partial<AIConsentSummary> = {}) {
        if (!("localProvidersAccepted" in $$source)) {
            this["localProvidersAccepted"] = false;
        }
        if (!("remoteProvidersAccepted" in $$source)) {
            this["remoteProvidersAccepted"] = false;
        }
        if (!("frontierProvidersAccepted" in $$source)) {
            this["frontierProvidersAccepted"] = false;
        }
        if (!("policySource" in $$source)) {
            this["policySource"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIConsentSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): AIConsentSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIConsentSummary($$parsedSource as Partial<AIConsentSummary>);
    }
}

export class AIContextDisclosure {
    "providerId"?: string;
    "providerKind"?: string;
    "endpoint"?: string;
    "model"?: string;
    "capability"?: AIProviderCapability;
    "optInSource"?: string;
    "dataCategories"?: string[];
    "redaction": AIRedactionSummary;

    /** Creates a new AIContextDisclosure instance. */
    constructor($$source: Partial<AIContextDisclosure> = {}) {
        if (!("redaction" in $$source)) {
            this["redaction"] = (new AIRedactionSummary());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIContextDisclosure instance from a string or object.
     */
    static createFrom($$source: any = {}): AIContextDisclosure {
        const $$createField6_0 = $$createType19;
        const $$createField7_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dataCategories" in $$parsedSource) {
            $$parsedSource["dataCategories"] = $$createField6_0($$parsedSource["dataCategories"]);
        }
        if ("redaction" in $$parsedSource) {
            $$parsedSource["redaction"] = $$createField7_0($$parsedSource["redaction"]);
        }
        return new AIContextDisclosure($$parsedSource as Partial<AIContextDisclosure>);
    }
}

export class AIContextDisclosureSummary {
    "providerId"?: string;
    "providerKind"?: string;
    "endpointClass"?: string;
    "model"?: string;
    "local": boolean;
    "frontier": boolean;
    "providerPolicyAllowed": boolean;
    "optInSource"?: string;
    "retentionSummary"?: string;
    "dataCategories"?: string[];

    /** Creates a new AIContextDisclosureSummary instance. */
    constructor($$source: Partial<AIContextDisclosureSummary> = {}) {
        if (!("local" in $$source)) {
            this["local"] = false;
        }
        if (!("frontier" in $$source)) {
            this["frontier"] = false;
        }
        if (!("providerPolicyAllowed" in $$source)) {
            this["providerPolicyAllowed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIContextDisclosureSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): AIContextDisclosureSummary {
        const $$createField9_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dataCategories" in $$parsedSource) {
            $$parsedSource["dataCategories"] = $$createField9_0($$parsedSource["dataCategories"]);
        }
        return new AIContextDisclosureSummary($$parsedSource as Partial<AIContextDisclosureSummary>);
    }
}

export class AIContextProviderDescriptor {
    "id": string;
    "name": string;
    "description": string;
    "capability"?: AIProviderCapability;
    "enabled": boolean;
    "available": boolean;
    "localOnly": boolean;

    /** Creates a new AIContextProviderDescriptor instance. */
    constructor($$source: Partial<AIContextProviderDescriptor> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("localOnly" in $$source)) {
            this["localOnly"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIContextProviderDescriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): AIContextProviderDescriptor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIContextProviderDescriptor($$parsedSource as Partial<AIContextProviderDescriptor>);
    }
}

export class AIContextRequest {
    "requestId"?: string;
    "documentVersion"?: string;
    "capability": AIProviderCapability;
    "prompt"?: string;
    "filePath"?: string;
    "language"?: string;
    "line"?: number;
    "column"?: number;
    "lineText"?: string;
    "textBefore"?: string;
    "textAfter"?: string;
    "fullText"?: string;
    "selection"?: string;
    "terminalInput"?: string;
    "terminalWorkDir"?: string;
    "includeMnemonic": boolean;
    "includeMCP": boolean;
    "includeSkills": boolean;
    "maxBytes"?: number;
    "maxSnippets"?: number;

    /** Creates a new AIContextRequest instance. */
    constructor($$source: Partial<AIContextRequest> = {}) {
        if (!("capability" in $$source)) {
            this["capability"] = providers$0.AIProviderCapability.$zero;
        }
        if (!("includeMnemonic" in $$source)) {
            this["includeMnemonic"] = false;
        }
        if (!("includeMCP" in $$source)) {
            this["includeMCP"] = false;
        }
        if (!("includeSkills" in $$source)) {
            this["includeSkills"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIContextRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): AIContextRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIContextRequest($$parsedSource as Partial<AIContextRequest>);
    }
}

export class AIContextSnapshot {
    "id": string;
    "requestId"?: string;
    "documentVersion"?: string;
    "capability": AIProviderCapability;
    "projectPathHash"?: string;
    "projectSessionId"?: string;
    "filePath"?: string;
    "language"?: string;
    "line"?: number;
    "column"?: number;
    "prompt"?: string;
    "terminalInput"?: string;
    "terminalWorkDir"?: string;
    "snippets": AIContextSnippet[];
    "snippetBreakdown"?: AIContextSnippetBreakdown[];
    "mcpContext"?: AIMCPContextPlane | null;
    "mnemonic"?: AIMnemonicEntry[];
    "skills"?: AISkillContext[];
    "dataCategories": string[];
    "redaction": AIRedactionSummary;
    "providerEnvelope"?: AIProviderEnvelope | null;
    "disclosure": AIContextDisclosure;
    "disclosureSummary": AIContextDisclosureSummary;
    "approvalSummary": AIApprovalSummary;
    "byteSize": number;
    "createdAt": string;

    /** Creates a new AIContextSnapshot instance. */
    constructor($$source: Partial<AIContextSnapshot> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("capability" in $$source)) {
            this["capability"] = providers$0.AIProviderCapability.$zero;
        }
        if (!("snippets" in $$source)) {
            this["snippets"] = [];
        }
        if (!("dataCategories" in $$source)) {
            this["dataCategories"] = [];
        }
        if (!("redaction" in $$source)) {
            this["redaction"] = (new AIRedactionSummary());
        }
        if (!("disclosure" in $$source)) {
            this["disclosure"] = (new AIContextDisclosure());
        }
        if (!("disclosureSummary" in $$source)) {
            this["disclosureSummary"] = (new AIContextDisclosureSummary());
        }
        if (!("approvalSummary" in $$source)) {
            this["approvalSummary"] = (new AIApprovalSummary());
        }
        if (!("byteSize" in $$source)) {
            this["byteSize"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIContextSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): AIContextSnapshot {
        const $$createField13_0 = $$createType22;
        const $$createField14_0 = $$createType24;
        const $$createField15_0 = $$createType26;
        const $$createField16_0 = $$createType28;
        const $$createField17_0 = $$createType30;
        const $$createField18_0 = $$createType19;
        const $$createField19_0 = $$createType20;
        const $$createField20_0 = $$createType8;
        const $$createField21_0 = $$createType31;
        const $$createField22_0 = $$createType11;
        const $$createField23_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("snippets" in $$parsedSource) {
            $$parsedSource["snippets"] = $$createField13_0($$parsedSource["snippets"]);
        }
        if ("snippetBreakdown" in $$parsedSource) {
            $$parsedSource["snippetBreakdown"] = $$createField14_0($$parsedSource["snippetBreakdown"]);
        }
        if ("mcpContext" in $$parsedSource) {
            $$parsedSource["mcpContext"] = $$createField15_0($$parsedSource["mcpContext"]);
        }
        if ("mnemonic" in $$parsedSource) {
            $$parsedSource["mnemonic"] = $$createField16_0($$parsedSource["mnemonic"]);
        }
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField17_0($$parsedSource["skills"]);
        }
        if ("dataCategories" in $$parsedSource) {
            $$parsedSource["dataCategories"] = $$createField18_0($$parsedSource["dataCategories"]);
        }
        if ("redaction" in $$parsedSource) {
            $$parsedSource["redaction"] = $$createField19_0($$parsedSource["redaction"]);
        }
        if ("providerEnvelope" in $$parsedSource) {
            $$parsedSource["providerEnvelope"] = $$createField20_0($$parsedSource["providerEnvelope"]);
        }
        if ("disclosure" in $$parsedSource) {
            $$parsedSource["disclosure"] = $$createField21_0($$parsedSource["disclosure"]);
        }
        if ("disclosureSummary" in $$parsedSource) {
            $$parsedSource["disclosureSummary"] = $$createField22_0($$parsedSource["disclosureSummary"]);
        }
        if ("approvalSummary" in $$parsedSource) {
            $$parsedSource["approvalSummary"] = $$createField23_0($$parsedSource["approvalSummary"]);
        }
        return new AIContextSnapshot($$parsedSource as Partial<AIContextSnapshot>);
    }
}

export class AIContextSnippet {
    "type": string;
    "path"?: string;
    "language"?: string;
    "content": string;

    /** Creates a new AIContextSnippet instance. */
    constructor($$source: Partial<AIContextSnippet> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIContextSnippet instance from a string or object.
     */
    static createFrom($$source: any = {}): AIContextSnippet {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIContextSnippet($$parsedSource as Partial<AIContextSnippet>);
    }
}

export class AIContextSnippetBreakdown {
    "type": string;
    "count": number;
    "bytes": number;

    /** Creates a new AIContextSnippetBreakdown instance. */
    constructor($$source: Partial<AIContextSnippetBreakdown> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIContextSnippetBreakdown instance from a string or object.
     */
    static createFrom($$source: any = {}): AIContextSnippetBreakdown {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIContextSnippetBreakdown($$parsedSource as Partial<AIContextSnippetBreakdown>);
    }
}

export class AIContextSummary {
    "id": string;
    "requestId"?: string;
    "documentVersion"?: string;
    "capability": AIProviderCapability;
    "projectSessionId"?: string;
    "filePath"?: string;
    "language"?: string;
    "snippetCount": number;
    "mnemonicCount": number;
    "skillCount": number;
    "mcpIncluded": boolean;
    "mcpContext"?: AIMCPContextPlane | null;
    "snippetBreakdown"?: AIContextSnippetBreakdown[];
    "dataCategories": string[];
    "redaction": AIRedactionSummary;
    "disclosureSummary": AIContextDisclosureSummary;
    "byteSize": number;
    "createdAt": string;

    /** Creates a new AIContextSummary instance. */
    constructor($$source: Partial<AIContextSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("capability" in $$source)) {
            this["capability"] = providers$0.AIProviderCapability.$zero;
        }
        if (!("snippetCount" in $$source)) {
            this["snippetCount"] = 0;
        }
        if (!("mnemonicCount" in $$source)) {
            this["mnemonicCount"] = 0;
        }
        if (!("skillCount" in $$source)) {
            this["skillCount"] = 0;
        }
        if (!("mcpIncluded" in $$source)) {
            this["mcpIncluded"] = false;
        }
        if (!("dataCategories" in $$source)) {
            this["dataCategories"] = [];
        }
        if (!("redaction" in $$source)) {
            this["redaction"] = (new AIRedactionSummary());
        }
        if (!("disclosureSummary" in $$source)) {
            this["disclosureSummary"] = (new AIContextDisclosureSummary());
        }
        if (!("byteSize" in $$source)) {
            this["byteSize"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIContextSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): AIContextSummary {
        const $$createField11_0 = $$createType26;
        const $$createField12_0 = $$createType24;
        const $$createField13_0 = $$createType19;
        const $$createField14_0 = $$createType20;
        const $$createField15_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("mcpContext" in $$parsedSource) {
            $$parsedSource["mcpContext"] = $$createField11_0($$parsedSource["mcpContext"]);
        }
        if ("snippetBreakdown" in $$parsedSource) {
            $$parsedSource["snippetBreakdown"] = $$createField12_0($$parsedSource["snippetBreakdown"]);
        }
        if ("dataCategories" in $$parsedSource) {
            $$parsedSource["dataCategories"] = $$createField13_0($$parsedSource["dataCategories"]);
        }
        if ("redaction" in $$parsedSource) {
            $$parsedSource["redaction"] = $$createField14_0($$parsedSource["redaction"]);
        }
        if ("disclosureSummary" in $$parsedSource) {
            $$parsedSource["disclosureSummary"] = $$createField15_0($$parsedSource["disclosureSummary"]);
        }
        return new AIContextSummary($$parsedSource as Partial<AIContextSummary>);
    }
}

export class AIContinuationResponse {
    "requestId"?: string;
    "documentVersion"?: string;
    "text": string;
    "providerId"?: string;
    "model"?: string;
    "context": AIContextSnapshot;
    "egress"?: AIEgressRecord | null;

    /** Creates a new AIContinuationResponse instance. */
    constructor($$source: Partial<AIContinuationResponse> = {}) {
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("context" in $$source)) {
            this["context"] = (new AIContextSnapshot());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIContinuationResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): AIContinuationResponse {
        const $$createField5_0 = $$createType32;
        const $$createField6_0 = $$createType34;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("context" in $$parsedSource) {
            $$parsedSource["context"] = $$createField5_0($$parsedSource["context"]);
        }
        if ("egress" in $$parsedSource) {
            $$parsedSource["egress"] = $$createField6_0($$parsedSource["egress"]);
        }
        return new AIContinuationResponse($$parsedSource as Partial<AIContinuationResponse>);
    }
}

export class AIDiscoveryResult {
    "providers": AIProviderDescriptor[];
    "checkedAt": string;

    /** Creates a new AIDiscoveryResult instance. */
    constructor($$source: Partial<AIDiscoveryResult> = {}) {
        if (!("providers" in $$source)) {
            this["providers"] = [];
        }
        if (!("checkedAt" in $$source)) {
            this["checkedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIDiscoveryResult instance from a string or object.
     */
    static createFrom($$source: any = {}): AIDiscoveryResult {
        const $$createField0_0 = $$createType36;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("providers" in $$parsedSource) {
            $$parsedSource["providers"] = $$createField0_0($$parsedSource["providers"]);
        }
        return new AIDiscoveryResult($$parsedSource as Partial<AIDiscoveryResult>);
    }
}

export class AIEgressRecord {
    "id": string;
    "requestId": string;
    "providerId": string;
    "providerKind": string;
    "endpoint"?: string;
    "model"?: string;
    "capability": AIProviderCapability;
    "projectPathHash"?: string;
    "projectSessionId"?: string;
    "dataCategories": string[];
    "redaction": AIRedactionSummary;
    "status": string;
    "latencyMs"?: number;
    "errorClass"?: string;
    "optInSource"?: string;
    "canceled": boolean;
    "createdAt": string;
    "runId"?: string;
    "source"?: string;
    "chatAction"?: AIChatAction;

    /** Creates a new AIEgressRecord instance. */
    constructor($$source: Partial<AIEgressRecord> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("requestId" in $$source)) {
            this["requestId"] = "";
        }
        if (!("providerId" in $$source)) {
            this["providerId"] = "";
        }
        if (!("providerKind" in $$source)) {
            this["providerKind"] = "";
        }
        if (!("capability" in $$source)) {
            this["capability"] = providers$0.AIProviderCapability.$zero;
        }
        if (!("dataCategories" in $$source)) {
            this["dataCategories"] = [];
        }
        if (!("redaction" in $$source)) {
            this["redaction"] = (new AIRedactionSummary());
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("canceled" in $$source)) {
            this["canceled"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIEgressRecord instance from a string or object.
     */
    static createFrom($$source: any = {}): AIEgressRecord {
        const $$createField9_0 = $$createType19;
        const $$createField10_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dataCategories" in $$parsedSource) {
            $$parsedSource["dataCategories"] = $$createField9_0($$parsedSource["dataCategories"]);
        }
        if ("redaction" in $$parsedSource) {
            $$parsedSource["redaction"] = $$createField10_0($$parsedSource["redaction"]);
        }
        return new AIEgressRecord($$parsedSource as Partial<AIEgressRecord>);
    }
}

export class AIEgressSummary {
    "recordId"?: string;
    "status"?: string;
    "providerId"?: string;
    "providerKind"?: string;
    "endpoint"?: string;
    "model"?: string;
    "capability"?: AIProviderCapability;
    "dataCategories"?: string[];
    "redaction": AIRedactionSummary;
    "latencyMs"?: number;
    "canceled": boolean;
    "errorClass"?: string;
    "createdAt"?: string;
    "runId"?: string;
    "source"?: string;
    "chatAction"?: AIChatAction;

    /** Creates a new AIEgressSummary instance. */
    constructor($$source: Partial<AIEgressSummary> = {}) {
        if (!("redaction" in $$source)) {
            this["redaction"] = (new AIRedactionSummary());
        }
        if (!("canceled" in $$source)) {
            this["canceled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIEgressSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): AIEgressSummary {
        const $$createField7_0 = $$createType19;
        const $$createField8_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dataCategories" in $$parsedSource) {
            $$parsedSource["dataCategories"] = $$createField7_0($$parsedSource["dataCategories"]);
        }
        if ("redaction" in $$parsedSource) {
            $$parsedSource["redaction"] = $$createField8_0($$parsedSource["redaction"]);
        }
        return new AIEgressSummary($$parsedSource as Partial<AIEgressSummary>);
    }
}

export class AIEmbeddingProviderDescriptor {
    "id": string;
    "name": string;
    "local": boolean;
    "available": boolean;
    "reason"?: string;

    /** Creates a new AIEmbeddingProviderDescriptor instance. */
    constructor($$source: Partial<AIEmbeddingProviderDescriptor> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("local" in $$source)) {
            this["local"] = false;
        }
        if (!("available" in $$source)) {
            this["available"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIEmbeddingProviderDescriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): AIEmbeddingProviderDescriptor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIEmbeddingProviderDescriptor($$parsedSource as Partial<AIEmbeddingProviderDescriptor>);
    }
}

export class AIEmbeddingStatus {
    "status": string;
    "reason": string;
    "providers": AIEmbeddingProviderDescriptor[];
    "updatedAt": string;

    /** Creates a new AIEmbeddingStatus instance. */
    constructor($$source: Partial<AIEmbeddingStatus> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }
        if (!("providers" in $$source)) {
            this["providers"] = [];
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIEmbeddingStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): AIEmbeddingStatus {
        const $$createField2_0 = $$createType38;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("providers" in $$parsedSource) {
            $$parsedSource["providers"] = $$createField2_0($$parsedSource["providers"]);
        }
        return new AIEmbeddingStatus($$parsedSource as Partial<AIEmbeddingStatus>);
    }
}

export class AIMCPContextPlane {
    "enabled": boolean;
    "available": boolean;
    "bridgeRunning": boolean;
    "bridgeAvailable": boolean;
    "toolCount": number;
    "enabledToolCount": number;
    "disabledToolCount": number;
    "toolGroups"?: AIMCPToolGroupSummary[];
    "memoryBackend"?: string;
    "memoryContextPath"?: string;
    "mnemonicSharedContext": boolean;
    "executionState": string;
    "approvalSummary"?: string;
    "dataCategories"?: string[];
    "redactionSummary"?: string;
    "updatedAt": string;

    /** Creates a new AIMCPContextPlane instance. */
    constructor($$source: Partial<AIMCPContextPlane> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("bridgeRunning" in $$source)) {
            this["bridgeRunning"] = false;
        }
        if (!("bridgeAvailable" in $$source)) {
            this["bridgeAvailable"] = false;
        }
        if (!("toolCount" in $$source)) {
            this["toolCount"] = 0;
        }
        if (!("enabledToolCount" in $$source)) {
            this["enabledToolCount"] = 0;
        }
        if (!("disabledToolCount" in $$source)) {
            this["disabledToolCount"] = 0;
        }
        if (!("mnemonicSharedContext" in $$source)) {
            this["mnemonicSharedContext"] = false;
        }
        if (!("executionState" in $$source)) {
            this["executionState"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIMCPContextPlane instance from a string or object.
     */
    static createFrom($$source: any = {}): AIMCPContextPlane {
        const $$createField7_0 = $$createType40;
        const $$createField13_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("toolGroups" in $$parsedSource) {
            $$parsedSource["toolGroups"] = $$createField7_0($$parsedSource["toolGroups"]);
        }
        if ("dataCategories" in $$parsedSource) {
            $$parsedSource["dataCategories"] = $$createField13_0($$parsedSource["dataCategories"]);
        }
        return new AIMCPContextPlane($$parsedSource as Partial<AIMCPContextPlane>);
    }
}

export class AIMCPToolGroupSummary {
    "name": string;
    "total": number;
    "enabled": number;
    "disabled": number;

    /** Creates a new AIMCPToolGroupSummary instance. */
    constructor($$source: Partial<AIMCPToolGroupSummary> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = 0;
        }
        if (!("disabled" in $$source)) {
            this["disabled"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIMCPToolGroupSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): AIMCPToolGroupSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIMCPToolGroupSummary($$parsedSource as Partial<AIMCPToolGroupSummary>);
    }
}

export class AIMnemonicEntry {
    "id": string;
    "type": string;
    "source"?: string;
    "tags"?: string[];
    "content": string;
    "importance": number;
    "confidence": number;
    "trust"?: string;
    "originKind"?: string;
    "generated": boolean;
    "superseded": boolean;
    "pinned": boolean;
    "isLatest": boolean;
    "decay": number;
    "lastAccessedAt"?: string;
    "accessCount": number;
    "provenance"?: { [_ in string]?: string };
    "relationships"?: AIMnemonicRelationship[];
    "createdAt": string;
    "updatedAt"?: string;

    /** Creates a new AIMnemonicEntry instance. */
    constructor($$source: Partial<AIMnemonicEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("importance" in $$source)) {
            this["importance"] = 0;
        }
        if (!("confidence" in $$source)) {
            this["confidence"] = 0;
        }
        if (!("generated" in $$source)) {
            this["generated"] = false;
        }
        if (!("superseded" in $$source)) {
            this["superseded"] = false;
        }
        if (!("pinned" in $$source)) {
            this["pinned"] = false;
        }
        if (!("isLatest" in $$source)) {
            this["isLatest"] = false;
        }
        if (!("decay" in $$source)) {
            this["decay"] = 0;
        }
        if (!("accessCount" in $$source)) {
            this["accessCount"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIMnemonicEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): AIMnemonicEntry {
        const $$createField3_0 = $$createType19;
        const $$createField16_0 = $$createType41;
        const $$createField17_0 = $$createType43;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField3_0($$parsedSource["tags"]);
        }
        if ("provenance" in $$parsedSource) {
            $$parsedSource["provenance"] = $$createField16_0($$parsedSource["provenance"]);
        }
        if ("relationships" in $$parsedSource) {
            $$parsedSource["relationships"] = $$createField17_0($$parsedSource["relationships"]);
        }
        return new AIMnemonicEntry($$parsedSource as Partial<AIMnemonicEntry>);
    }
}

export class AIMnemonicEntryInput {
    "id"?: string;
    "type"?: string;
    "source"?: string;
    "tags"?: string[];
    "content": string;
    "importance"?: number;
    "confidence"?: number;
    "trust"?: string;
    "pinned": boolean;
    "isLatest": boolean;
    "decay"?: number;
    "provenance"?: { [_ in string]?: string };
    "relationships"?: AIMnemonicRelationship[];

    /** Creates a new AIMnemonicEntryInput instance. */
    constructor($$source: Partial<AIMnemonicEntryInput> = {}) {
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("pinned" in $$source)) {
            this["pinned"] = false;
        }
        if (!("isLatest" in $$source)) {
            this["isLatest"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIMnemonicEntryInput instance from a string or object.
     */
    static createFrom($$source: any = {}): AIMnemonicEntryInput {
        const $$createField3_0 = $$createType19;
        const $$createField11_0 = $$createType41;
        const $$createField12_0 = $$createType43;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField3_0($$parsedSource["tags"]);
        }
        if ("provenance" in $$parsedSource) {
            $$parsedSource["provenance"] = $$createField11_0($$parsedSource["provenance"]);
        }
        if ("relationships" in $$parsedSource) {
            $$parsedSource["relationships"] = $$createField12_0($$parsedSource["relationships"]);
        }
        return new AIMnemonicEntryInput($$parsedSource as Partial<AIMnemonicEntryInput>);
    }
}

export class AIMnemonicEntryPatch {
    "type"?: string;
    "source"?: string;
    "tags"?: string[];
    "content"?: string;
    "importance"?: number | null;
    "confidence"?: number | null;
    "trust"?: string;
    "pinned"?: boolean | null;
    "isLatest"?: boolean | null;
    "decay"?: number | null;
    "provenance"?: { [_ in string]?: string };
    "relationships"?: AIMnemonicRelationship[];

    /** Creates a new AIMnemonicEntryPatch instance. */
    constructor($$source: Partial<AIMnemonicEntryPatch> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIMnemonicEntryPatch instance from a string or object.
     */
    static createFrom($$source: any = {}): AIMnemonicEntryPatch {
        const $$createField2_0 = $$createType19;
        const $$createField10_0 = $$createType41;
        const $$createField11_0 = $$createType43;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField2_0($$parsedSource["tags"]);
        }
        if ("provenance" in $$parsedSource) {
            $$parsedSource["provenance"] = $$createField10_0($$parsedSource["provenance"]);
        }
        if ("relationships" in $$parsedSource) {
            $$parsedSource["relationships"] = $$createField11_0($$parsedSource["relationships"]);
        }
        return new AIMnemonicEntryPatch($$parsedSource as Partial<AIMnemonicEntryPatch>);
    }
}

export class AIMnemonicInclusionSummary {
    "requested": boolean;
    "enabled": boolean;
    "included": boolean;
    "count": number;
    "trusts"?: string[];

    /** Creates a new AIMnemonicInclusionSummary instance. */
    constructor($$source: Partial<AIMnemonicInclusionSummary> = {}) {
        if (!("requested" in $$source)) {
            this["requested"] = false;
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("included" in $$source)) {
            this["included"] = false;
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIMnemonicInclusionSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): AIMnemonicInclusionSummary {
        const $$createField4_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("trusts" in $$parsedSource) {
            $$parsedSource["trusts"] = $$createField4_0($$parsedSource["trusts"]);
        }
        return new AIMnemonicInclusionSummary($$parsedSource as Partial<AIMnemonicInclusionSummary>);
    }
}

export class AIMnemonicRelationship {
    "id"?: string;
    "fromId": string;
    "toId": string;
    "type": string;
    "createdAt"?: string;

    /** Creates a new AIMnemonicRelationship instance. */
    constructor($$source: Partial<AIMnemonicRelationship> = {}) {
        if (!("fromId" in $$source)) {
            this["fromId"] = "";
        }
        if (!("toId" in $$source)) {
            this["toId"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIMnemonicRelationship instance from a string or object.
     */
    static createFrom($$source: any = {}): AIMnemonicRelationship {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIMnemonicRelationship($$parsedSource as Partial<AIMnemonicRelationship>);
    }
}

export class AIMnemonicSearchRequest {
    "query"?: string;
    "tags"?: string[];
    "limit"?: number;
    "includeUntrusted": boolean;
    "includeGenerated": boolean;
    "includeSuperseded": boolean;

    /** Creates a new AIMnemonicSearchRequest instance. */
    constructor($$source: Partial<AIMnemonicSearchRequest> = {}) {
        if (!("includeUntrusted" in $$source)) {
            this["includeUntrusted"] = false;
        }
        if (!("includeGenerated" in $$source)) {
            this["includeGenerated"] = false;
        }
        if (!("includeSuperseded" in $$source)) {
            this["includeSuperseded"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIMnemonicSearchRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): AIMnemonicSearchRequest {
        const $$createField1_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField1_0($$parsedSource["tags"]);
        }
        return new AIMnemonicSearchRequest($$parsedSource as Partial<AIMnemonicSearchRequest>);
    }
}

export class AIPromptWorkflowDescriptor {
    "id": string;
    "name": string;
    "slash"?: string;
    "action": AIChatAction;
    "description": string;
    "builtIn": boolean;

    /** Creates a new AIPromptWorkflowDescriptor instance. */
    constructor($$source: Partial<AIPromptWorkflowDescriptor> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = AIChatAction.$zero;
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("builtIn" in $$source)) {
            this["builtIn"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIPromptWorkflowDescriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): AIPromptWorkflowDescriptor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIPromptWorkflowDescriptor($$parsedSource as Partial<AIPromptWorkflowDescriptor>);
    }
}

export type AIProviderCapability = providers$0.AIProviderCapability;

export class AIProviderDataPolicy {
    "providerId"?: string;
    "providerKind"?: string;
    "endpoint"?: string;
    "model"?: string;
    "local": boolean;
    "frontier": boolean;
    "allowed": boolean;
    "dataCategories"?: string[];
    "retentionSummary"?: string;
    "updatedAt"?: string;

    /** Creates a new AIProviderDataPolicy instance. */
    constructor($$source: Partial<AIProviderDataPolicy> = {}) {
        if (!("local" in $$source)) {
            this["local"] = false;
        }
        if (!("frontier" in $$source)) {
            this["frontier"] = false;
        }
        if (!("allowed" in $$source)) {
            this["allowed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIProviderDataPolicy instance from a string or object.
     */
    static createFrom($$source: any = {}): AIProviderDataPolicy {
        const $$createField7_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dataCategories" in $$parsedSource) {
            $$parsedSource["dataCategories"] = $$createField7_0($$parsedSource["dataCategories"]);
        }
        return new AIProviderDataPolicy($$parsedSource as Partial<AIProviderDataPolicy>);
    }
}

export const AIProviderDescriptor = providers$0.AIProviderDescriptor;
export type AIProviderDescriptor = providers$0.AIProviderDescriptor;

export class AIProviderEnvelope {
    "providerId"?: string;
    "kind"?: string;
    "endpoint"?: string;
    "model"?: string;
    "status"?: AIProviderStatusValue;
    "local": boolean;
    "frontier": boolean;

    /** Creates a new AIProviderEnvelope instance. */
    constructor($$source: Partial<AIProviderEnvelope> = {}) {
        if (!("local" in $$source)) {
            this["local"] = false;
        }
        if (!("frontier" in $$source)) {
            this["frontier"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIProviderEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): AIProviderEnvelope {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIProviderEnvelope($$parsedSource as Partial<AIProviderEnvelope>);
    }
}

export const AIProviderSettings = providers$0.AIProviderSettings;
export type AIProviderSettings = providers$0.AIProviderSettings;

export type AIProviderStatusValue = providers$0.AIProviderStatusValue;

export class AIRedactionSummary {
    "secretsRedacted": number;
    "pathsRedacted": number;
    "truncated": boolean;
    "originalBytes": number;
    "sanitizedBytes": number;
    "blockedCategories"?: string[];
    "appliedRules"?: string[];

    /** Creates a new AIRedactionSummary instance. */
    constructor($$source: Partial<AIRedactionSummary> = {}) {
        if (!("secretsRedacted" in $$source)) {
            this["secretsRedacted"] = 0;
        }
        if (!("pathsRedacted" in $$source)) {
            this["pathsRedacted"] = 0;
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }
        if (!("originalBytes" in $$source)) {
            this["originalBytes"] = 0;
        }
        if (!("sanitizedBytes" in $$source)) {
            this["sanitizedBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIRedactionSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): AIRedactionSummary {
        const $$createField5_0 = $$createType19;
        const $$createField6_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("blockedCategories" in $$parsedSource) {
            $$parsedSource["blockedCategories"] = $$createField5_0($$parsedSource["blockedCategories"]);
        }
        if ("appliedRules" in $$parsedSource) {
            $$parsedSource["appliedRules"] = $$createField6_0($$parsedSource["appliedRules"]);
        }
        return new AIRedactionSummary($$parsedSource as Partial<AIRedactionSummary>);
    }
}

export class AISkillContext {
    "skillId": string;
    "name": string;
    "description"?: string;
    "sourceKind": string;
    "trustState": string;
    "state"?: string;
    "contentHash"?: string;
    "digestVersion": number;
    "summary": string;
    "activationRules"?: string[];
    "operatingReminders"?: string[];
    "avoidRules"?: string[];
    "toolHints"?: string[];
    "verificationHints"?: string[];
    "resourcesIndex"?: string[];
    "topicMatch"?: string;
    "confidence"?: number;
    "activatedAt"?: string;
    "lastUsedAt"?: string;
    "decayDeadline"?: string;

    /** Creates a new AISkillContext instance. */
    constructor($$source: Partial<AISkillContext> = {}) {
        if (!("skillId" in $$source)) {
            this["skillId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("sourceKind" in $$source)) {
            this["sourceKind"] = "";
        }
        if (!("trustState" in $$source)) {
            this["trustState"] = "";
        }
        if (!("digestVersion" in $$source)) {
            this["digestVersion"] = 0;
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AISkillContext instance from a string or object.
     */
    static createFrom($$source: any = {}): AISkillContext {
        const $$createField9_0 = $$createType19;
        const $$createField10_0 = $$createType19;
        const $$createField11_0 = $$createType19;
        const $$createField12_0 = $$createType19;
        const $$createField13_0 = $$createType19;
        const $$createField14_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("activationRules" in $$parsedSource) {
            $$parsedSource["activationRules"] = $$createField9_0($$parsedSource["activationRules"]);
        }
        if ("operatingReminders" in $$parsedSource) {
            $$parsedSource["operatingReminders"] = $$createField10_0($$parsedSource["operatingReminders"]);
        }
        if ("avoidRules" in $$parsedSource) {
            $$parsedSource["avoidRules"] = $$createField11_0($$parsedSource["avoidRules"]);
        }
        if ("toolHints" in $$parsedSource) {
            $$parsedSource["toolHints"] = $$createField12_0($$parsedSource["toolHints"]);
        }
        if ("verificationHints" in $$parsedSource) {
            $$parsedSource["verificationHints"] = $$createField13_0($$parsedSource["verificationHints"]);
        }
        if ("resourcesIndex" in $$parsedSource) {
            $$parsedSource["resourcesIndex"] = $$createField14_0($$parsedSource["resourcesIndex"]);
        }
        return new AISkillContext($$parsedSource as Partial<AISkillContext>);
    }
}

export class AIStatus {
    "enabled": boolean;
    "mnemonicEnabled": boolean;
    "providers": AIProviderDescriptor[];
    "activeProviderId"?: string;
    "activeModel"?: string;
    "settingsConfigured": boolean;
    "projectPathHash"?: string;
    "projectSessionId"?: string;

    /** Creates a new AIStatus instance. */
    constructor($$source: Partial<AIStatus> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("mnemonicEnabled" in $$source)) {
            this["mnemonicEnabled"] = false;
        }
        if (!("providers" in $$source)) {
            this["providers"] = [];
        }
        if (!("settingsConfigured" in $$source)) {
            this["settingsConfigured"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): AIStatus {
        const $$createField2_0 = $$createType36;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("providers" in $$parsedSource) {
            $$parsedSource["providers"] = $$createField2_0($$parsedSource["providers"]);
        }
        return new AIStatus($$parsedSource as Partial<AIStatus>);
    }
}

export enum AIToolExecutionState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AIToolExecutionStateNotExecutable = "not_executable_in_this_slice",
};

export enum AIToolHardDenyReason {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AIToolHardDenyReasonSecrets = "secrets",
    AIToolHardDenyReasonSensitivePaths = "sensitive_paths",
    AIToolHardDenyReasonNonLoopbackNetwork = "non_loopback_network",
    AIToolHardDenyReasonFrontierCloudEgress = "frontier_cloud_egress",
    AIToolHardDenyReasonDestructiveShell = "destructive_shell_commands",
    AIToolHardDenyReasonOutsideProjectWrite = "outside_project_writes",
};

export enum AIToolKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AIToolKindContextRead = "context_read",
    AIToolKindFileWrite = "file_write",
    AIToolKindTerminal = "terminal",
    AIToolKindMCP = "mcp",
    AIToolKindSubagent = "subagent",
    AIToolKindNetworkLocal = "network_local",
};

export enum AIToolPolicy {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AIToolPolicyReadOnly = "read_only_context",
    AIToolPolicyProposalOnly = "tool_proposal_only",
    AIToolPolicyApprovalRequired = "approval_required",
};

export class AIToolProposal {
    "id": string;
    "name": string;
    "description": string;
    "policy": AIToolPolicy;
    "arguments"?: { [_ in string]?: string };
    "kind": AIToolKind;
    "scopeSummary"?: string;
    "riskLevel": AIToolRiskLevel;
    "targetPaths"?: string[];
    "commandPreview"?: string;
    "mcpToolName"?: string;
    "approvalModeRequired": AIApprovalMode;
    "allowedByCurrentPolicy": boolean;
    "hardDenyReason"?: AIToolHardDenyReason;
    "approvalToken"?: string;
    "status": AIToolProposalStatus;
    "executionState": AIToolExecutionState;

    /** Creates a new AIToolProposal instance. */
    constructor($$source: Partial<AIToolProposal> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("policy" in $$source)) {
            this["policy"] = AIToolPolicy.$zero;
        }
        if (!("kind" in $$source)) {
            this["kind"] = AIToolKind.$zero;
        }
        if (!("riskLevel" in $$source)) {
            this["riskLevel"] = AIToolRiskLevel.$zero;
        }
        if (!("approvalModeRequired" in $$source)) {
            this["approvalModeRequired"] = AIApprovalMode.$zero;
        }
        if (!("allowedByCurrentPolicy" in $$source)) {
            this["allowedByCurrentPolicy"] = false;
        }
        if (!("status" in $$source)) {
            this["status"] = AIToolProposalStatus.$zero;
        }
        if (!("executionState" in $$source)) {
            this["executionState"] = AIToolExecutionState.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIToolProposal instance from a string or object.
     */
    static createFrom($$source: any = {}): AIToolProposal {
        const $$createField4_0 = $$createType41;
        const $$createField8_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("arguments" in $$parsedSource) {
            $$parsedSource["arguments"] = $$createField4_0($$parsedSource["arguments"]);
        }
        if ("targetPaths" in $$parsedSource) {
            $$parsedSource["targetPaths"] = $$createField8_0($$parsedSource["targetPaths"]);
        }
        return new AIToolProposal($$parsedSource as Partial<AIToolProposal>);
    }
}

export enum AIToolProposalStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AIToolProposalStatusProposed = "proposed",
    AIToolProposalStatusBlocked = "blocked",
};

export class AIToolProposalSummary {
    "total": number;
    "allowedByPolicy": number;
    "hardDenied": number;
    "notExecutableInSlice": number;

    /** Creates a new AIToolProposalSummary instance. */
    constructor($$source: Partial<AIToolProposalSummary> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("allowedByPolicy" in $$source)) {
            this["allowedByPolicy"] = 0;
        }
        if (!("hardDenied" in $$source)) {
            this["hardDenied"] = 0;
        }
        if (!("notExecutableInSlice" in $$source)) {
            this["notExecutableInSlice"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIToolProposalSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): AIToolProposalSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIToolProposalSummary($$parsedSource as Partial<AIToolProposalSummary>);
    }
}

export enum AIToolRiskLevel {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AIToolRiskLow = "low",
    AIToolRiskMedium = "medium",
    AIToolRiskHigh = "high",
    AIToolRiskHardDeny = "hard_deny",
};

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = AIApprovalScope.createFrom;
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = AIContextSummary.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = AIToolProposal.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = AIProviderEnvelope.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = AIEgressSummary.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = AIContextDisclosureSummary.createFrom;
const $$createType12 = AIApprovalSummary.createFrom;
const $$createType13 = AIConsentSummary.createFrom;
const $$createType14 = AIToolProposalSummary.createFrom;
const $$createType15 = AIMnemonicInclusionSummary.createFrom;
const $$createType16 = AIContextRequest.createFrom;
const $$createType17 = AIProviderDataPolicy.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = $Create.Array($Create.Any);
const $$createType20 = AIRedactionSummary.createFrom;
const $$createType21 = AIContextSnippet.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = AIContextSnippetBreakdown.createFrom;
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = AIMCPContextPlane.createFrom;
const $$createType26 = $Create.Nullable($$createType25);
const $$createType27 = AIMnemonicEntry.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = AISkillContext.createFrom;
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = AIContextDisclosure.createFrom;
const $$createType32 = AIContextSnapshot.createFrom;
const $$createType33 = AIEgressRecord.createFrom;
const $$createType34 = $Create.Nullable($$createType33);
const $$createType35 = providers$0.AIProviderDescriptor.createFrom;
const $$createType36 = $Create.Array($$createType35);
const $$createType37 = AIEmbeddingProviderDescriptor.createFrom;
const $$createType38 = $Create.Array($$createType37);
const $$createType39 = AIMCPToolGroupSummary.createFrom;
const $$createType40 = $Create.Array($$createType39);
const $$createType41 = $Create.Map($Create.Any, $Create.Any);
const $$createType42 = AIMnemonicRelationship.createFrom;
const $$createType43 = $Create.Array($$createType42);
