// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

export class CacheOptions {
    "ExcludeGroups": string[];
    "IncludeGroups": string[];

    /** Creates a new CacheOptions instance. */
    constructor($$source: Partial<CacheOptions> = {}) {
        if (!("ExcludeGroups" in $$source)) {
            this["ExcludeGroups"] = [];
        }
        if (!("IncludeGroups" in $$source)) {
            this["IncludeGroups"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CacheOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): CacheOptions {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ExcludeGroups" in $$parsedSource) {
            $$parsedSource["ExcludeGroups"] = $$createField0_0($$parsedSource["ExcludeGroups"]);
        }
        if ("IncludeGroups" in $$parsedSource) {
            $$parsedSource["IncludeGroups"] = $$createField1_0($$parsedSource["IncludeGroups"]);
        }
        return new CacheOptions($$parsedSource as Partial<CacheOptions>);
    }
}

export class MigrateOptions {
    "Force": boolean;
    "Step": number;
    "Path": string;
    "Realpath": boolean;

    /** Creates a new MigrateOptions instance. */
    constructor($$source: Partial<MigrateOptions> = {}) {
        if (!("Force" in $$source)) {
            this["Force"] = false;
        }
        if (!("Step" in $$source)) {
            this["Step"] = 0;
        }
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Realpath" in $$source)) {
            this["Realpath"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MigrateOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): MigrateOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MigrateOptions($$parsedSource as Partial<MigrateOptions>);
    }
}

export class MigrateRefreshOptions {
    "Seed": boolean;
    "Step": number;
    "Path": string;
    "Realpath": boolean;

    /** Creates a new MigrateRefreshOptions instance. */
    constructor($$source: Partial<MigrateRefreshOptions> = {}) {
        if (!("Seed" in $$source)) {
            this["Seed"] = false;
        }
        if (!("Step" in $$source)) {
            this["Step"] = 0;
        }
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Realpath" in $$source)) {
            this["Realpath"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MigrateRefreshOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): MigrateRefreshOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MigrateRefreshOptions($$parsedSource as Partial<MigrateRefreshOptions>);
    }
}

export class MigrateResetOptions {
    "Path": string;
    "Realpath": boolean;

    /** Creates a new MigrateResetOptions instance. */
    constructor($$source: Partial<MigrateResetOptions> = {}) {
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Realpath" in $$source)) {
            this["Realpath"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MigrateResetOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): MigrateResetOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MigrateResetOptions($$parsedSource as Partial<MigrateResetOptions>);
    }
}

export class MigrateRollbackOptions {
    "Step": number;
    "Paths": string[];
    "Realpath": boolean;

    /** Creates a new MigrateRollbackOptions instance. */
    constructor($$source: Partial<MigrateRollbackOptions> = {}) {
        if (!("Step" in $$source)) {
            this["Step"] = 0;
        }
        if (!("Paths" in $$source)) {
            this["Paths"] = [];
        }
        if (!("Realpath" in $$source)) {
            this["Realpath"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MigrateRollbackOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): MigrateRollbackOptions {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Paths" in $$parsedSource) {
            $$parsedSource["Paths"] = $$createField1_0($$parsedSource["Paths"]);
        }
        return new MigrateRollbackOptions($$parsedSource as Partial<MigrateRollbackOptions>);
    }
}

export class ServeOptions {
    "Host": string;
    "Port": string;
    "Env": string;
    "ForceHttps": boolean;

    /** Creates a new ServeOptions instance. */
    constructor($$source: Partial<ServeOptions> = {}) {
        if (!("Host" in $$source)) {
            this["Host"] = "";
        }
        if (!("Port" in $$source)) {
            this["Port"] = "";
        }
        if (!("Env" in $$source)) {
            this["Env"] = "";
        }
        if (!("ForceHttps" in $$source)) {
            this["ForceHttps"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServeOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): ServeOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServeOptions($$parsedSource as Partial<ServeOptions>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
