package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

type PatternFile struct {
	Version   string        `json:"version"`
	Name      string        `json:"name"`
	Language  string        `json:"language"`
	Framework string        `json:"framework"`
	Patterns  []JSONPattern `json:"patterns"`
}

type JSONPattern struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Language    string             `json:"language"`
	Framework   string             `json:"framework,omitempty"`
	Context     JSONPatternContext `json:"context"`
	Trigger     JSONPatternTrigger `json:"trigger"`
	Template    string             `json:"template,omitempty"`
	Generator   string             `json:"generator,omitempty"`
	Priority    int                `json:"priority"`
	Builtin     bool               `json:"builtin"`
	IsSkeleton  bool               `json:"isSkeleton,omitempty"`
	Variables   map[string]string  `json:"variables,omitempty"`
}

type JSONPatternContext struct {
	Languages  []string `json:"languages,omitempty"`
	Frameworks []string `json:"frameworks,omitempty"`
	FileTypes  []string `json:"fileTypes,omitempty"`
	Positions  []string `json:"positions,omitempty"`
	Extends    string   `json:"extends,omitempty"`
	Implements []string `json:"implements,omitempty"`
	HasTrait   string   `json:"hasTrait,omitempty"`
	InMethod   string   `json:"inMethod,omitempty"`
	AfterText  string   `json:"afterText,omitempty"`
	BeforeText string   `json:"beforeText,omitempty"`
}

type JSONPatternTrigger struct {
	Type  string `json:"type"`
	Value string `json:"value,omitempty"`
}

type GeneratedPattern struct {
	ID          string
	Name        string
	Description string
	Language    string
	Framework   string
	Context     GeneratedContext
	Trigger     GeneratedTrigger
	Template    string
	Generator   string
	Priority    int
	Variables   map[string]string
	Builtin     bool
	IsSkeleton  bool
}

type GeneratedContext struct {
	FileTypes  []string
	Positions  []string
	Languages  []string
	Frameworks []string
	Extends    string
	Implements []string
	HasTrait   string
	InMethod   string
	AfterText  string
	BeforeText string
}

type GeneratedTrigger struct {
	Type  string
	Value string
}

const codeTemplate = `// Code generated by patterngen. DO NOT EDIT.
//go:generate go run ../../cmd/patterngen/main.go

package predictive

var generatedPatterns = []Pattern{
{{- range .Patterns }}
	{
		ID:          {{ printf "%q" .ID }},
		Name:        {{ printf "%q" .Name }},
		Description: {{ printf "%q" .Description }},
		Language:    {{ printf "%q" .Language }},
		Framework:   {{ printf "%q" .Framework }},
		Context: PatternContext{
			{{- if .Context.FileTypes }}
			FileTypes: []string{ {{- range .Context.FileTypes }}{{ printf "%q" . }}, {{ end }}},
			{{- end }}
			{{- if .Context.Positions }}
			Positions: []string{ {{- range .Context.Positions }}{{ printf "%q" . }}, {{ end }}},
			{{- end }}
			{{- if .Context.Languages }}
			Languages: []string{ {{- range .Context.Languages }}{{ printf "%q" . }}, {{ end }}},
			{{- end }}
			{{- if .Context.Frameworks }}
			Frameworks: []string{ {{- range .Context.Frameworks }}{{ printf "%q" . }}, {{ end }}},
			{{- end }}
			{{- if .Context.Extends }}
			Extends: {{ printf "%q" .Context.Extends }},
			{{- end }}
			{{- if .Context.Implements }}
			Implements: []string{ {{- range .Context.Implements }}{{ printf "%q" . }}, {{ end }}},
			{{- end }}
			{{- if .Context.HasTrait }}
			HasTrait: {{ printf "%q" .Context.HasTrait }},
			{{- end }}
			{{- if .Context.InMethod }}
			InMethod: {{ printf "%q" .Context.InMethod }},
			{{- end }}
			{{- if .Context.AfterText }}
			AfterText: {{ printf "%q" .Context.AfterText }},
			{{- end }}
			{{- if .Context.BeforeText }}
			BeforeText: {{ printf "%q" .Context.BeforeText }},
			{{- end }}
		},
		Trigger: PatternTrigger{
			Type:  {{ .Trigger.Type }},
			{{- if .Trigger.Value }}
			Value: {{ printf "%q" .Trigger.Value }},
			{{- end }}
		},
		{{- if .Template }}
		Template: {{ printf "%q" .Template }},
		{{- end }}
		{{- if .Generator }}
		Generator: {{ printf "%q" .Generator }},
		{{- end }}
		Priority: {{ .Priority }},
		{{- if .Variables }}
		Variables: map[string]string{
			{{- range $key, $value := .Variables }}
			{{ printf "%q" $key }}: {{ printf "%q" $value }},
			{{- end }}
		},
		{{- end }}
		Builtin:    {{ .Builtin }},
		IsSkeleton: {{ .IsSkeleton }},
	},
{{- end }}
}
`

func main() {
	wd, err := os.Getwd()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error getting working directory: %v\n", err)
		os.Exit(1)
	}

	var patternsDir, outputFile string

	if filepath.Base(wd) == "predictive" || filepath.Base(wd) == "arlecchino" {
		patternsDir = "patterns"
		outputFile = "patterns_generated.go"
		if filepath.Base(wd) == "arlecchino" {
			patternsDir = "internal/predictive/patterns"
			outputFile = "internal/predictive/patterns_generated.go"
		}
	} else {
		patternsDir = "internal/predictive/patterns"
		outputFile = "internal/predictive/patterns_generated.go"
	}

	files, err := filepath.Glob(filepath.Join(patternsDir, "*.json"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error finding pattern files: %v\n", err)
		os.Exit(1)
	}

	sort.Strings(files)

	var allPatterns []GeneratedPattern

	for _, file := range files {
		patterns, err := loadPatternsFromFile(file)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error loading %s: %v\n", file, err)
			continue
		}
		allPatterns = append(allPatterns, patterns...)
	}

	fmt.Printf("Loaded %d patterns from %d files\n", len(allPatterns), len(files))

	if err := generateCode(allPatterns, outputFile); err != nil {
		fmt.Fprintf(os.Stderr, "Error generating code: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s with %d patterns\n", outputFile, len(allPatterns))
}

func loadPatternsFromFile(filePath string) ([]GeneratedPattern, error) {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return nil, fmt.Errorf("read file: %w", err)
	}

	var file PatternFile
	if err := json.Unmarshal(data, &file); err != nil {
		return nil, fmt.Errorf("parse JSON: %w", err)
	}

	patterns := make([]GeneratedPattern, 0, len(file.Patterns))

	for _, jp := range file.Patterns {
		lang := jp.Language
		if lang == "" {
			lang = file.Language
		}

		fw := jp.Framework
		if fw == "" {
			fw = file.Framework
		}

		pattern := GeneratedPattern{
			ID:          jp.ID,
			Name:        jp.Name,
			Description: jp.Description,
			Language:    lang,
			Framework:   fw,
			Template:    jp.Template,
			Generator:   jp.Generator,
			Priority:    jp.Priority,
			Builtin:     jp.Builtin,
			IsSkeleton:  jp.IsSkeleton,
			Variables:   jp.Variables,
			Context: GeneratedContext{
				FileTypes:  jp.Context.FileTypes,
				Positions:  jp.Context.Positions,
				Languages:  jp.Context.Languages,
				Frameworks: jp.Context.Frameworks,
				Extends:    jp.Context.Extends,
				Implements: jp.Context.Implements,
				HasTrait:   jp.Context.HasTrait,
				InMethod:   jp.Context.InMethod,
				AfterText:  jp.Context.AfterText,
				BeforeText: jp.Context.BeforeText,
			},
			Trigger: GeneratedTrigger{
				Type:  normalizeTriggerType(jp.Trigger.Type),
				Value: jp.Trigger.Value,
			},
		}

		patterns = append(patterns, pattern)
	}

	return patterns, nil
}

func normalizeTriggerType(t string) string {
	switch strings.ToLower(t) {
	case "empty":
		return "TriggerTypeEmpty"
	case "text":
		return "TriggerTypeText"
	case "regex":
		return "TriggerTypeRegex"
	case "newline":
		return "TriggerTypeNewLine"
	case "always":
		return "TriggerTypeAlways"
	case "prefix":
		return "TriggerTypePrefix"
	case "context":
		return "TriggerTypeContext"
	default:
		return "TriggerTypeAlways"
	}
}

func generateCode(patterns []GeneratedPattern, outputPath string) error {
	funcMap := template.FuncMap{
		"backtick": func(s string) string {
			return "`" + s + "`"
		},
	}

	tmpl, err := template.New("code").Funcs(funcMap).Parse(codeTemplate)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, map[string]interface{}{
		"Patterns": patterns,
	}); err != nil {
		return fmt.Errorf("execute template: %w", err)
	}

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		return fmt.Errorf("format code: %w", err)
	}

	if err := os.WriteFile(outputPath, formatted, 0644); err != nil {
		return fmt.Errorf("write file: %w", err)
	}

	return nil
}
