// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

export class SearchBackendStatus {
    "name": string;
    "ready": boolean;
    "indexed": boolean;
    "fallback": boolean;
    "message"?: string;
    "cachePath"?: string;

    /** Creates a new SearchBackendStatus instance. */
    constructor($$source: Partial<SearchBackendStatus> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("ready" in $$source)) {
            this["ready"] = false;
        }
        if (!("indexed" in $$source)) {
            this["indexed"] = false;
        }
        if (!("fallback" in $$source)) {
            this["fallback"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchBackendStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchBackendStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchBackendStatus($$parsedSource as Partial<SearchBackendStatus>);
    }
}
