// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as importcaps$0 from "./importcaps/models.js";

export class CapabilitySources {
    "syntax": boolean;
    "lspDeclared": boolean;
    "lspAvailable": boolean;
    "index": boolean;
    "local": boolean;
    "predictive": boolean;
    "imports": boolean;
    "importContext": boolean;
    "dependencyImports": boolean;
    "nativeAutoImport": boolean;
    "lspAutoImportEdits": boolean;
    "importEditNormalization": boolean;
    "stubs": boolean;
    "keywords": boolean;
    "fillAll": boolean;

    /** Creates a new CapabilitySources instance. */
    constructor($$source: Partial<CapabilitySources> = {}) {
        if (!("syntax" in $$source)) {
            this["syntax"] = false;
        }
        if (!("lspDeclared" in $$source)) {
            this["lspDeclared"] = false;
        }
        if (!("lspAvailable" in $$source)) {
            this["lspAvailable"] = false;
        }
        if (!("index" in $$source)) {
            this["index"] = false;
        }
        if (!("local" in $$source)) {
            this["local"] = false;
        }
        if (!("predictive" in $$source)) {
            this["predictive"] = false;
        }
        if (!("imports" in $$source)) {
            this["imports"] = false;
        }
        if (!("importContext" in $$source)) {
            this["importContext"] = false;
        }
        if (!("dependencyImports" in $$source)) {
            this["dependencyImports"] = false;
        }
        if (!("nativeAutoImport" in $$source)) {
            this["nativeAutoImport"] = false;
        }
        if (!("lspAutoImportEdits" in $$source)) {
            this["lspAutoImportEdits"] = false;
        }
        if (!("importEditNormalization" in $$source)) {
            this["importEditNormalization"] = false;
        }
        if (!("stubs" in $$source)) {
            this["stubs"] = false;
        }
        if (!("keywords" in $$source)) {
            this["keywords"] = false;
        }
        if (!("fillAll" in $$source)) {
            this["fillAll"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CapabilitySources instance from a string or object.
     */
    static createFrom($$source: any = {}): CapabilitySources {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CapabilitySources($$parsedSource as Partial<CapabilitySources>);
    }
}

export enum CapabilityTier {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TierNative = "native",
    TierHybrid = "hybrid",
    TierLSPOnly = "lsp-only",
    TierSyntaxOnly = "syntax-only",
    TierUnknown = "unknown",
};

export class LanguageCapability {
    "id": string;
    "name": string;
    "extensions": string[];
    "canonicalId": string;
    "tier": CapabilityTier;
    "autoImportLevel": importcaps$0.AutoImportLevel;
    "sources": CapabilitySources;
    "lspServerId": string;
    "lspInstalled": boolean;
    "lspCanInstall": boolean;
    "lspInstalling": boolean;
    "lspConfigured": boolean;
    "lspRunning": boolean;
    "lspBinaryPath": string;
    "lspInstallType": string;
    "lspInstallCommand": string;
    "lspInstallDependencies": string[];
    "lspInstallUnavailableReason": string;
    "lspInstallStage": string;
    "lspInstallPercent": number;
    "lspInstallMessage": string;
    "lspInstallError": string;
    "lspLastError": string;
    "notes": string[];

    /** Creates a new LanguageCapability instance. */
    constructor($$source: Partial<LanguageCapability> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("extensions" in $$source)) {
            this["extensions"] = [];
        }
        if (!("canonicalId" in $$source)) {
            this["canonicalId"] = "";
        }
        if (!("tier" in $$source)) {
            this["tier"] = CapabilityTier.$zero;
        }
        if (!("autoImportLevel" in $$source)) {
            this["autoImportLevel"] = importcaps$0.AutoImportLevel.$zero;
        }
        if (!("sources" in $$source)) {
            this["sources"] = (new CapabilitySources());
        }
        if (!("lspServerId" in $$source)) {
            this["lspServerId"] = "";
        }
        if (!("lspInstalled" in $$source)) {
            this["lspInstalled"] = false;
        }
        if (!("lspCanInstall" in $$source)) {
            this["lspCanInstall"] = false;
        }
        if (!("lspInstalling" in $$source)) {
            this["lspInstalling"] = false;
        }
        if (!("lspConfigured" in $$source)) {
            this["lspConfigured"] = false;
        }
        if (!("lspRunning" in $$source)) {
            this["lspRunning"] = false;
        }
        if (!("lspBinaryPath" in $$source)) {
            this["lspBinaryPath"] = "";
        }
        if (!("lspInstallType" in $$source)) {
            this["lspInstallType"] = "";
        }
        if (!("lspInstallCommand" in $$source)) {
            this["lspInstallCommand"] = "";
        }
        if (!("lspInstallDependencies" in $$source)) {
            this["lspInstallDependencies"] = [];
        }
        if (!("lspInstallUnavailableReason" in $$source)) {
            this["lspInstallUnavailableReason"] = "";
        }
        if (!("lspInstallStage" in $$source)) {
            this["lspInstallStage"] = "";
        }
        if (!("lspInstallPercent" in $$source)) {
            this["lspInstallPercent"] = 0;
        }
        if (!("lspInstallMessage" in $$source)) {
            this["lspInstallMessage"] = "";
        }
        if (!("lspInstallError" in $$source)) {
            this["lspInstallError"] = "";
        }
        if (!("lspLastError" in $$source)) {
            this["lspLastError"] = "";
        }
        if (!("notes" in $$source)) {
            this["notes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LanguageCapability instance from a string or object.
     */
    static createFrom($$source: any = {}): LanguageCapability {
        const $$createField2_0 = $$createType0;
        const $$createField6_0 = $$createType1;
        const $$createField16_0 = $$createType0;
        const $$createField23_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField2_0($$parsedSource["extensions"]);
        }
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField6_0($$parsedSource["sources"]);
        }
        if ("lspInstallDependencies" in $$parsedSource) {
            $$parsedSource["lspInstallDependencies"] = $$createField16_0($$parsedSource["lspInstallDependencies"]);
        }
        if ("notes" in $$parsedSource) {
            $$parsedSource["notes"] = $$createField23_0($$parsedSource["notes"]);
        }
        return new LanguageCapability($$parsedSource as Partial<LanguageCapability>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = CapabilitySources.createFrom;
