// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

export class CapabilitySources {
    "syntax": boolean;
    "lspDeclared": boolean;
    "lspAvailable": boolean;
    "index": boolean;
    "local": boolean;
    "predictive": boolean;
    "imports": boolean;
    "stubs": boolean;
    "keywords": boolean;
    "fillAll": boolean;

    /** Creates a new CapabilitySources instance. */
    constructor($$source: Partial<CapabilitySources> = {}) {
        if (!("syntax" in $$source)) {
            this["syntax"] = false;
        }
        if (!("lspDeclared" in $$source)) {
            this["lspDeclared"] = false;
        }
        if (!("lspAvailable" in $$source)) {
            this["lspAvailable"] = false;
        }
        if (!("index" in $$source)) {
            this["index"] = false;
        }
        if (!("local" in $$source)) {
            this["local"] = false;
        }
        if (!("predictive" in $$source)) {
            this["predictive"] = false;
        }
        if (!("imports" in $$source)) {
            this["imports"] = false;
        }
        if (!("stubs" in $$source)) {
            this["stubs"] = false;
        }
        if (!("keywords" in $$source)) {
            this["keywords"] = false;
        }
        if (!("fillAll" in $$source)) {
            this["fillAll"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CapabilitySources instance from a string or object.
     */
    static createFrom($$source: any = {}): CapabilitySources {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CapabilitySources($$parsedSource as Partial<CapabilitySources>);
    }
}

export enum CapabilityTier {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TierNative = "native",
    TierHybrid = "hybrid",
    TierLSPOnly = "lsp-only",
    TierSyntaxOnly = "syntax-only",
    TierUnknown = "unknown",
};

export class LanguageCapability {
    "id": string;
    "name": string;
    "extensions": string[];
    "canonicalId": string;
    "tier": CapabilityTier;
    "sources": CapabilitySources;
    "lspServerId": string;
    "notes": string[];

    /** Creates a new LanguageCapability instance. */
    constructor($$source: Partial<LanguageCapability> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("extensions" in $$source)) {
            this["extensions"] = [];
        }
        if (!("canonicalId" in $$source)) {
            this["canonicalId"] = "";
        }
        if (!("tier" in $$source)) {
            this["tier"] = CapabilityTier.$zero;
        }
        if (!("sources" in $$source)) {
            this["sources"] = (new CapabilitySources());
        }
        if (!("lspServerId" in $$source)) {
            this["lspServerId"] = "";
        }
        if (!("notes" in $$source)) {
            this["notes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LanguageCapability instance from a string or object.
     */
    static createFrom($$source: any = {}): LanguageCapability {
        const $$createField2_0 = $$createType0;
        const $$createField5_0 = $$createType1;
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField2_0($$parsedSource["extensions"]);
        }
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField5_0($$parsedSource["sources"]);
        }
        if ("notes" in $$parsedSource) {
            $$parsedSource["notes"] = $$createField7_0($$parsedSource["notes"]);
        }
        return new LanguageCapability($$parsedSource as Partial<LanguageCapability>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = CapabilitySources.createFrom;
