// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

/**
 * ServerStatus represents the health status of an LSP server
 */
export class ServerStatus {
    "Language": string;
    "Running": boolean;
    "ProcessAlive": boolean;
    "LastError": string;
    "Restarts": number;

    /** Creates a new ServerStatus instance. */
    constructor($$source: Partial<ServerStatus> = {}) {
        if (!("Language" in $$source)) {
            this["Language"] = "";
        }
        if (!("Running" in $$source)) {
            this["Running"] = false;
        }
        if (!("ProcessAlive" in $$source)) {
            this["ProcessAlive"] = false;
        }
        if (!("LastError" in $$source)) {
            this["LastError"] = "";
        }
        if (!("Restarts" in $$source)) {
            this["Restarts"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerStatus($$parsedSource as Partial<ServerStatus>);
    }
}
