// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

export class ToolStatus {
    "name": string;
    "available": boolean;
    "version": string;
    "installCmd": string;

    /** Creates a new ToolStatus instance. */
    constructor($$source: Partial<ToolStatus> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("installCmd" in $$source)) {
            this["installCmd"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolStatus($$parsedSource as Partial<ToolStatus>);
    }
}
