// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

export class InstallOptions {
    "Dev": boolean;
    "NoDev": boolean;
    "Optimize": boolean;
    "NoScripts": boolean;
    "Update": boolean;
    "IgnorePlatformReqs": boolean;

    /** Creates a new InstallOptions instance. */
    constructor($$source: Partial<InstallOptions> = {}) {
        if (!("Dev" in $$source)) {
            this["Dev"] = false;
        }
        if (!("NoDev" in $$source)) {
            this["NoDev"] = false;
        }
        if (!("Optimize" in $$source)) {
            this["Optimize"] = false;
        }
        if (!("NoScripts" in $$source)) {
            this["NoScripts"] = false;
        }
        if (!("Update" in $$source)) {
            this["Update"] = false;
        }
        if (!("IgnorePlatformReqs" in $$source)) {
            this["IgnorePlatformReqs"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstallOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): InstallOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InstallOptions($$parsedSource as Partial<InstallOptions>);
    }
}

export class RemoveOptions {
    "NoDev": boolean;
    "NoScripts": boolean;
    "Update": boolean;

    /** Creates a new RemoveOptions instance. */
    constructor($$source: Partial<RemoveOptions> = {}) {
        if (!("NoDev" in $$source)) {
            this["NoDev"] = false;
        }
        if (!("NoScripts" in $$source)) {
            this["NoScripts"] = false;
        }
        if (!("Update" in $$source)) {
            this["Update"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoveOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): RemoveOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RemoveOptions($$parsedSource as Partial<RemoveOptions>);
    }
}
