// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

export class ComponentOptions {
    "Force": boolean;
    "Plain": boolean;
    "Invokable": boolean;

    /** Creates a new ComponentOptions instance. */
    constructor($$source: Partial<ComponentOptions> = {}) {
        if (!("Force" in $$source)) {
            this["Force"] = false;
        }
        if (!("Plain" in $$source)) {
            this["Plain"] = false;
        }
        if (!("Invokable" in $$source)) {
            this["Invokable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ComponentOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): ComponentOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ComponentOptions($$parsedSource as Partial<ComponentOptions>);
    }
}

export class ControllerOptions {
    "Resource": boolean;
    "Api": boolean;
    "Plain": boolean;
    "Invokable": boolean;
    "Model": string;
    "Parent": string;
    "Singleton": boolean;
    "Requests": boolean;

    /** Creates a new ControllerOptions instance. */
    constructor($$source: Partial<ControllerOptions> = {}) {
        if (!("Resource" in $$source)) {
            this["Resource"] = false;
        }
        if (!("Api" in $$source)) {
            this["Api"] = false;
        }
        if (!("Plain" in $$source)) {
            this["Plain"] = false;
        }
        if (!("Invokable" in $$source)) {
            this["Invokable"] = false;
        }
        if (!("Model" in $$source)) {
            this["Model"] = "";
        }
        if (!("Parent" in $$source)) {
            this["Parent"] = "";
        }
        if (!("Singleton" in $$source)) {
            this["Singleton"] = false;
        }
        if (!("Requests" in $$source)) {
            this["Requests"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ControllerOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): ControllerOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ControllerOptions($$parsedSource as Partial<ControllerOptions>);
    }
}

export class EnumClassOptions {
    "Force": boolean;

    /** Creates a new EnumClassOptions instance. */
    constructor($$source: Partial<EnumClassOptions> = {}) {
        if (!("Force" in $$source)) {
            this["Force"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnumClassOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): EnumClassOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnumClassOptions($$parsedSource as Partial<EnumClassOptions>);
    }
}

export class EventClassOptions {
    "Force": boolean;

    /** Creates a new EventClassOptions instance. */
    constructor($$source: Partial<EventClassOptions> = {}) {
        if (!("Force" in $$source)) {
            this["Force"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EventClassOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): EventClassOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EventClassOptions($$parsedSource as Partial<EventClassOptions>);
    }
}

export class FactoryClassOptions {
    "Force": boolean;
    "Model": string;
    "Seeded": boolean;

    /** Creates a new FactoryClassOptions instance. */
    constructor($$source: Partial<FactoryClassOptions> = {}) {
        if (!("Force" in $$source)) {
            this["Force"] = false;
        }
        if (!("Model" in $$source)) {
            this["Model"] = "";
        }
        if (!("Seeded" in $$source)) {
            this["Seeded"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FactoryClassOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): FactoryClassOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FactoryClassOptions($$parsedSource as Partial<FactoryClassOptions>);
    }
}

export class JobOptions {
    "Sync": boolean;

    /** Creates a new JobOptions instance. */
    constructor($$source: Partial<JobOptions> = {}) {
        if (!("Sync" in $$source)) {
            this["Sync"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JobOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): JobOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new JobOptions($$parsedSource as Partial<JobOptions>);
    }
}

export class LivewireComponentOptions {
    "Force": boolean;
    "Inline": boolean;
    "Plain": boolean;
    "Invokable": boolean;
    "SkipViews": boolean;

    /** Creates a new LivewireComponentOptions instance. */
    constructor($$source: Partial<LivewireComponentOptions> = {}) {
        if (!("Force" in $$source)) {
            this["Force"] = false;
        }
        if (!("Inline" in $$source)) {
            this["Inline"] = false;
        }
        if (!("Plain" in $$source)) {
            this["Plain"] = false;
        }
        if (!("Invokable" in $$source)) {
            this["Invokable"] = false;
        }
        if (!("SkipViews" in $$source)) {
            this["SkipViews"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LivewireComponentOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): LivewireComponentOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LivewireComponentOptions($$parsedSource as Partial<LivewireComponentOptions>);
    }
}

export class MailOptions {
    "Markdown": string;

    /** Creates a new MailOptions instance. */
    constructor($$source: Partial<MailOptions> = {}) {
        if (!("Markdown" in $$source)) {
            this["Markdown"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MailOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): MailOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MailOptions($$parsedSource as Partial<MailOptions>);
    }
}

export class MigrationOptions {
    "Create": string;
    "Table": string;
    "Path": string;
    "Force": boolean;

    /** Creates a new MigrationOptions instance. */
    constructor($$source: Partial<MigrationOptions> = {}) {
        if (!("Create" in $$source)) {
            this["Create"] = "";
        }
        if (!("Table" in $$source)) {
            this["Table"] = "";
        }
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Force" in $$source)) {
            this["Force"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MigrationOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): MigrationOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MigrationOptions($$parsedSource as Partial<MigrationOptions>);
    }
}

export class ModelOptions {
    "All": boolean;
    "Controller": boolean;
    "Factory": boolean;
    "Invokable": boolean;
    "Migration": boolean;
    "Policy": boolean;
    "Resource": boolean;
    "Seeder": boolean;

    /** Creates a new ModelOptions instance. */
    constructor($$source: Partial<ModelOptions> = {}) {
        if (!("All" in $$source)) {
            this["All"] = false;
        }
        if (!("Controller" in $$source)) {
            this["Controller"] = false;
        }
        if (!("Factory" in $$source)) {
            this["Factory"] = false;
        }
        if (!("Invokable" in $$source)) {
            this["Invokable"] = false;
        }
        if (!("Migration" in $$source)) {
            this["Migration"] = false;
        }
        if (!("Policy" in $$source)) {
            this["Policy"] = false;
        }
        if (!("Resource" in $$source)) {
            this["Resource"] = false;
        }
        if (!("Seeder" in $$source)) {
            this["Seeder"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelOptions($$parsedSource as Partial<ModelOptions>);
    }
}

export class NotificationOptions {
    "Force": boolean;

    /** Creates a new NotificationOptions instance. */
    constructor($$source: Partial<NotificationOptions> = {}) {
        if (!("Force" in $$source)) {
            this["Force"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotificationOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): NotificationOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NotificationOptions($$parsedSource as Partial<NotificationOptions>);
    }
}

export class PolicyClassOptions {
    "Force": boolean;
    "Model": string;
    "Guard": string;
    "Resource": boolean;

    /** Creates a new PolicyClassOptions instance. */
    constructor($$source: Partial<PolicyClassOptions> = {}) {
        if (!("Force" in $$source)) {
            this["Force"] = false;
        }
        if (!("Model" in $$source)) {
            this["Model"] = "";
        }
        if (!("Guard" in $$source)) {
            this["Guard"] = "";
        }
        if (!("Resource" in $$source)) {
            this["Resource"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PolicyClassOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): PolicyClassOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PolicyClassOptions($$parsedSource as Partial<PolicyClassOptions>);
    }
}

export class ResourceClassOptions {
    "Collection": boolean;
    "Force": boolean;
    "Invokable": boolean;
    "Model": string;

    /** Creates a new ResourceClassOptions instance. */
    constructor($$source: Partial<ResourceClassOptions> = {}) {
        if (!("Collection" in $$source)) {
            this["Collection"] = false;
        }
        if (!("Force" in $$source)) {
            this["Force"] = false;
        }
        if (!("Invokable" in $$source)) {
            this["Invokable"] = false;
        }
        if (!("Model" in $$source)) {
            this["Model"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourceClassOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): ResourceClassOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResourceClassOptions($$parsedSource as Partial<ResourceClassOptions>);
    }
}

export class SeederClassOptions {
    "Force": boolean;
    "Class": string;

    /** Creates a new SeederClassOptions instance. */
    constructor($$source: Partial<SeederClassOptions> = {}) {
        if (!("Force" in $$source)) {
            this["Force"] = false;
        }
        if (!("Class" in $$source)) {
            this["Class"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SeederClassOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): SeederClassOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SeederClassOptions($$parsedSource as Partial<SeederClassOptions>);
    }
}
