package ai

import "arlecchino/internal/ai/providers"

func (s *Service) ListChatActions() []AIChatActionDescriptor {
	return []AIChatActionDescriptor{
		{
			ID:               AIChatActionAsk,
			Name:             "Chat",
			Description:      "Chat with visible project context when context is selected.",
			BuiltIn:          true,
			MayProposeTools:  true,
			ReadOnlyIntent:   true,
			MutationAllowed:  false,
			RequiresApproval: false,
			ToolKinds:        []AIToolKind{AIToolKindContextRead},
			ApprovalBoundary: "read-only context and inspection tools only",
		},
		{
			ID:                   AIChatActionDebug,
			Name:                 "Debug",
			Description:          "Investigate failures with diagnostic context, read-only evidence, and approval-gated terminal checks.",
			BuiltIn:              true,
			MayProposeTools:      true,
			ExpectsToolProposals: false,
			ReadOnlyIntent:       true,
			MutationAllowed:      false,
			RequiresApproval:     true,
			ToolKinds:            []AIToolKind{AIToolKindContextRead, AIToolKindTerminal},
			ApprovalBoundary:     "terminal execution requires visible approval and audit; file writes are unavailable",
		},
		{
			ID:                AIChatActionPlan,
			Name:              "Plan",
			Description:       "Inspect read-only context and produce a project-grounded implementation plan.",
			BuiltIn:           true,
			MayProposeTools:   true,
			ReadOnlyIntent:    true,
			ShowPlanStructure: true,
			MutationAllowed:   false,
			RequiresApproval:  false,
			ToolKinds:         []AIToolKind{AIToolKindContextRead},
			ApprovalBoundary:  "read-only planning",
		},
		{
			ID:                   AIChatActionBuild,
			Name:                 "Build",
			Description:          "Produce patch artifacts and explicit approval-gated tool calls.",
			BuiltIn:              true,
			MayProposeTools:      true,
			ExpectsToolProposals: false,
			ExecutionUnavailable: false,
			MutationAllowed:      true,
			RequiresApproval:     true,
			ToolKinds:            []AIToolKind{AIToolKindContextRead, AIToolKindFileWrite, AIToolKindTerminal, AIToolKindMCP},
			ApprovalBoundary:     "patch apply, terminal, and MCP actions require approval, checkpoint, and audit",
		},
		{
			ID:                   AIChatActionReview,
			Name:                 "Review",
			Description:          "Review changes and surface defects, risks, and missing verification without mutating files.",
			BuiltIn:              true,
			MayProposeTools:      true,
			ExpectsToolProposals: false,
			ReadOnlyIntent:       true,
			MutationAllowed:      false,
			RequiresApproval:     false,
			ToolKinds:            []AIToolKind{AIToolKindContextRead},
			ApprovalBoundary:     "read-only review",
		},
	}
}

func (s *Service) ListAgentProfiles() []AIAgentProfileDescriptor {
	return []AIAgentProfileDescriptor{
		{
			ID:          minimalChatProfileID,
			Name:        "Minimal Chat",
			Description: "General conversation profile with no implicit project context or tools.",
			BuiltIn:     true,
			Enabled:     true,
			Action:      AIChatActionAsk,
			ReadOnly:    true,
			Approval:    "none",
			ToolKinds:   []AIToolKind{},
		},
		{
			ID:          "ask-readonly",
			Name:        "Chat Readonly",
			Description: "Project-grounded chat profile with no mutation capability.",
			BuiltIn:     true,
			Enabled:     true,
			Action:      AIChatActionAsk,
			ReadOnly:    true,
			Approval:    "none",
			ToolKinds:   []AIToolKind{AIToolKindContextRead},
		},
		{
			ID:          "plan-architect",
			Name:        "Plan Architect",
			Description: "Structured planning profile with read-only project context, search, diagnostics, and git preview.",
			BuiltIn:     true,
			Enabled:     true,
			Action:      AIChatActionPlan,
			ReadOnly:    true,
			Approval:    "none",
			ToolKinds:   []AIToolKind{AIToolKindContextRead},
		},
		{
			ID:          "debug-operator",
			Name:        "Debug Operator",
			Description: "Debugging profile with diagnostics, read-only search, git preview, and approval-gated terminal checks.",
			BuiltIn:     true,
			Enabled:     true,
			Action:      AIChatActionDebug,
			ReadOnly:    false,
			Approval:    "terminal approval required",
			ToolKinds:   []AIToolKind{AIToolKindContextRead, AIToolKindTerminal},
		},
		{
			ID:          "build-reviewer",
			Name:        "Build Reviewer",
			Description: "Build profile that produces patch artifacts and approval-gated tool calls.",
			BuiltIn:     true,
			Enabled:     true,
			Action:      AIChatActionBuild,
			ReadOnly:    false,
			Approval:    "mutation approval required",
			ToolKinds:   []AIToolKind{AIToolKindContextRead, AIToolKindFileWrite, AIToolKindTerminal, AIToolKindMCP},
		},
		{
			ID:          "subagent-runner",
			Name:        "Subagent Runner",
			Description: "Isolated background-agent preview profile with scoped context and shared tool gateway boundaries.",
			BuiltIn:     true,
			Enabled:     true,
			Action:      AIChatActionBuild,
			ReadOnly:    true,
			Approval:    "preview only",
			ToolKinds:   []AIToolKind{AIToolKindSubagent},
		},
		{
			ID:          "review-auditor",
			Name:        "Review Auditor",
			Description: "Read-only review profile focused on defects, regressions, and missing tests.",
			BuiltIn:     true,
			Enabled:     true,
			Action:      AIChatActionReview,
			ReadOnly:    true,
			Approval:    "none",
			ToolKinds:   []AIToolKind{AIToolKindContextRead},
		},
	}
}

func (s *Service) ListPromptWorkflows() []AIPromptWorkflowDescriptor {
	return []AIPromptWorkflowDescriptor{
		{
			ID:          "slash-chat",
			Name:        "Chat",
			Slash:       "/chat",
			Action:      AIChatActionAsk,
			Description: "Chat with visible project context.",
			BuiltIn:     true,
			ProfileID:   "ask-readonly",
			ToolKinds:   []AIToolKind{AIToolKindContextRead},
		},
		{
			ID:          "slash-debug",
			Name:        "Debug",
			Slash:       "/debug",
			Action:      AIChatActionDebug,
			Description: "Inspect failure context and produce evidence-backed debugging guidance.",
			BuiltIn:     true,
			ProfileID:   "debug-operator",
			ToolKinds:   []AIToolKind{AIToolKindContextRead, AIToolKindTerminal},
		},
		{
			ID:          "slash-plan",
			Name:        "Plan",
			Slash:       "/plan",
			Action:      AIChatActionPlan,
			Description: "Inspect read-only project context and create an implementation plan.",
			BuiltIn:     true,
			ProfileID:   "plan-architect",
			ToolKinds:   []AIToolKind{AIToolKindContextRead},
		},
		{
			ID:          "slash-build",
			Name:        "Build",
			Slash:       "/build",
			Action:      AIChatActionBuild,
			Description: "Draft implementation steps and explicit approval-gated tool calls.",
			BuiltIn:     true,
			ProfileID:   "build-reviewer",
			ToolKinds:   []AIToolKind{AIToolKindContextRead, AIToolKindFileWrite, AIToolKindTerminal, AIToolKindMCP},
		},
		{
			ID:          "slash-review",
			Name:        "Review",
			Slash:       "/review",
			Action:      AIChatActionReview,
			Description: "Review current changes and risks without mutation.",
			BuiltIn:     true,
			ProfileID:   "review-auditor",
			ToolKinds:   []AIToolKind{AIToolKindContextRead},
		},
	}
}

func (s *Service) ListContextProviders() []AIContextProviderDescriptor {
	return []AIContextProviderDescriptor{
		{
			ID:          "current_file",
			Name:        "Current File",
			Description: "Sanitized current file window.",
			Capability:  providers.CapabilityChat,
			Enabled:     true,
			Available:   true,
			LocalOnly:   true,
		},
		{
			ID:          "selection",
			Name:        "Selection",
			Description: "Sanitized active editor selection.",
			Capability:  providers.CapabilityChat,
			Enabled:     true,
			Available:   true,
			LocalOnly:   true,
		},
		{
			ID:          "terminal_input",
			Name:        "Terminal Input",
			Description: "Sanitized terminal input snapshot.",
			Capability:  providers.CapabilityTerminalPrediction,
			Enabled:     true,
			Available:   true,
			LocalOnly:   true,
		},
		{
			ID:          "mnemonic",
			Name:        "Mnemonic",
			Description: "Project-local trusted memory graph entries.",
			Capability:  providers.CapabilityChat,
			Enabled:     true,
			Available:   true,
			LocalOnly:   true,
		},
		{
			ID:          "egress",
			Name:        "Egress Ledger",
			Description: "Metadata-only provider egress activity.",
			Capability:  providers.CapabilityChat,
			Enabled:     true,
			Available:   true,
			LocalOnly:   true,
		},
		{
			ID:          "fast_context",
			Name:        "Fast Context",
			Description: "Local lexical retrieval over project files with secret/path guards.",
			Capability:  providers.CapabilityChat,
			Enabled:     true,
			Available:   true,
			LocalOnly:   true,
		},
		{
			ID:          "diagnostics",
			Name:        "Diagnostics",
			Description: "Current file-scoped LSP diagnostics exposed as bounded read-only context.",
			Capability:  providers.CapabilityChat,
			Enabled:     s != nil && s.diagnostics != nil,
			Available:   s != nil && s.diagnostics != nil,
			LocalOnly:   true,
		},
		{
			ID:          "git_diff",
			Name:        "Git Diff",
			Description: "Future sanitized git diff context provider placeholder.",
			Capability:  providers.CapabilityChat,
			Enabled:     false,
			Available:   false,
			LocalOnly:   true,
		},
		{
			ID:          "mcp",
			Name:        "MCP",
			Description: "Metadata-only Arlecchino MCP tool-plane summary; approvals stay separate.",
			Capability:  providers.CapabilityChat,
			Enabled:     s != nil && s.mcpContext != nil,
			Available:   s != nil && s.mcpContext != nil,
			LocalOnly:   true,
		},
	}
}

func (s *Service) ListTools() []AIToolDescriptor {
	return []AIToolDescriptor{
		{
			ID:                     "context.read",
			Name:                   "Read context",
			Description:            "Read sanitized project context selected by the user.",
			Kind:                   AIToolKindContextRead,
			ExecutionAvailable:     true,
			DefaultApprovalMode:    AIApprovalModeReadOnlyAllowed,
			RequiresArtifactReview: false,
		},
		{
			ID:                     "interaction.question",
			Name:                   "Ask structured question",
			Description:            "Create a persistent clarifying-question artifact with up to four ready answers and hover descriptions.",
			Kind:                   AIToolKindContextRead,
			ExecutionAvailable:     true,
			DefaultApprovalMode:    AIApprovalModeReadOnlyAllowed,
			RequiresArtifactReview: false,
		},
		{
			ID:                     "file.read_range",
			Name:                   "Read file range",
			Description:            "Read a bounded, line-numbered range from a project text file before proposing targeted edits.",
			Kind:                   AIToolKindContextRead,
			ExecutionAvailable:     true,
			DefaultApprovalMode:    AIApprovalModeReadOnlyAllowed,
			HardDenyCategories:     []AIToolHardDenyReason{AIToolHardDenyReasonSensitivePaths},
			RequiresArtifactReview: false,
		},
		{
			ID:                     "workspace.grep",
			Name:                   "Search workspace",
			Description:            "Search project text files for bounded line-numbered matches before planning or editing.",
			Kind:                   AIToolKindContextRead,
			ExecutionAvailable:     true,
			DefaultApprovalMode:    AIApprovalModeReadOnlyAllowed,
			HardDenyCategories:     []AIToolHardDenyReason{AIToolHardDenyReasonSensitivePaths},
			RequiresArtifactReview: false,
		},
		{
			ID:                     "diagnostics.read",
			Name:                   "Read diagnostics",
			Description:            "Read bounded current diagnostics for a project file.",
			Kind:                   AIToolKindContextRead,
			ExecutionAvailable:     s != nil && s.diagnostics != nil,
			DefaultApprovalMode:    AIApprovalModeReadOnlyAllowed,
			HardDenyCategories:     []AIToolHardDenyReason{AIToolHardDenyReasonSensitivePaths},
			RequiresArtifactReview: false,
		},
		{
			ID:                     "file.patch.preview",
			Name:                   "Preview file patch",
			Description:            "Create a patch artifact for explicit review before any file is changed.",
			Kind:                   AIToolKindFileWrite,
			ExecutionAvailable:     true,
			DefaultApprovalMode:    AIApprovalModeAskEachTime,
			HardDenyCategories:     []AIToolHardDenyReason{AIToolHardDenyReasonSensitivePaths, AIToolHardDenyReasonOutsideProjectWrite},
			RequiresArtifactReview: true,
		},
		{
			ID:                     "file.edit.preview",
			Name:                   "Preview targeted edit",
			Description:            "Create a patch artifact from a narrow replace or insert operation; rejects whole-file rewrites.",
			Kind:                   AIToolKindFileWrite,
			ExecutionAvailable:     true,
			DefaultApprovalMode:    AIApprovalModeAskEachTime,
			HardDenyCategories:     []AIToolHardDenyReason{AIToolHardDenyReasonSensitivePaths, AIToolHardDenyReasonOutsideProjectWrite},
			RequiresArtifactReview: true,
		},
		{
			ID:                     "file.create.preview",
			Name:                   "Preview new file",
			Description:            "Create a patch artifact for a new project text file without writing it directly.",
			Kind:                   AIToolKindFileWrite,
			ExecutionAvailable:     true,
			DefaultApprovalMode:    AIApprovalModeAskEachTime,
			HardDenyCategories:     []AIToolHardDenyReason{AIToolHardDenyReasonSensitivePaths, AIToolHardDenyReasonOutsideProjectWrite},
			RequiresArtifactReview: true,
		},
		{
			ID:                     "file.patch.apply",
			Name:                   "Apply reviewed patch",
			Description:            "Apply a validated patch artifact after explicit approval.",
			Kind:                   AIToolKindFileWrite,
			ExecutionAvailable:     true,
			DefaultApprovalMode:    AIApprovalModeFullAccess,
			HardDenyCategories:     []AIToolHardDenyReason{AIToolHardDenyReasonSensitivePaths, AIToolHardDenyReasonOutsideProjectWrite},
			RequiresArtifactReview: true,
		},
		{
			ID:                     "terminal.preview",
			Name:                   "Preview terminal command",
			Description:            "Show terminal command intent, cwd, and risk; execute only with active approval.",
			Kind:                   AIToolKindTerminal,
			ExecutionAvailable:     true,
			DefaultApprovalMode:    AIApprovalModeAskEachTime,
			HardDenyCategories:     []AIToolHardDenyReason{AIToolHardDenyReasonSecrets, AIToolHardDenyReasonDestructiveShell, AIToolHardDenyReasonTerminalFileWrite, AIToolHardDenyReasonNonLoopbackNetwork},
			RequiresArtifactReview: true,
		},
		{
			ID:                     "git.preview",
			Name:                   "Preview Git state",
			Description:            "Read git status, diff summary, or recent log without mutation.",
			Kind:                   AIToolKindContextRead,
			ExecutionAvailable:     true,
			DefaultApprovalMode:    AIApprovalModeReadOnlyAllowed,
			RequiresArtifactReview: false,
		},
		{
			ID:                     "memory.search",
			Name:                   "Search Mnemonic memory",
			Description:            "Search shared project Mnemonic memory with trust and source labels.",
			Kind:                   AIToolKindContextRead,
			ExecutionAvailable:     true,
			DefaultApprovalMode:    AIApprovalModeReadOnlyAllowed,
			RequiresArtifactReview: false,
		},
		{
			ID:                     "memory.context",
			Name:                   "Read Mnemonic context",
			Description:            "Read a compact shared Mnemonic memory summary without promoting generated entries.",
			Kind:                   AIToolKindContextRead,
			ExecutionAvailable:     true,
			DefaultApprovalMode:    AIApprovalModeReadOnlyAllowed,
			RequiresArtifactReview: false,
		},
		{
			ID:                     "memory.propose_save",
			Name:                   "Propose Mnemonic save",
			Description:            "Create a reviewable Mnemonic memory-save proposal; does not save trusted memory directly.",
			Kind:                   AIToolKindContextRead,
			ExecutionAvailable:     true,
			DefaultApprovalMode:    AIApprovalModeReadOnlyAllowed,
			RequiresArtifactReview: true,
		},
		{
			ID:                     "mcp.preview",
			Name:                   "Preview MCP action",
			Description:            "Show MCP server, tool name, and arguments before any MCP execution is available.",
			Kind:                   AIToolKindMCP,
			ExecutionAvailable:     true,
			DefaultApprovalMode:    AIApprovalModeAskEachTime,
			HardDenyCategories:     []AIToolHardDenyReason{AIToolHardDenyReasonSecrets, AIToolHardDenyReasonFrontierCloudEgress},
			RequiresArtifactReview: true,
		},
		{
			ID:                     "mcp.execute",
			Name:                   "Execute MCP action",
			Description:            "Policy-gated MCP tool execution through AI approval, MCP permission, subtool risk classification, and audit.",
			Kind:                   AIToolKindMCP,
			ExecutionAvailable:     s != nil && s.mcpExecutor != nil,
			DefaultApprovalMode:    AIApprovalModeFullAccess,
			HardDenyCategories:     []AIToolHardDenyReason{AIToolHardDenyReasonSecrets, AIToolHardDenyReasonFrontierCloudEgress},
			RequiresArtifactReview: true,
		},
		{
			ID:                     "subagent.preview",
			Name:                   "Preview subagent task",
			Description:            "Create an isolated background-agent preview artifact with scoped context and no mutation.",
			Kind:                   AIToolKindSubagent,
			ExecutionAvailable:     true,
			DefaultApprovalMode:    AIApprovalModeAskEachTime,
			RequiresArtifactReview: true,
		},
	}
}

func (s *Service) GetEmbeddingStatus() AIEmbeddingStatus {
	return AIEmbeddingStatus{
		Status: "disabled_no_local_model",
		Reason: "Embeddings are intentionally disabled in this backend slice: no downloads, no external APIs, and no bundled weights.",
		Providers: []AIEmbeddingProviderDescriptor{
			{
				ID:        "local-embedding-placeholder",
				Name:      "Local embedding provider seam",
				Local:     true,
				Available: false,
				Reason:    "No local embedding model is configured.",
			},
		},
		UpdatedAt: utcNow(),
	}
}
