// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

/**
 * PredictionResult — результат предсказания
 */
export class PredictionResult {
    /**
     * Полная команда
     */
    "Text": string;

    /**
     * Часть для дополнения
     */
    "Completion": string;

    /**
     * Preview output (для safe commands)
     */
    "Output": string;

    /**
     * "history", "plugin", "safe"
     */
    "Source": string;

    /**
     * 0.0 - 1.0
     */
    "Confidence": number;

    /** Creates a new PredictionResult instance. */
    constructor($$source: Partial<PredictionResult> = {}) {
        if (!("Text" in $$source)) {
            this["Text"] = "";
        }
        if (!("Completion" in $$source)) {
            this["Completion"] = "";
        }
        if (!("Output" in $$source)) {
            this["Output"] = "";
        }
        if (!("Source" in $$source)) {
            this["Source"] = "";
        }
        if (!("Confidence" in $$source)) {
            this["Confidence"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PredictionResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PredictionResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PredictionResult($$parsedSource as Partial<PredictionResult>);
    }
}
