// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

export class Project {
    "id": number;
    "name": string;
    "path": string;

    /**
     * laravel, django, rails, express, go, unknown
     */
    "framework": string;
    "version": string;
    "created_at": string;
    "last_opened": string;
    "is_favorite": boolean;

    /** Creates a new Project instance. */
    constructor($$source: Partial<Project> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("framework" in $$source)) {
            this["framework"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("last_opened" in $$source)) {
            this["last_opened"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("is_favorite" in $$source)) {
            this["is_favorite"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Project instance from a string or object.
     */
    static createFrom($$source: any = {}): Project {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Project($$parsedSource as Partial<Project>);
    }
}
