// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

export enum SymbolKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SymbolKindClass = "class",
    SymbolKindInterface = "interface",
    SymbolKindTrait = "trait",
    SymbolKindFunction = "function",
    SymbolKindMethod = "method",
    SymbolKindProperty = "property",
    SymbolKindVariable = "variable",
    SymbolKindConstant = "constant",
    SymbolKindEnum = "enum",
    SymbolKindEnumCase = "enum_case",
    SymbolKindStruct = "struct",
    SymbolKindField = "field",
    SymbolKindType = "type",
    SymbolKindModule = "module",
    SymbolKindPackage = "package",
    SymbolKindNamespace = "namespace",
    SymbolKindComponent = "component",
    SymbolKindDecorator = "decorator",
    SymbolKindRoute = "route",
    SymbolKindView = "view",
    SymbolKindModel = "model",
    SymbolKindController = "controller",
    SymbolKindMiddleware = "middleware",
    SymbolKindMigration = "migration",
    SymbolKindConfig = "config",
    SymbolKindTest = "test",
    SymbolKindSnippet = "snippet",
    SymbolKindText = "text",
};

export enum SymbolSource {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SourceIndex = "index",
    SourceAST = "ast",
    SourceLSP = "lsp",
    SourceLibrary = "library",
    SourceVirtual = "virtual",
    SourcePredictive = "predictive",
    SourceLocal = "local",
    SourceFillAll = "fill_all",
    SourceKeywords = "keywords",
};
