// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeModels(arg1) {
  return window['go']['main']['App']['AnalyzeModels'](arg1);
}

export function CacheClear(arg1) {
  return window['go']['main']['App']['CacheClear'](arg1);
}

export function CancelPrediction() {
  return window['go']['main']['App']['CancelPrediction']();
}

export function ClearCompiled() {
  return window['go']['main']['App']['ClearCompiled']();
}

export function CloseAllTerminals() {
  return window['go']['main']['App']['CloseAllTerminals']();
}

export function CloseProject() {
  return window['go']['main']['App']['CloseProject']();
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function ConfigCache() {
  return window['go']['main']['App']['ConfigCache']();
}

export function ConfirmPrediction(arg1) {
  return window['go']['main']['App']['ConfirmPrediction'](arg1);
}

export function CreateComponent(arg1, arg2) {
  return window['go']['main']['App']['CreateComponent'](arg1, arg2);
}

export function CreateController(arg1, arg2) {
  return window['go']['main']['App']['CreateController'](arg1, arg2);
}

export function CreateEnum(arg1, arg2) {
  return window['go']['main']['App']['CreateEnum'](arg1, arg2);
}

export function CreateEvent(arg1, arg2) {
  return window['go']['main']['App']['CreateEvent'](arg1, arg2);
}

export function CreateFactory(arg1, arg2) {
  return window['go']['main']['App']['CreateFactory'](arg1, arg2);
}

export function CreateJob(arg1, arg2) {
  return window['go']['main']['App']['CreateJob'](arg1, arg2);
}

export function CreateLivewire(arg1, arg2) {
  return window['go']['main']['App']['CreateLivewire'](arg1, arg2);
}

export function CreateMail(arg1, arg2) {
  return window['go']['main']['App']['CreateMail'](arg1, arg2);
}

export function CreateMigration(arg1, arg2) {
  return window['go']['main']['App']['CreateMigration'](arg1, arg2);
}

export function CreateModel(arg1, arg2) {
  return window['go']['main']['App']['CreateModel'](arg1, arg2);
}

export function CreateNewProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateNewProject'](arg1, arg2, arg3);
}

export function CreateNotification(arg1, arg2) {
  return window['go']['main']['App']['CreateNotification'](arg1, arg2);
}

export function CreatePolicy(arg1, arg2) {
  return window['go']['main']['App']['CreatePolicy'](arg1, arg2);
}

export function CreateResource(arg1, arg2) {
  return window['go']['main']['App']['CreateResource'](arg1, arg2);
}

export function CreateSeeder(arg1, arg2) {
  return window['go']['main']['App']['CreateSeeder'](arg1, arg2);
}

export function CreateTerminal(arg1, arg2) {
  return window['go']['main']['App']['CreateTerminal'](arg1, arg2);
}

export function DBSeed(arg1) {
  return window['go']['main']['App']['DBSeed'](arg1);
}

export function DetectLanguage(arg1) {
  return window['go']['main']['App']['DetectLanguage'](arg1);
}

export function DetectLanguageFromFile(arg1, arg2) {
  return window['go']['main']['App']['DetectLanguageFromFile'](arg1, arg2);
}

export function DispatchCommand(arg1) {
  return window['go']['main']['App']['DispatchCommand'](arg1);
}

export function DumpAutoload() {
  return window['go']['main']['App']['DumpAutoload']();
}

export function ExecuteQuery(arg1, arg2) {
  return window['go']['main']['App']['ExecuteQuery'](arg1, arg2);
}

export function ExpandTag(arg1) {
  return window['go']['main']['App']['ExpandTag'](arg1);
}

export function FindEnv(arg1) {
  return window['go']['main']['App']['FindEnv'](arg1);
}

export function FindFileByName(arg1, arg2) {
  return window['go']['main']['App']['FindFileByName'](arg1, arg2);
}

export function FormatCode(arg1, arg2) {
  return window['go']['main']['App']['FormatCode'](arg1, arg2);
}

export function GetAllLSPServers() {
  return window['go']['main']['App']['GetAllLSPServers']();
}

export function GetCurrentProjectFramework() {
  return window['go']['main']['App']['GetCurrentProjectFramework']();
}

export function GetCurrentProjectID() {
  return window['go']['main']['App']['GetCurrentProjectID']();
}

export function GetCurrentProjectPath() {
  return window['go']['main']['App']['GetCurrentProjectPath']();
}

export function GetCurrentWorkDir() {
  return window['go']['main']['App']['GetCurrentWorkDir']();
}

export function GetDependencyGraph(arg1, arg2) {
  return window['go']['main']['App']['GetDependencyGraph'](arg1, arg2);
}

export function GetDevToolsStatus() {
  return window['go']['main']['App']['GetDevToolsStatus']();
}

export function GetDispatcherPinned() {
  return window['go']['main']['App']['GetDispatcherPinned']();
}

export function GetDispatcherRecent() {
  return window['go']['main']['App']['GetDispatcherRecent']();
}

export function GetDispatcherSuggestions(arg1) {
  return window['go']['main']['App']['GetDispatcherSuggestions'](arg1);
}

export function GetEditorCompletions(arg1) {
  return window['go']['main']['App']['GetEditorCompletions'](arg1);
}

export function GetGitBlame(arg1) {
  return window['go']['main']['App']['GetGitBlame'](arg1);
}

export function GetGitBranch() {
  return window['go']['main']['App']['GetGitBranch']();
}

export function GetGitBranches() {
  return window['go']['main']['App']['GetGitBranches']();
}

export function GetGitCommitDiff(arg1) {
  return window['go']['main']['App']['GetGitCommitDiff'](arg1);
}

export function GetGitDiff(arg1, arg2) {
  return window['go']['main']['App']['GetGitDiff'](arg1, arg2);
}

export function GetGitFileAtCommit(arg1, arg2) {
  return window['go']['main']['App']['GetGitFileAtCommit'](arg1, arg2);
}

export function GetGitFileDiffBetweenCommits(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetGitFileDiffBetweenCommits'](arg1, arg2, arg3);
}

export function GetGitLog(arg1, arg2) {
  return window['go']['main']['App']['GetGitLog'](arg1, arg2);
}

export function GetGitShow(arg1) {
  return window['go']['main']['App']['GetGitShow'](arg1);
}

export function GetGitStatus() {
  return window['go']['main']['App']['GetGitStatus']();
}

export function GetInlineSuggestion(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetInlineSuggestion'](arg1, arg2, arg3, arg4, arg5);
}

export function GetLSPBinaryPath(arg1) {
  return window['go']['main']['App']['GetLSPBinaryPath'](arg1);
}

export function GetLSPForFile(arg1) {
  return window['go']['main']['App']['GetLSPForFile'](arg1);
}

export function GetLSPInstallStatus() {
  return window['go']['main']['App']['GetLSPInstallStatus']();
}

export function GetLSPStatus() {
  return window['go']['main']['App']['GetLSPStatus']();
}

export function GetLanguageForFile(arg1) {
  return window['go']['main']['App']['GetLanguageForFile'](arg1);
}

export function GetLaravelVersion(arg1) {
  return window['go']['main']['App']['GetLaravelVersion'](arg1);
}

export function GetMiddlewareList() {
  return window['go']['main']['App']['GetMiddlewareList']();
}

export function GetPluginCommands() {
  return window['go']['main']['App']['GetPluginCommands']();
}

export function GetRecentProjects(arg1) {
  return window['go']['main']['App']['GetRecentProjects'](arg1);
}

export function GetRelatedFiles(arg1) {
  return window['go']['main']['App']['GetRelatedFiles'](arg1);
}

export function GetRouteList(arg1) {
  return window['go']['main']['App']['GetRouteList'](arg1);
}

export function GetSupportedLanguages() {
  return window['go']['main']['App']['GetSupportedLanguages']();
}

export function GetTerminalHistory(arg1) {
  return window['go']['main']['App']['GetTerminalHistory'](arg1);
}

export function GetTerminalPreview(arg1) {
  return window['go']['main']['App']['GetTerminalPreview'](arg1);
}

export function GoToDefinition(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['GoToDefinition'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportShellHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportShellHistory'](arg1, arg2, arg3);
}

export function IndexLaravelAll() {
  return window['go']['main']['App']['IndexLaravelAll']();
}

export function IndexLaravelConfig() {
  return window['go']['main']['App']['IndexLaravelConfig']();
}

export function IndexLaravelModels() {
  return window['go']['main']['App']['IndexLaravelModels']();
}

export function IndexLaravelRoutes() {
  return window['go']['main']['App']['IndexLaravelRoutes']();
}

export function IndexLaravelViews() {
  return window['go']['main']['App']['IndexLaravelViews']();
}

export function InitDispatcherForProject() {
  return window['go']['main']['App']['InitDispatcherForProject']();
}

export function InspectProject() {
  return window['go']['main']['App']['InspectProject']();
}

export function InstallAll() {
  return window['go']['main']['App']['InstallAll']();
}

export function InstallBreeze() {
  return window['go']['main']['App']['InstallBreeze']();
}

export function InstallDevTool(arg1) {
  return window['go']['main']['App']['InstallDevTool'](arg1);
}

export function InstallFortify() {
  return window['go']['main']['App']['InstallFortify']();
}

export function InstallJetstream() {
  return window['go']['main']['App']['InstallJetstream']();
}

export function InstallLSPServer(arg1) {
  return window['go']['main']['App']['InstallLSPServer'](arg1);
}

export function InstallLivewire() {
  return window['go']['main']['App']['InstallLivewire']();
}

export function InstallPackage(arg1, arg2) {
  return window['go']['main']['App']['InstallPackage'](arg1, arg2);
}

export function IsLSPInstalling(arg1) {
  return window['go']['main']['App']['IsLSPInstalling'](arg1);
}

export function IsLangDetectorLoaded() {
  return window['go']['main']['App']['IsLangDetectorLoaded']();
}

export function IsLaravelProject(arg1) {
  return window['go']['main']['App']['IsLaravelProject'](arg1);
}

export function LSPApplyWorkspaceEdit(arg1) {
  return window['go']['main']['App']['LSPApplyWorkspaceEdit'](arg1);
}

export function LSPGetCodeActions(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LSPGetCodeActions'](arg1, arg2, arg3, arg4);
}

export function LSPGetDiagnostics(arg1) {
  return window['go']['main']['App']['LSPGetDiagnostics'](arg1);
}

export function LSPGoToDefinition(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LSPGoToDefinition'](arg1, arg2, arg3, arg4);
}

export function LSPHover(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LSPHover'](arg1, arg2, arg3, arg4);
}

export function LSPSignatureHelp(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LSPSignatureHelp'](arg1, arg2, arg3, arg4);
}

export function ListInstalledPackages() {
  return window['go']['main']['App']['ListInstalledPackages']();
}

export function ListTerminalSessions() {
  return window['go']['main']['App']['ListTerminalSessions']();
}

export function Migrate(arg1) {
  return window['go']['main']['App']['Migrate'](arg1);
}

export function MigrateFresh(arg1) {
  return window['go']['main']['App']['MigrateFresh'](arg1);
}

export function MigrateRefresh(arg1) {
  return window['go']['main']['App']['MigrateRefresh'](arg1);
}

export function MigrateReset(arg1) {
  return window['go']['main']['App']['MigrateReset'](arg1);
}

export function MigrateRollback(arg1) {
  return window['go']['main']['App']['MigrateRollback'](arg1);
}

export function MigrateSeed(arg1) {
  return window['go']['main']['App']['MigrateSeed'](arg1);
}

export function MigrateStatus() {
  return window['go']['main']['App']['MigrateStatus']();
}

export function NotifyFileChanged(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['NotifyFileChanged'](arg1, arg2, arg3, arg4);
}

export function NotifyFileClosed(arg1, arg2) {
  return window['go']['main']['App']['NotifyFileClosed'](arg1, arg2);
}

export function NotifyFileOpened(arg1, arg2, arg3) {
  return window['go']['main']['App']['NotifyFileOpened'](arg1, arg2, arg3);
}

export function OpenProject(arg1) {
  return window['go']['main']['App']['OpenProject'](arg1);
}

export function ParseCommand(arg1) {
  return window['go']['main']['App']['ParseCommand'](arg1);
}

export function PinCommand(arg1) {
  return window['go']['main']['App']['PinCommand'](arg1);
}

export function PredictCommand(arg1) {
  return window['go']['main']['App']['PredictCommand'](arg1);
}

export function PredictTerminalCommand(arg1) {
  return window['go']['main']['App']['PredictTerminalCommand'](arg1);
}

export function PublishAssets(arg1, arg2) {
  return window['go']['main']['App']['PublishAssets'](arg1, arg2);
}

export function QueueWork(arg1, arg2) {
  return window['go']['main']['App']['QueueWork'](arg1, arg2);
}

export function ReadDirectory(arg1) {
  return window['go']['main']['App']['ReadDirectory'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RecordCommandExecution(arg1, arg2, arg3) {
  return window['go']['main']['App']['RecordCommandExecution'](arg1, arg2, arg3);
}

export function RecordCompletionUsage(arg1) {
  return window['go']['main']['App']['RecordCompletionUsage'](arg1);
}

export function RecordFileAccess(arg1) {
  return window['go']['main']['App']['RecordFileAccess'](arg1);
}

export function RecordGhostRejected() {
  return window['go']['main']['App']['RecordGhostRejected']();
}

export function RecordGhostShown() {
  return window['go']['main']['App']['RecordGhostShown']();
}

export function RecordTypingActivity(arg1) {
  return window['go']['main']['App']['RecordTypingActivity'](arg1);
}

export function RemovePackage(arg1, arg2) {
  return window['go']['main']['App']['RemovePackage'](arg1, arg2);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RestartLSPServer(arg1) {
  return window['go']['main']['App']['RestartLSPServer'](arg1);
}

export function RouteCache() {
  return window['go']['main']['App']['RouteCache']();
}

export function RunGitCommand(arg1) {
  return window['go']['main']['App']['RunGitCommand'](arg1);
}

export function RunMigrate() {
  return window['go']['main']['App']['RunMigrate']();
}

export function ScheduleRun() {
  return window['go']['main']['App']['ScheduleRun']();
}

export function SearchClasses(arg1) {
  return window['go']['main']['App']['SearchClasses'](arg1);
}

export function SearchContent(arg1) {
  return window['go']['main']['App']['SearchContent'](arg1);
}

export function SearchFiles(arg1) {
  return window['go']['main']['App']['SearchFiles'](arg1);
}

export function SearchInProject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SearchInProject'](arg1, arg2, arg3, arg4);
}

export function SearchSymbols(arg1) {
  return window['go']['main']['App']['SearchSymbols'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SendTerminalText(arg1, arg2) {
  return window['go']['main']['App']['SendTerminalText'](arg1, arg2);
}

export function Serve(arg1) {
  return window['go']['main']['App']['Serve'](arg1);
}

export function ShowPackageInfo(arg1) {
  return window['go']['main']['App']['ShowPackageInfo'](arg1);
}

export function StorageLink() {
  return window['go']['main']['App']['StorageLink']();
}

export function SuggestCommand(arg1) {
  return window['go']['main']['App']['SuggestCommand'](arg1);
}

export function Tinker() {
  return window['go']['main']['App']['Tinker']();
}

export function UnpinCommand(arg1) {
  return window['go']['main']['App']['UnpinCommand'](arg1);
}

export function UpdateAll() {
  return window['go']['main']['App']['UpdateAll']();
}

export function UpdatePackage(arg1) {
  return window['go']['main']['App']['UpdatePackage'](arg1);
}

export function UpdatePrediction(arg1) {
  return window['go']['main']['App']['UpdatePrediction'](arg1);
}

export function ValidateEnvironment() {
  return window['go']['main']['App']['ValidateEnvironment']();
}

export function ViewCache() {
  return window['go']['main']['App']['ViewCache']();
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminal'](arg1, arg2);
}
