// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {system} from '../models';
import {plugins} from '../models';
import {main} from '../models';
import {indexer} from '../models';
import {depsync} from '../models';
import {welcome} from '../models';
import {execution} from '../models';
import {lsp} from '../models';
import {brain} from '../models';
import {project} from '../models';
import {composer} from '../models';

export function AnalyzeModels(arg1:string):Promise<any>;

export function CacheClear(arg1:system.CacheOptions):Promise<string>;

export function CancelPrediction():Promise<void>;

export function ClearApprovedDependencyActions():Promise<void>;

export function ClearCompiled():Promise<string>;

export function CloseAllTerminals():Promise<void>;

export function CloseProject():Promise<void>;

export function CloseTerminal(arg1:string):Promise<void>;

export function ConfigCache():Promise<string>;

export function ConfirmPrediction(arg1:string):Promise<void>;

export function CreateComponent(arg1:string,arg2:plugins.ComponentOptions):Promise<void>;

export function CreateController(arg1:string,arg2:plugins.ControllerOptions):Promise<void>;

export function CreateDirectory(arg1:string):Promise<void>;

export function CreateEnum(arg1:string,arg2:plugins.EnumClassOptions):Promise<void>;

export function CreateEvent(arg1:string,arg2:plugins.EventClassOptions):Promise<void>;

export function CreateFactory(arg1:string,arg2:plugins.FactoryClassOptions):Promise<void>;

export function CreateJob(arg1:string,arg2:plugins.JobOptions):Promise<void>;

export function CreateLivewire(arg1:string,arg2:plugins.LivewireComponentOptions):Promise<void>;

export function CreateMail(arg1:string,arg2:plugins.MailOptions):Promise<void>;

export function CreateMigration(arg1:string,arg2:plugins.MigrationOptions):Promise<void>;

export function CreateModel(arg1:string,arg2:plugins.ModelOptions):Promise<void>;

export function CreateNewProject(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CreateNotification(arg1:string,arg2:plugins.NotificationOptions):Promise<void>;

export function CreatePolicy(arg1:string,arg2:plugins.PolicyClassOptions):Promise<void>;

export function CreateResource(arg1:string,arg2:plugins.ResourceClassOptions):Promise<void>;

export function CreateSeeder(arg1:string,arg2:plugins.SeederClassOptions):Promise<void>;

export function CreateTerminal(arg1:string,arg2:string):Promise<void>;

export function CreateTerminalForProject(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DBSeed(arg1:string):Promise<string>;

export function DetectLanguage(arg1:string):Promise<Array<main.LanguagePrediction>>;

export function DetectLanguageFromFile(arg1:string,arg2:string):Promise<string>;

export function DispatchCommand(arg1:string):Promise<main.DispatcherResultJS>;

export function DumpAutoload():Promise<void>;

export function ExecuteQuery(arg1:string,arg2:Array<any>):Promise<any>;

export function ExpandTag(arg1:string):Promise<string>;

export function FindEnv(arg1:string):Promise<boolean>;

export function FindFileByName(arg1:string,arg2:string):Promise<Array<string>>;

export function FormatCode(arg1:string,arg2:string):Promise<string>;

export function GetAllLSPServers():Promise<Array<main.LSPServerInfo>>;

export function GetCurrentProjectFramework():Promise<string>;

export function GetCurrentProjectID():Promise<string>;

export function GetCurrentProjectPath():Promise<string>;

export function GetCurrentWorkDir():Promise<string>;

export function GetDependencyGraph(arg1:string,arg2:number):Promise<indexer.DependencyGraph>;

export function GetDependencyPolicyPlan(arg1:string):Promise<depsync.PolicyPlan>;

export function GetDependencySyncPlan(arg1:string):Promise<depsync.Plan>;

export function GetDevToolsStatus():Promise<Array<welcome.ToolStatus>>;

export function GetDispatcherPinned():Promise<Array<main.ResultItemJS>>;

export function GetDispatcherRecent():Promise<Array<main.ResultItemJS>>;

export function GetDispatcherSuggestions(arg1:string):Promise<Array<main.ResultItemJS>>;

export function GetEditorCompletions(arg1:main.EditorCompletionContext):Promise<main.EditorCompletionResult>;

export function GetExecutionProfiles(arg1:main.ExecutionProfilesRequest):Promise<execution.ProfileSet>;

export function GetGitBlame(arg1:string):Promise<string>;

export function GetGitBranch():Promise<string>;

export function GetGitBranches():Promise<Array<string>>;

export function GetGitCommitDiff(arg1:string):Promise<string>;

export function GetGitDiff(arg1:string,arg2:boolean):Promise<string>;

export function GetGitFileAtCommit(arg1:string,arg2:string):Promise<string>;

export function GetGitFileDiffBetweenCommits(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetGitLog(arg1:number,arg2:string):Promise<Array<main.GitCommitInfo>>;

export function GetGitShow(arg1:string):Promise<string>;

export function GetGitStatus():Promise<string>;

export function GetInlineSuggestion(arg1:string,arg2:string,arg3:number,arg4:number,arg5:string):Promise<string>;

export function GetLSPBinaryPath(arg1:string):Promise<string>;

export function GetLSPForFile(arg1:string):Promise<main.LSPServerInfo>;

export function GetLSPInstallStatus():Promise<Array<welcome.ToolStatus>>;

export function GetLSPStatus():Promise<Array<lsp.ServerStatus>>;

export function GetLanguageForFile(arg1:string):Promise<main.LanguageInfoResult>;

export function GetLaravelVersion(arg1:string):Promise<string>;

export function GetLastAutocompleteTrace():Promise<brain.CompletionTrace>;

export function GetMiddlewareList():Promise<any>;

export function GetPluginCommands():Promise<Array<main.PluginCommandDefJS>>;

export function GetRecentProjects(arg1:number):Promise<Array<project.Project>>;

export function GetRelatedFiles(arg1:string):Promise<Array<indexer.FileRelation>>;

export function GetRouteList(arg1:string):Promise<any>;

export function GetSupportedLanguages():Promise<Array<string>>;

export function GetTerminalHistory(arg1:number):Promise<Array<string>>;

export function GetTerminalPreview(arg1:string):Promise<main.TerminalPreviewJS>;

export function GoToDefinition(arg1:string,arg2:string,arg3:number,arg4:number,arg5:string,arg6:string,arg7:string):Promise<Array<main.DefinitionResult>>;

export function Greet(arg1:string):Promise<string>;

export function ImportShellHistory(arg1:string,arg2:string,arg3:string):Promise<void>;

export function IndexLaravelAll():Promise<Record<string, any>>;

export function IndexLaravelConfig():Promise<string>;

export function IndexLaravelModels():Promise<string>;

export function IndexLaravelRoutes():Promise<string>;

export function IndexLaravelViews():Promise<string>;

export function InitDispatcherForProject():Promise<void>;

export function InspectProject():Promise<any>;

export function InstallAll():Promise<void>;

export function InstallBreeze():Promise<void>;

export function InstallDevTool(arg1:string):Promise<string>;

export function InstallFortify():Promise<void>;

export function InstallJetstream():Promise<void>;

export function InstallLSPServer(arg1:string):Promise<void>;

export function InstallLivewire():Promise<void>;

export function InstallPackage(arg1:string,arg2:composer.InstallOptions):Promise<void>;

export function IsLSPInstalling(arg1:string):Promise<boolean>;

export function IsLangDetectorLoaded():Promise<boolean>;

export function IsLaravelProject(arg1:string):Promise<boolean>;

export function LSPApplyWorkspaceEdit(arg1:main.LSPWorkspaceEdit):Promise<void>;

export function LSPGetCodeActions(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<main.LSPCodeAction>>;

export function LSPGetDiagnostics(arg1:string):Promise<Array<main.LSPDiagnostic>>;

export function LSPGoToDefinition(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<main.LSPDefinitionResult>>;

export function LSPHover(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function LSPPreloadProjectDiagnostics(arg1:string):Promise<boolean>;

export function LSPSignatureHelp(arg1:string,arg2:string,arg3:number,arg4:number):Promise<main.SignatureHelpResult>;

export function ListApprovedDependencyActions():Promise<Array<string>>;

export function ListInstalledPackages():Promise<string>;

export function ListTerminalSessions():Promise<Array<string>>;

export function Migrate(arg1:system.MigrateOptions):Promise<string>;

export function MigrateFresh(arg1:system.MigrateRefreshOptions):Promise<string>;

export function MigrateRefresh(arg1:system.MigrateRefreshOptions):Promise<string>;

export function MigrateReset(arg1:system.MigrateResetOptions):Promise<string>;

export function MigrateRollback(arg1:system.MigrateRollbackOptions):Promise<string>;

export function MigrateSeed(arg1:system.MigrateOptions):Promise<string>;

export function MigrateStatus():Promise<string>;

export function NotifyFileChanged(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function NotifyFileClosed(arg1:string,arg2:string):Promise<void>;

export function NotifyFileOpened(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenProject(arg1:string):Promise<void>;

export function ParseCommand(arg1:string):Promise<Record<string, any>>;

export function PinCommand(arg1:string):Promise<void>;

export function PredictCommand(arg1:string):Promise<main.ClassResult>;

export function PredictTerminalCommand(arg1:main.TerminalPredictionRequest):Promise<main.TerminalPredictionResponse>;

export function PublishAssets(arg1:string,arg2:Array<string>):Promise<void>;

export function QueueWork(arg1:string,arg2:string):Promise<void>;

export function ReadDirectory(arg1:string):Promise<Array<main.FileEntry>>;

export function ReadFile(arg1:string):Promise<string>;

export function RecordCommandExecution(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RecordCompletionUsage(arg1:string):Promise<void>;

export function RecordFileAccess(arg1:string):Promise<void>;

export function RecordGhostRejected():Promise<void>;

export function RecordGhostShown():Promise<void>;

export function RecordTypingActivity(arg1:number):Promise<void>;

export function RemovePackage(arg1:string,arg2:composer.RemoveOptions):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestartLSPServer(arg1:string):Promise<boolean>;

export function RouteCache():Promise<string>;

export function RunDependencyPolicySync(arg1:depsync.ExecuteRequest):Promise<depsync.ExecuteResult>;

export function RunGitCommand(arg1:Array<string>):Promise<string>;

export function RunMigrate():Promise<void>;

export function ScheduleRun():Promise<string>;

export function SearchClasses(arg1:string):Promise<Array<main.ClassResult>>;

export function SearchContent(arg1:string):Promise<Array<main.ResultItemJS>>;

export function SearchFiles(arg1:string):Promise<Array<main.ResultItemJS>>;

export function SearchInProject(arg1:string,arg2:boolean,arg3:boolean,arg4:boolean):Promise<Array<main.SearchResult>>;

export function SearchSymbols(arg1:string):Promise<Array<main.ResultItemJS>>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SendTerminalText(arg1:string,arg2:string):Promise<void>;

export function Serve(arg1:system.ServeOptions):Promise<void>;

export function ShowPackageInfo(arg1:string):Promise<string>;

export function StorageLink():Promise<string>;

export function SuggestCommand(arg1:string):Promise<Array<main.CommandSuggestion>>;

export function SyncProjectDependencies(arg1:string):Promise<Record<string, string>>;

export function Tinker():Promise<void>;

export function UnpinCommand(arg1:string):Promise<void>;

export function UpdateAll():Promise<void>;

export function UpdatePackage(arg1:string):Promise<void>;

export function UpdatePrediction(arg1:string):Promise<void>;

export function ValidateEnvironment():Promise<Record<string, boolean>>;

export function ViewCache():Promise<string>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;
